### ISSUE TITLE
使用截图翻译的时候B站视频会黑屏

### ISSUE THREAD

**Issue by sq9960** [InkTimeRecord/TTime#10]
截图翻译的时候B站视频会黑屏，但鼠标经过又会出现内容

**Comment by ByLiangCheng** [comment]
截图翻译目前测试，是发现截图后动图或视频会还在动，这个问题下个版本解决，不过暂时没有测试出黑屏的情况，请问有示例或可以复现吗？

**Comment by ByLiangCheng** [comment]
新版已发布，此问题已修复，下载最新版即可
