### ISSUE TITLE
[Feature] 可以增加支持win7系统，我电脑跟不上了。

### ISSUE THREAD

**Issue by asdsfdsfsdfs** [InkTimeRecord/TTime#100]
**功能描述 / Function Description**
可以支持win7系统吗，win7系统的截图翻译跟OCR截图都不能用，其他暂时没发现问题。

**Comment by ByLiangCheng** [comment]
目前Win7默认的OCR的是有这个问题

如果想使用建议可以在设置 -> 翻译源设置 -> 文字识别 -> 开启TTime在线OCR 或 第三方OCR服务

后面有时间的话会考虑优化

**Comment by asdsfdsfsdfs** [comment]
大佬，刚试过了不行。 截图翻译也不行，大佬有空闲的时候看看要不要增加个win7系统支持~~

**Comment by ByLiangCheng** [comment]
截图翻译不行指的是？截图错误还是截图显示一直在识别中呢？

**Comment by asdsfdsfsdfs** [comment]
一直显示识别中

**Comment by asdsfdsfsdfs** [comment]
截图翻译一直显示"文字识别中···"    OCR也是一样的问题。

**Comment by ByLiangCheng** [comment]
设置 -> 翻译源设置 -> 文字识别 -> 开启TTime在线OCR 或 第三方OCR服务

有按照流程在设置里切换文本识别服务吗？

**Comment by asdsfdsfsdfs** [comment]
刚刚没注意看，还以为又不行，文字识别解决了，谢谢大佬。

**Comment by ByLiangCheng** [comment]
OK
