### ISSUE TITLE
[BUG] vscode 中选中英文单词无法获取选中数据，提示“识别内容为空”

### ISSUE THREAD

**Issue by daidaihk** [InkTimeRecord/TTime#102]
请提供下述完整信息以便快速定位问题 / Please provide the following information to quickly locate the problem

- 系统环境 / System Environment：win10

- TTime版本号 / TTime Version：0.4.0

- 问题描述 / Description of the issue：vscode 中选中英文单词无法获取选中数据，提示“识别内容为空”

**Comment by ByLiangCheng** [comment]
你好，VSCode能否检查下是否有插件冲突了

之前也有其他用户有这种类似情况，后面排查原因是受到了vim插件影响

**Comment by daidaihk** [comment]
> 你好，VSCode能否检查下是否有插件冲突了
> 
> 之前也有其他用户有这种类似情况，后面排查原因是受到了vim插件影响

vscode: v1.78.2
window: v10 22H2
vscode 禁用所有插件后测试，问题依旧存在。

**Comment by daidaihk** [comment]
> 只有VSCode无法操作吗？其他文本编辑器或工具、浏览器等是否正常划词

浏览器，记事本，其他代码编辑器均测试无问题，目前就只是vscode有问题

**Comment by ByLiangCheng** [comment]
> > 只有 VSCode 无法操作吗？其他文档或工具、浏览器等是否正常规划
> 
> 浏览器，记录本，其他代码编辑器平均测试无问题，目前只是vscode有问题

抱歉，我这边自己安装了1.78.2的版本后没有复现出你这种情况，目前需要你自行先排查一下电脑是否有其他应用冲突了
或者你可以把联系方式通过邮箱发送给我，我远程调试一下看看

**Comment by daidaihk** [comment]
无论是公司电脑还是私人电脑至今任存在vscode中选词无法翻译，换了一个开源项目 pot-desktop 在vscode中能正常翻译
