### ISSUE TITLE
[Feature] 手动拖动调整翻译源的上下位置

### ISSUE THREAD

**Issue by snoopytl** [InkTimeRecord/TTime#103]
首先肯定一下，这是个好用的软件，我是无意看别人的issue中发现了这个宝藏软件，希望以后越做越好

接下来说一下我的建议：

1. 在手动设置翻译源的地方，能否通过拖动方式来排序翻译源的位置

**Comment by ByLiangCheng** [comment]
感谢，目前这个功能有计划增加，只是现在需求堆积的有些多，正在一点点开发中

**Comment by ByLiangCheng** [comment]
新版本已发布，功能已增加
