### ISSUE TITLE
[BUG] 下载下来安装不了

### ISSUE THREAD

**Issue by hahaha28** [InkTimeRecord/TTime#104]
请提供下述完整信息以便快速定位问题 / Please provide the following information to quickly locate the problem

- 系统环境 / System Environment：
mac m1

- TTime版本号 / TTime Version：
0.5.0 最新release，下载下来安装不了

- 问题描述 / Description of the issue：
- 
<img width="260" alt="image" src="https://github.com/InkTimeRecord/TTime/assets/46659807/518ee08b-e6c8-4e5a-ba70-7a951e183e3d">

**Comment by ByLiangCheng** [comment]
#48 此问题可以参考下这个Issues哈
