### ISSUE TITLE
[Feature] 输入翻译处添加搜索功能

### ISSUE THREAD

**Issue by snoopytl** [InkTimeRecord/TTime#105]
在输入翻译的地方，通过搜索的方式来快速指定原语言和翻译语言
1.通过中文方式：例如在原语言处搜索汉字“英语”，翻译语言处搜索“日语”实现英语到日语的翻译
2.通过拼音的方式：还是上述例子，搜索处搜索“yy”（英语的首字母），翻译处搜索“ry”实现英语到日语的翻译
3.通过语言代码：还是上述例子，搜索处搜索“en”，翻译处搜索“jp”实现英语到日语的翻译，语言代码可参考http://mowblog.com/%E5%90%84%E5%9B%BD%E5%AE%B6%E8%AF%AD%E8%A8%80%E4%BB%A3%E7%A0%81%E5%AF%B9%E7%85%A7%E8%A1%A8/

![image](https://github.com/InkTimeRecord/TTime/assets/29892766/456a3ea4-60a0-40ee-b9c8-060eb295de5c)

**Comment by ByLiangCheng** [comment]
你好，根据名称搜索方式有计划加入

拼音和语言代码暂未考虑，拼音感觉实用性不大
语言代码现在各翻译平台好像也没有完全一致，没法确定以哪个为准，反而还增加工作量

**Comment by ByLiangCheng** [comment]
功能已增加
