### ISSUE TITLE
[Feature] 能否改成免安装？公司电脑不能自己安装软件，但是可以打开免安装的

### ISSUE THREAD

**Issue by xiahounan** [InkTimeRecord/TTime#106]
**功能描述 / Function Description**
![image](https://github.com/InkTimeRecord/TTime/assets/101793084/0c2da16e-89cc-4ddd-99a9-4d37cf2179b0)
公司电脑不能自己安装软件，但是可以打开免安装的，例如snipaste，就可以直接打开

**Comment by ByLiangCheng** [comment]
你好，是支持的，releases中有exe便携版，你可以看看
