### ISSUE TITLE
翻译窗口打字时偏移

### ISSUE THREAD

**Issue by Ghomist** [InkTimeRecord/TTime#11]
翻译窗口在每输入一个字符（或者输入法确认输入）的时候向左上方偏移一点点，点击按钮、Alt+Q召出窗口也存在这个偏移
![230315-18-45-44](https://user-images.githubusercontent.com/87055025/225288599-3f31eeb2-a755-4ba7-ab88-4853d802bc05.gif)

**Comment by ByLiangCheng** [comment]
可以提供一下，系统版本，显示器缩放比例等信息吗？我这边试试看能不能复现出来

**Comment by Ghomist** [comment]
我这边自测了一下缩放比例：
自定义缩放大小124%时出现这个问题；120%时窗口会向正上方偏移；
调回125%就正常了，其它缩放比例兼容性暂时未知

**Comment by ByLiangCheng** [comment]
收到，我这边测试一下，看能否复现这个问题

**Comment by ByLiangCheng** [comment]
新版本已发布，问题已修复，请尝试在：设置 -> 偏好设置 -> 关闭翻译窗口动态高度 后再试试看
