### ISSUE TITLE
[BUG] 0.05软件内升级到0.0.6调用安装时报错

### ISSUE THREAD

**Issue by rogercc116** [InkTimeRecord/TTime#110]
![image](https://github.com/InkTimeRecord/TTime/assets/63380214/bdf3c3fb-5bc0-4afa-b6ca-558866d91dc0)
![image](https://github.com/InkTimeRecord/TTime/assets/63380214/d226bbe7-3ed2-4b25-9ea0-85cda3b8865f)
[2023-06-30.log](https://github.com/InkTimeRecord/TTime/files/11924173/2023-06-30.log)

**Comment by ByLiangCheng** [comment]
#109 和这个问题一致，正在修复中

**Comment by ByLiangCheng** [comment]
已修复，新版本中生效
