### ISSUE TITLE
翻译出来结果能不能按照输入的换行

### ISSUE THREAD

**Issue by JiangPee** [InkTimeRecord/TTime#111]
换行？
![Snipaste_2023-07-01_13-52-07](https://github.com/InkTimeRecord/TTime/assets/50794510/28c63323-9965-435f-a9ba-369edd80e6ac)

**Comment by ByLiangCheng** [comment]
你好，我这边测试这个问题是正常的，你看看是不是设置中有开启：

“文本处理” 将翻译结果的【换行符】替换为【空格】)

当我开启此功能时会这样

**Comment by JiangPee** [comment]
![Snipaste_2023-07-01_15-07-00](https://github.com/InkTimeRecord/TTime/assets/50794510/1036ddc7-c0e4-4c55-9219-1dfbb83a0880)
我觉得你们这个提示语说反了：“将OCR结果的【换行符】替换为【空格】”，默认没开启的情况下是自动把换行替换成空格，开启之后才是把换行符不替换，我在发布这个issue的时候看过一遍这个提示，我

**Comment by ByLiangCheng** [comment]
OK
