### ISSUE TITLE
[Feature] Mac 下多桌面场景，存在桌面切换问题

### ISSUE THREAD

**Issue by 874435441** [InkTimeRecord/TTime#113]
首次在桌面1打开了翻译窗口，当下次在桌面2打开翻译窗口时，会导致自动跳转到桌面1.

mainWin.setAlwaysOnTop(true,'floating') 应能解决这个问题

**Comment by ByLiangCheng** [comment]
你好感谢，有空我会测试一下这个问题和解决方案

**Comment by 874435441** [comment]
很抱歉，上面这个解决方案是错误的，是我测试不到位。问题还在

**Comment by bovindev** [comment]
我也遇到了这个问题

**Comment by tjx666** [comment]
这个问题很影响使用体验呀！ @ByLiangCheng 
每次翻译全屏的浏览器网页内容给我跳到别的桌面。

**Comment by ByLiangCheng** [comment]
新版本已发布，功能已支持

可以在设置 -> 偏好设置 -> 开启 静默显示窗口
