### ISSUE TITLE
[BUG]双击选词后点击翻译按钮提示：识别内容为空

### ISSUE THREAD

**Issue by soul521** [InkTimeRecord/TTime#116]
请提供下述完整信息以便快速定位问题 / Please provide the following information to quickly locate the problem

- 系统环境 / System Environment：win10

- TTime版本号 / TTime Version：0.6.0

- 问题描述 / Description of the issue：双击选词后点击翻译按钮提示：识别内容为空，选词在Google class中，edge浏览器

**Comment by ByLiangCheng** [comment]
你好，指的是Edge浏览器环境下Google class中的页面悬浮球不行吗？手动按下划词快捷键是否正常？其他应用或页面是正常的吗？
