### ISSUE TITLE
[Feature] 新增覆盖翻译功能

### ISSUE THREAD

**Issue by tdccj** [InkTimeRecord/TTime#117]
**功能描述 / Function Description**
用于编程、翻译、对话、编辑文本等工作
选中要翻译的部分，按下快捷键，翻译直接覆盖原文，可选（弹出可忽略复选框）

**Comment by ByLiangCheng** [comment]
你好，这个是有计划开发

**Comment by ByLiangCheng** [comment]
已更新，版本已经发布
