### ISSUE TITLE
[Feature] 主界面不自动最小化到托盘，以及类似Qtranslate的直接抓取网页翻译服务？

### ISSUE THREAD

**Issue by future93** [InkTimeRecord/TTime#118]
如标题，从Qtranslate跳过来之后，有两个不习惯的地方：

一个是只要窗口焦点离开主界面，主界面便直接自动隐藏了，这个对于我这种习惯把翻译窗口丢在副屏上随时调用的人确实不太习惯；（另外OCR必须使用全局快捷键调用也是，不知能否在托盘菜单或者主界面上增加一个入口？）

另外就是因为没有外行的卡，deepL直接不能用了，这时候才念起Qtranslate那种直接生成对应网页服务url然后抓取输出内容的模式的好。不知道有没有引入类似功能的计划？

**Comment by ByLiangCheng** [comment]
你好，我回答一下这几个问题
1.失焦问题可以使用置顶功能解决
2.托盘菜单功能下个版本加入
3.DeepL有内置的，你可以在设置中自行添加或开启

**Comment by future93** [comment]
> 你好，我回答一下这几个问题 1.失焦问题可以使用置顶功能解决 2.托盘菜单功能下个版本加入 3.DeepL有内置的，你可以在设置中自行添加或开启

你好，感谢回复。

关于失焦问题，还想再问一下，有没有计划将来加入正常最小化到任务栏、或者不窗口置顶（也就是可以被其他窗口覆盖）的情况下、失去焦点后仍能从任务栏调回的功能？

期待托盘入口的上线。

关于内置的DEEPL等引擎，大意了，因为以前试用的时候没有，就没仔细检查，非常抱歉。想请教一下，这些内置的DEEPL、Google、必应词典等引擎，是走开发者自己部署的API的吧？这样恐怕得收敛着点用了，免得造成太大的负担。

总之，再次感谢回复！

**Comment by ByLiangCheng** [comment]
你好，这块有考虑过通过配置开关，但是并没完全确定是否会增加

内置的接口目前只有TTime翻译源是走的我自己部署的API

**Comment by future93** [comment]
> 你好，这块有考虑过通过配置开关，但是并没完全确定是否会增加
> 
> 内置的接口目前只有TTime翻译源是走的我自己部署的API

感谢回复。

其他的内置接口是直接走服务商的网页端之类的话就好，用起来就没什么心理负担了。

祝开发顺利！

**Comment by ByLiangCheng** [comment]
感谢支持 ~
