### ISSUE TITLE
能否支持以下google翻译吗

### ISSUE THREAD

**Issue by hiknn** [InkTimeRecord/TTime#12]
在国外适用国内的翻译引擎不是很好用，希望增加一下谷歌

**Comment by ByLiangCheng** [comment]
收到，下个版本会加入

**Comment by rogercc116** [comment]
如果加入谷歌能否加入代理的设置

**Comment by ByLiangCheng** [comment]
> 如果加入谷歌可以否加入代理的设置

加入代理设置是担心谷歌被墙的问题吗？

**Comment by rogercc116** [comment]
> > 如果加入谷歌可以否加入代理的设置
> 
> 加入代理设置是担心谷歌被墙的问题吗？

是的，目前来看谷歌翻译已经被墙了必须要走代理

**Comment by ByLiangCheng** [comment]
> > > 如果加入谷歌可以否加入代理的设置
> > 
> > 
> > 加入代理设置是担心谷歌被墙的问题吗？
> 
> 是的，目前来看谷歌翻译已经被墙了必须要走代理

收到，会跟随代理配置一起集成

**Comment by ByLiangCheng** [comment]
新版已发布，下载最新版即可
