### ISSUE TITLE
[Feature] 是否能添加一个汉语词典的功能

### ISSUE THREAD

**Issue by snoopytl** [InkTimeRecord/TTime#124]
**功能描述 / Function Description**
有时候看文章的时候，虽然是中文但对它的拼音拿不准，这个时候就需要进行翻译，比如“觊觎”这个词，我想知道它的汉语拼音是什么、意思是什么
--------更深层次的功能---------------
1. 不仅能反查拼音，还能反查成语，甚至粤语发音
2. 如果有chatgpt的用户，可以自动实现上述1的功能，比如还是“觊觎”这个词，通过固化的chatgpt指令，直接输出以下内容
  1. 拼音：jì yù
  2. 释义：xxxxxxx
  3. 粤语发音：xxxx
 --------------实现方式-------------
1. 可在设置中单独添加一个开关，开启“拼音释义”（暂且这么叫吧）功能
2. 或允许用户开启第二翻译词典，这个词典可以翻译成日文、韩文等其他语言，当然也包含“拼音释义”

**Comment by ByLiangCheng** [comment]
你好，指的是想chatgpt新增一个中文释义的功能吗？

**Comment by snoopytl** [comment]
准确的说不是chatgpt有中文释义的功能，而是添加一个功能项叫中文释义，这个功能可以调用chatgpt的结果，具体如下：
设置界面：
![Uploading Snipaste_2023-07-16_10-45-56.png…]()
使用界面：
![Snipaste_2023-07-16_10-47-43](https://github.com/InkTimeRecord/TTime/assets/29892766/f253a965-053d-439a-9620-ab4faa4b164a)

**Comment by ByLiangCheng** [comment]
收到，会考虑做解决释义的方式，但不会这样实现

**Comment by snoopytl** [comment]
ok，我只是抛砖引玉，这样形象一点展示会更容易理解，主要是有相关的功能

**Comment by ByLiangCheng** [comment]
功能已更新，版本已发布
