### ISSUE TITLE
[Feature] 增加开关，处理划词翻译的换行符

### ISSUE THREAD

**Issue by 18183883296** [InkTimeRecord/TTime#125]
**功能描述 / Function Description**
当前的版本为OCR识别提供了优秀的支持，然而相比于划词翻译，识别准确率显然低得多，希望在新版本中增加开关，处理划词翻译的换行符。
当开关打开，划词翻译模式下处理选定文本段落的换行符，若行末为`-`，去除换行符，否则将换行符替换为空格，相信这将在段落翻译中极其实用。

**Comment by ByLiangCheng** [comment]
你好

1.“若行末为-”不理解是什么意思？

2.默认将换行符替换为空格，在高级设置中可以开启“将翻译结果的【换行符】替换为【空格】”，这个已经是满足了需求吧？

**Comment by 18183883296** [comment]
> 你好
> 
> 1.“若行末为-”不理解是什么意思？
> 
> 2.默认将换行符替换为空格，在高级设置中可以开启“将翻译结果的【换行符】替换为【空格】”，这个已经是满足了需求吧？

1. 行末为连字符，这在大片英文段落中经常出现。
2. 是的，我已经在高级设置中开启了文本处理开关，可是当前版本该选项似乎仅对输入的文本生效。
我对同一段文本进行翻译，图一使用快捷键划词翻译，图二复制后粘贴到翻译栏，我惊讶地发现尽管它们的文本内容一致，但是翻译结果不同，如图所示。
![图一](https://github.com/InkTimeRecord/TTime/assets/89304297/ed798808-b289-4b61-8fd3-bcf7ec7bb187)
![图二](https://github.com/InkTimeRecord/TTime/assets/89304297/e7cd0549-e08a-4e89-ae4a-815bd7405afd)

**Comment by ByLiangCheng** [comment]
抱歉，由于之前有事 一直没有回复

1.行末为-替换问题，这个我不确定是否为大众需求
2.划词和复制后粘贴翻译确实存在此问题，下个版本将会修复

**Comment by ByLiangCheng** [comment]
最新版本已发布，功能已新增
