### ISSUE TITLE
[Feature] 这个场景下是否需要优化下体验?

### ISSUE THREAD

**Issue by soidaken** [InkTimeRecord/TTime#126]
**功能描述 / Function Description**
操作流程: 任何时候快捷键调出主界面,输入内容,回车翻译. 这时候我想使用alt+tab,发现没有ttime软件的窗口.这让我有点困惑. 并且再次唤起界面,我之前的输入内容和翻译结果都被清空了.  是否要优化一下.

**Comment by ByLiangCheng** [comment]
你好，alt+tab不显示是这样设计的，因为本身应用理念就是即时翻译，快捷键触发

结果清空的问题目前有准备增加配置

**Comment by ByLiangCheng** [comment]
最新版本已发布，功能已新增
