### ISSUE TITLE
[Feature] OCR语言支持问题

### ISSUE THREAD

**Issue by tdccj** [InkTimeRecord/TTime#127]
**功能描述 / Function Description**
增强翻译ocr对俄语的支持
目前翻译ocr对西里尔字母的识别很糟糕，经常会识别成英文俄文混杂，导致无法翻译

**Comment by ByLiangCheng** [comment]
你好，目前离线的OCR只支持中英文，后续有计划会增加其他语言

但是目前的话其他语言建议可以配置下第三方OCR服务即可

**Comment by person2217** [comment]
希望可以添加识别文字选择功能，可以有效提升识别多语种时识别精度，谢谢。 @ByLiangCheng

**Comment by ByLiangCheng** [comment]
新版本已发布，功能已新增
