### ISSUE TITLE
[Feature] 感谢作者!是否可以降低内存占用?

### ISSUE THREAD

**Issue by 573523145** [InkTimeRecord/TTime#130]
首先感谢作者在windows平台也能做出这么优秀的翻译集合软件
如果时间充裕,能否优化一下后台下的内存占用和CPU占用?
尤其是后台内存占用!
再次感谢!

**Comment by ByLiangCheng** [comment]
你好 关于这个类似的问题在之前的Issues中已经回答过了，可以看看： #41 同理
