### ISSUE TITLE
[Feature] 自动读取剪贴板内容并翻译

### ISSUE THREAD

**Issue by Rao-Jupiter** [InkTimeRecord/TTime#131]
希望添加自动读取剪贴板内容并翻译的功能，比如说，我直接复制pdf上的内容，自动就进行翻译

**Comment by ByLiangCheng** [comment]
你好，这个有考虑，后续版本中会增加

**Comment by FunnyRoc** [comment]
自动读取剪贴板内容并翻译这个功能真的是刚需，另外一个特别重要的功能是读取剪贴板时希望还有个‘去除换行符’的功能开关，开发者辛苦了！

**Comment by FunnyRoc** [comment]
> 你好，这个有考虑，后续版本中会增加

自动读取剪贴板内容并翻译这个功能真的是刚需，另外一个特别重要的功能是读取剪贴板时希望还有个‘去除换行符’的功能开关，开发者辛苦了！

**Comment by ByLiangCheng** [comment]
> > 你好，这个有考虑，后续版本中会增加
> 
> 自动读取剪贴板内容并翻译这个功能真的是刚需，另外一个特别重要的功能是读取剪贴板时希望还有个‘去除换行符’的功能开关，开发者辛苦了！

取出换行符这个，在高级设置中开启：“将翻译结果的【换行符】替换为【空格】”，这个应该就可以满足了吧？

**Comment by ByLiangCheng** [comment]
最新版本已发布，功能已新增
