### ISSUE TITLE
[BUG] windows下默认TTime翻译会报错

### ISSUE THREAD

**Issue by oasisFly** [InkTimeRecord/TTime#136]
请提供下述完整信息以便快速定位问题 / Please provide the following information to quickly locate the problem

- 系统环境 / System Environment：
windows 10

- TTime版本号 / TTime Version：
v0.70

- 问题描述 / Description of the issue：
- 使用默认TTime翻译时会有报错
- {"message":"unable to get local issuer certificate","name":"Error","stack":"Error: unable to get local issuer certificate\n    at AxiosError.from (C:\\Program Files\\TTime\\resources\\app.asar\\node_modules\\axios\\dist\\node\\axios.cjs:825:14)\n    at RedirectableRequest.handleRequestError (C:\\Program Files\\TTime\\resources\\app.asar\\node_modules\\axios\\dist\\node\\axios.cjs:2961:25)\n    at RedirectableRequest.emit (node:events:539:35)\n    at eventHandlers.<computed> (C:\\Program Files\\TTime\\resources\\app.asar\\node_modules\\follow-redirects\\index.js:14:24)\n    at ClientRequest.emit (node:events:527:28)\n    at TLSSocket.socketErrorListener (node:_http_client:454:9)\n    at TLSSocket.emit (node:events:527:28)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)","config":{"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false},"adapter":["xhr","http"],"transformRequest":[null],"transformResponse":[null],"timeout":15000,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"env":{"Blob":null},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json","User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) time-translate/0.7.0 Chrome/104.0.5112.124 Electron/20.3.8 Safari/537.36","Content-Length":"102","Accept-Encoding":"gzip, compress, deflate, br"},"baseURL":"https://timerecord.cn/apis/","url":"translate/translate/","method":"post","data":"{\"channel\":0,\"translateContent\":\"医护\",\"languageType\":\"zh\",\"languageResultType\":\"en\",\"type\":\"TTime\"}","httpsAgent":{"_events":{},"_eventsCount":0,"timeout":null,"maxFreeSockets":1,"maxSockets":1,"maxTotalSockets":null,"sockets":{},"freeSockets":{},"requests":{},"options":{},"secureProxy":false,"proxy":{"host":"127.0.0.1","port":58424}}},"code":"UNABLE_TO_GET_ISSUER_CERT_LOCALLY","status":null}

**Comment by ByLiangCheng** [comment]
你好，是有设置什么吗？或者什么环境？我这边无法复现出来这种场景

**Comment by oasisFly** [comment]
也没有其它配置，下载完成后默认安装的，翻译的时候就内置的默认翻译都会提示"message":"unable to get local issuer certificate","name":"Error",

**Comment by ByLiangCheng** [comment]
> > 你好，是有设置什么吗？或者什么环境？我这边无法复现出来这种场景
> 
> 也没有其它配置，下载完成后默认安装的，翻译的时候就内置的默认翻译都会提示"message":"unable to get local issuer certificate","name":"Error",

你浏览器打开百度翻译、腾讯翻译之类的正常吗？

如果所有的翻译源都这样的话可能不是应用的BUG，而是网络请求失败了

根据提示目前看起来像是电脑系统时间和正常时间不一致这种类似的原因造成的

**Comment by oasisFly** [comment]
> > > 你好，是有设置什么吗？或者什么环境？我这边无法复现出来这种场景
> > 
> > 
> > 也没有其它配置，下载完成后默认安装的，翻译的时候就内置的默认翻译都会提示"message":"unable to get local issuer certificate","name":"Error",
> 
> 你浏览器打开百度翻译、腾讯翻译之类的正常吗？
> 
> 如果所有的翻译源都这样的话可能不是应用的BUG，而是网络请求失败了
> 
> 根据提示目前看起来像是电脑系统时间和正常时间不一致这种类似的原因造成的

网页打开这些翻译源都是正常的
![image](https://github.com/InkTimeRecord/TTime/assets/95963062/6be72499-d84b-4387-a60a-2ae4c7e55315)

**Comment by oasisFly** [comment]
校准了一下时间，好像也不是有误差这个问题
![image](https://github.com/InkTimeRecord/TTime/assets/95963062/b67a5c66-226d-41d1-bea7-10cc16eaac5d)

**Comment by ByLiangCheng** [comment]
抱歉，我这边本地尝试了一下，暂时还是无法复现，你这边可否邮箱给我一个联系方式，我远程给你看一下？

**Comment by oasisFly** [comment]
> 抱歉，我这边本地尝试了一下，暂时还是无法复现，你这边可否邮箱给我一个联系方式，我远程给你看一下？

我再研究研究，看看是不是电脑某些配置有问题

**Comment by ByLiangCheng** [comment]
此问题长时间未答复，自动关闭
