### ISSUE TITLE
[BUG] 翻译英文混杂中文问题

### ISSUE THREAD

**Issue by YU-7** [InkTimeRecord/TTime#137]
请提供下述完整信息以便快速定位问题 / Please provide the following information to quickly locate the problem

- 系统环境 / System Environment：
![image](https://github.com/InkTimeRecord/TTime/assets/58320198/93b8cdd6-c209-4cbc-9a89-626481d7236d)
- TTime版本号 / TTime Version：
![image](https://github.com/InkTimeRecord/TTime/assets/58320198/d46781c1-b9f2-4bd4-9755-35d970260d69)
- 问题描述 / Description of the issue：
英文中夹杂部分中文，翻译就出现问题了。
![image](https://github.com/InkTimeRecord/TTime/assets/58320198/1269926f-5dbc-4dec-a9c9-33063c160415)

**Comment by ByLiangCheng** [comment]
你好，目前默认校验如果是出现了超过两个汉字时会默认识别为汉译英
