### ISSUE TITLE
可否生成可编辑的配置文件在软件根目录下?

### ISSUE THREAD

**Issue by 573523145** [InkTimeRecord/TTime#138]
希望下个版本把设置的内容保存在可编辑的config.ini文件里,并且把设置文件和缓存文件都改为保存在软件根目录下,方便便携,和直接修改,比如目前很多组合的快捷键无法设置,就比如ctrl+space,TAB+其它键,我从代码中直接改默认,这些组合都是可以用的
![图片](https://github.com/InkTimeRecord/TTime/assets/60864668/6ca24cc2-2ec0-47d6-a81e-5b11ba4887aa)

**Comment by ByLiangCheng** [comment]
新版本发布，功能已新增
