### ISSUE TITLE
[BUG] 为什么我一截图就所有窗口都消失了，只出现一个空白的桌面？

### ISSUE THREAD

**Issue by GitHubHWX** [InkTimeRecord/TTime#139]
请提供下述完整信息以便快速定位问题 / Please provide the following information to quickly locate the problem

- 系统环境 / System Environment：
硬件：intel 15.4寸 macbook pro 系统：macos 13.5

- TTime版本号 / TTime Version：
0.7.0

- 问题描述 / Description of the issue：
一截图就所有窗口都消失了，只出现一个空白的桌面

**Comment by ByLiangCheng** [comment]
你看看是不是没给TTime权限

**Comment by CrystalWyz** [comment]
去系统设置一下录屏权限
