### ISSUE TITLE
在 JetBrains 产品里划词无法获取到数据

### ISSUE THREAD

**Issue by burt1025lzz** [InkTimeRecord/TTime#14]
在 JetBrains 系列产品里划词无法获取到数据, 只能先复制再使用划词才可以获取到数据

**Comment by ByLiangCheng** [comment]
目前划词是存在一些问题，正在寻找解决方案，后续版本会想办法解决

**Comment by ByLiangCheng** [comment]
此问题已修复，新版本已发布，如还有问题，请重新提交Issues
