### ISSUE TITLE
[Feature] 增加翻译记录功能

### ISSUE THREAD

**Issue by ByLiangCheng** [InkTimeRecord/TTime#140]
希望添加翻译记录，虽然固定了，但是有时在翻译过程中，查看其他内容不小心点选了翻译图标丢失打断内容且无法返回。希望作者可以考虑下

_Originally posted by @pzhren in https://github.com/InkTimeRecord/TTime/issues/66#issuecomment-1669185418_

**Comment by ByLiangCheng** [comment]
近期版本有准备添加了

**Comment by pzhren** [comment]
感���

 �

发件人: ***@***.*** ***@***.***> 代表 ByLiangCheng
发送时间: 2023年8月8日 17:55
收件人: InkTimeRecord/TTime ***@***.***>
抄送: Andy Lynd ***@***.***>; Mention ***@***.***>
主题: Re: [InkTimeRecord/TTime] >增加翻译记录功能 (Issue #140)

 �

近期版本有准备添加了

**Comment by ByLiangCheng** [comment]
最新版本已发布，功能已新增
