### ISSUE TITLE
[Feature] 希望能够自由调整翻译窗口的大小

### ISSUE THREAD

**Issue by xiuqiuzhl** [InkTimeRecord/TTime#142]
希望能够自由调整翻译窗口的大小
现在无法自由调整翻译窗口的大小，当选择翻译源较多的时候，无法直接全部显示出来，需要滚动阅读，不方便直观阅读对比

**Comment by ByLiangCheng** [comment]
你好，有计划，后续版本中会加入

**Comment by ByLiangCheng** [comment]
#95  已经存在相同问题，此issues关闭
