### ISSUE TITLE
[Feature] 希望增加输入的时候能全自动翻译不用按回车键

### ISSUE THREAD

**Issue by pokipoi** [InkTimeRecord/TTime#143]
**功能描述 / Function Description**
打完一个单词后还需要回车一下才能看结果，不知道这个功能实现起来难度怎么样。类似有道翻译这样
![image](https://github.com/InkTimeRecord/TTime/assets/22863236/4d203008-b2ab-4caa-9deb-a827385473cb)

**Comment by ByLiangCheng** [comment]
有计划，后续版本中会加入

**Comment by ByLiangCheng** [comment]
新版本发布，功能已更新
