### ISSUE TITLE
[Feature] 关于Linux平台运行

### ISSUE THREAD

**Issue by lizipeng0013** [InkTimeRecord/TTime#144]
请提供下述完整信息以便快速定位问题 / Please provide the following information to quickly locate the problem

- 系统环境 / System Environment：

- TTime版本号 / TTime Version：
0.7.0

- 问题描述 /
- 这软件官方支持Linux平台吗？

**Comment by ByLiangCheng** [comment]
linux版本暂未测试过，所以暂未打包发布，后续有时间会做兼容处理

当然如果可以的话，欢迎加入一起进行适配

**Comment by feiwuya** [comment]
修改一下图标路径，然后重新打包

- 具体修改如下：src/main/service/TrayEvent.ts

第 107 行修改为：

```typescript
      iconPath = path.join(__dirname, '../../public/icon-16x16.png')
```

**Comment by Greatsaltedfish** [comment]
请问一下ts或者js的项目应该如何构建呢？我对这块不熟，但是我很想在linux（kde）下使用

**Comment by lizipeng0013** [comment]
> 请问一下ts或者js的项目应该如何构建呢？我对这块不熟，但是我很想在linux（kde）下使用

不同项目有区别，我只能给你TTime的Linux构建参考，请看这个txt文件：
[Deepin构建TTime.txt](https://github.com/InkTimeRecord/TTime/files/14535052/Deepin.TTime.txt)

**Comment by lizipeng0013** [comment]
> 修改一下图标路径，然后重新打包
> 
> * 具体修改如下：src/main/service/TrayEvent.ts
> 
> 第 107 行修改为：
> 
> ```ts
>       iconPath = path.join(__dirname, '../../public/icon-16x16.png')
> ```

谢谢，已成功打包
