### ISSUE TITLE
[Feature] 希望增加面板位置是否随鼠标、上次位置，面板可以拖大拖小，设置里可以有一个选项是否结果折叠等

### ISSUE THREAD

**Issue by ldk-ldk** [InkTimeRecord/TTime#146]
**功能描述 / Function Description**
1. 希望增加面板位置是否随鼠标、上次位置。
2. 面板可以拖大拖小。
3. 设置里可以有一个选项是否结果折叠。
4. 字体可以自己设置、字号也可以设置功能。
5. 面板结果的每一个翻译引擎，上面是否有原文，可选项，因为引擎多了后，想看看原文。就是原文对照。

**Comment by ByLiangCheng** [comment]
你好
1.窗口位置功能已开发，下个版本发布
2、3、4.功能已记录，有计划开发
5.每一个翻译上面展示原文指的是？这个没太明白是什么意思

**Comment by ldk-ldk** [comment]
5 就是

**Comment by ByLiangCheng** [comment]
> 5 结果如下 输入框：汉语 Baidu 翻译： 汉语 显示在上 翻译后的英文 显示在下 谷歌 翻译： 汉语 显示在上 翻译后的英文 显示在下

这种方式暂不考虑，如果翻译内容过长时，会显得很臃肿

**Comment by ByLiangCheng** [comment]
已更新，版本已经发布
