### ISSUE TITLE
[Feature] 增加“替换选中文本/插入到光标位置”

### ISSUE THREAD

**Issue by mccree2** [InkTimeRecord/TTime#147]
**功能描述 / Function Description**

举个例子，在输入框输入了一段话，快捷键翻译了，正常情况点击复制后的文本，粘贴到输入框。但是这一步可以简化，不需要复制粘贴，点击按钮直接替换选中的原文或插入到光标位置。

**Comment by ByLiangCheng** [comment]
指的是，划词一段内容，当我按下快捷键，自动翻译并进行替换操作吗？

**Comment by bowencool** [comment]
<img width="195" alt="image" src="https://github.com/InkTimeRecord/TTime/assets/20217146/05a4480b-1aa3-4a2f-9277-a08df9f249fe">
在“复制”旁边加一个按钮就行了

**Comment by ByLiangCheng** [comment]
> <img alt="image" width="195" src="https://user-images.githubusercontent.com/20217146/261167773-05a4480b-1aa3-4a2f-9277-a08df9f249fe.png"> 在“复制”旁边加一个按钮就行了

抱歉，没有理解这个功能，可以描述一下吗？

**Comment by bowencool** [comment]
![Screen-Recording-2023-08-17-at-18 54 34](https://github.com/InkTimeRecord/TTime/assets/20217146/7071ca34-d41e-45a6-859c-c729d9a087f7)

**Comment by jkqxl** [comment]
作者你好，我也有类似的问题，能否对选中文本直接使用 快捷键 ，进行 翻译替换 ，在不满意后还可以撤回。主要是省却了，复制、粘贴这一步骤。

**Comment by leidichen** [comment]
开发者你好，我想很多人都有此需求。特别在输入ai提示词时，需要文本替换功能，类似「沉浸式翻译」三个空格翻译并替换当前文本框内的文字。感谢开发者辛勤付出🙏
- 未选中状态，使用快捷键将当前文本框的所有文字翻译并替换
- 选中状态下，翻译并替换选中文本
- 软件窗口处可以增加一个替换文本图标，点击图标可以将翻译内容粘贴到光标所在位置
![image](https://github.com/InkTimeRecord/TTime/assets/18671216/22b519a3-bde3-4616-b296-b9fe281095eb)

**Comment by ByLiangCheng** [comment]
目前此功能可以考虑一下替换翻译快捷键 ～
