### ISSUE TITLE
[Feature] 自动删去OCR结果的【换行符】

### ISSUE THREAD

**Issue by novemnovemsex** [InkTimeRecord/TTime#148]
**功能描述 / Function Description**
【换行符】换为空格有时不太实用，识别完成一段话之后还要逐个删去空格，建议在OCR设置中添加新选项：自动删去OCR结果的【换行符】。

**Comment by novemnovemsex** [comment]
扫描旧书籍，以进行数字化保存，并进行二次编排校对。

**Comment by ByLiangCheng** [comment]
好的，下个版本加入

**Comment by ByLiangCheng** [comment]
新版本发布，功能已更新
