### ISSUE TITLE
[BUG] 划词翻译快捷键会唤出微软团队，功能无法正常使用。

### ISSUE THREAD

**Issue by darknesscho** [InkTimeRecord/TTime#154]
请提供下述完整信息以便快速定位问题 / Please provide the following information to quickly locate the problem

- 系统环境 / System Environment：Windows11 专业工作站版 22621.2134 

- TTime版本号 / TTime Version：0.8.1

- 问题描述 / Description of the issue：
在Windows11下设置划词翻译的快捷键和唤出Microsoft Team来，无论设置成什么快捷键都会。导致划词翻译快捷键设置无效，使得功能无法通过快捷键来使用。即使卸载了Microsoft Team也无济于事，仍然会唤起安装它的界面。

**Comment by ByLiangCheng** [comment]
微软团队指的是？能否提供一下视频示例？因为划词本质上还是触发的ctrl+c

同时悬浮球翻译使用也会存在此情况吗？

**Comment by darknesscho** [comment]
是的，悬浮球翻译使用也会存在此情况。
视频在这里：
https://cowtransfer.com/s/e443d1ab5bcd48 点击链接查看 [ 屏幕录制 2023-08-21 210814.mp4 ] ，或访问奶牛快传 cowtransfer.com 输入传输口令 a5q2ko 查看；

**Comment by ByLiangCheng** [comment]
微软团队的这个正常来说是需要按下什么快捷键才会触发显示的，这个你有实际测试过吗？

**Comment by darknesscho** [comment]
我只要开启划词翻译快捷键，这个快捷键就会默认变成触发微软团队的快捷键。无论修改成哪一个，都会触发微软团队。不开启划词翻译就不会有什么快捷键触发微软团队，至少我没遇到。
控制全局快捷键的软件我只安装了PowerToy最新版，但里面并没关于微软团队的快捷键设置。

**Comment by ByLiangCheng** [comment]
可参考 #238
