### ISSUE TITLE
TTime在线OCR不能用了

### ISSUE THREAD

**Issue by lizipeng0013** [InkTimeRecord/TTime#155]
请提供下述完整信息以便快速定位问题 / Please provide the following information to quickly locate the problem

- 系统环境 / System Environment：

- TTime版本号 / TTime Version：

- 问题描述 / Description of the issue：
![截图_time-translate_20230821210106](https://github.com/InkTimeRecord/TTime/assets/123794418/8f5a214d-a394-46db-bee5-3ecc4760ff2a)
TTime在线OCR不能用了，显示“请求通道方接口失败，请稍后再试”

**Comment by ByLiangCheng** [comment]
你好，已经恢复了，前面宕机了，后续版本中会重构一下这块，提升稳定性
