### ISSUE TITLE
[Feature] 希望能够配置汉译英翻译结果的格式

### ISSUE THREAD

**Issue by Icebear-Qiu** [InkTimeRecord/TTime#158]
**功能描述 / Function Description**
希望可以增加一个翻译结果的处理 比如间隔符号配置 大小写配置

**Comment by ByLiangCheng** [comment]
你好，没理解指的是什么意思

**Comment by Icebear-Qiu** [comment]
我是一名程序员，在进行变量命名时经常会用到它 ，我希望能自定义翻译结果的格式例如驼峰命名或者下划线分隔单词。非常希望能够推出一个类似的配置功能



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月23日(周三) 下午3:39
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [InkTimeRecord/TTime] [Feature] 希望能够配置汉译英翻译结果的格式 (Issue #158)




 
你好，没理解指的是什么意思

**Comment by Icebear-Qiu** [comment]
我想使用Qt写一个类似的翻译软件，只是作为项目经历，想借鉴下TTime界面，可以吗



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年8月23日(星期三) 晚上8:18
收件人: ***@***.***&gt;; 
抄送: "Ice ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [InkTimeRecord/TTime] [Feature] 希望能够配置汉译英翻译结果的格式 (Issue #158)





 
了解了 我会先记录下来 看看后续这块应该怎么做

**Comment by ByLiangCheng** [comment]
功能已增加，版本已发布
