### ISSUE TITLE
[BUG] TTime安装包依赖提示

### ISSUE THREAD

**Issue by emako** [InkTimeRecord/TTime#159]
请提供下述完整信息以便快速定位问题 / Please provide the following information to quickly locate the problem

- 系统环境 / System Environment：
WIN11

- TTime版本号 / TTime Version：
TTime-0.8.2-setup.exe

- 问题描述 / Description of the issue：
看安装包的UI应该是NSIS做的，这个依赖提示，其实不应该缺的，每次都提示。
![image](https://github.com/InkTimeRecord/TTime/assets/24737061/df536ec1-5a8e-4723-a0ea-bfefaaaba4be)
其实提示去掉的话可以做自动更新。

**Comment by ByLiangCheng** [comment]
你好，目前部分机型是存在这个问题，后续会看看怎么优化

不过所指的自动更新是？

**Comment by emako** [comment]
就是自动拉NSIS安装包静默更新

**Comment by ByLiangCheng** [comment]
确实是一个思路，感谢提醒，我后面看看这快
