### ISSUE TITLE
[BUG] 0.8.3版本窗口大小调整bug

### ISSUE THREAD

**Issue by Cheng2379** [InkTimeRecord/TTime#164]
请提供下述完整信息以便快速定位问题 / Please provide the following information to quickly locate the problem

- 系统环境 / System Environment：
- windows10专业版 22H2

- TTime版本号 / TTime Version：
0.8.3

- 问题描述 / Description of the issue：
- 只能横向放大窗口，无法缩小窗口，无法自定义调整窗口大小

![image](https://github.com/InkTimeRecord/TTime/assets/90660643/b10a119b-47ac-491f-b0e6-32e9d589c845)

**Comment by ByLiangCheng** [comment]
你好，目前可以通过鼠标到窗口的右上角调整宽度，高度目前是无法调整的，那块是会自动计算

**Comment by Cheng2379** [comment]
> 你好，目前可以通过鼠标到窗口的右上角调整宽度，高度目前是无法调整的，那块是会自动计算的
能提供下联系方式吗，我可以录个视频发给你，有点不太好描述

**Comment by Cheng2379** [comment]
> 你好，目前可以通过鼠标到窗口的右上角调整宽度，高度目前是无法调整的，那块是会自动计算的

不只是高度没法调，就是鼠标放到下方可以调节大小变成双向箭头的时候，长按调整会自动左右拉长，而且快捷键呼出翻译窗口输入文字准备翻译的时候，有时窗口会轻微抖动

**Comment by ByLiangCheng** [comment]
> > 你好，目前可以通过鼠标到窗口的右上角调整宽度，高度目前是无法调整的，那块是会自动计算的
> 
> 不只是高度没法调，就是鼠标放到下方可以调节大小变成双向箭头的时候，长按调整会自动左右拉长，而且快捷键呼出翻译窗口输入文字准备翻译的时候，有时窗口会轻微抖动

byliangcheng@sina.com 这是我邮箱
