### ISSUE TITLE
[BUG] Unable to open app

### ISSUE THREAD

**Issue by majinding** [InkTimeRecord/TTime#168]
请提供下述完整信息以便快速定位问题 / Please provide the following information to quickly locate the problem

- 系统环境 / System Environment：
MasOS Big Sur 11.0.1 (20B29)

- TTime版本号 / TTime Version：
TTime-0.8.3-x64.dmg

- 问题描述 / Description of the issue：
<img width="260" alt="image" src="https://github.com/InkTimeRecord/TTime/assets/2681645/1461a89f-dde0-44ba-b262-840b5255ae3a">

**Comment by ByLiangCheng** [comment]
#48 这个问题可以参考下这个Issues哈
