### ISSUE TITLE
[Feature] 增加选项以翻译时不显示原文

### ISSUE THREAD

**Issue by scbzfarmingtest** [InkTimeRecord/TTime#169]
**功能描述 / Function Description**
翻译过长内容时，显示原文会导致窗口过大或仅第一个翻译源被显示。
![image](https://github.com/InkTimeRecord/TTime/assets/68948943/fb565747-f65e-4d7e-bcc1-021c1a952374)

如果有选项，选择能去除原文和切换语言的框，可以看到更多的翻译源结果或者将窗口缩小很多
![image](https://github.com/InkTimeRecord/TTime/assets/68948943/cecc0bf5-3268-4640-9e6c-52e5424e2e32)

Anyway，不胜感激！

**Comment by ByLiangCheng** [comment]
你好，翻译语言隐藏后续会考虑加入配置，看大家需求量情况

目前要是觉得占用空间过大，可以把翻译窗口宽度调整或点击翻译源右边的收缩按钮，可以快速的隐藏某个翻译源的结果

**Comment by ntlv1** [comment]
附议附议，就我自己而言，绝大多数情况下并不是很需要在翻译窗口中显示原文。
如果可以隐藏原文，真是解决了一大痛点。

**Comment by ByLiangCheng** [comment]
功能已增加，版本已发布
