### ISSUE TITLE
[Feature] Supports preset lang, including left and right

### ISSUE THREAD

**Issue by emako** [InkTimeRecord/TTime#170]
**功能描述 / Function Description**
![image](https://github.com/InkTimeRecord/TTime/assets/24737061/04300812-c5d2-490f-8f0f-719ec34a3750)
支持预设语言，包括左边和右边，加个一键切换成预设的下拉选择框，同时这个下拉选择框也可以多一个固定选项“添加当前为预设”。
高级的翻译机基本都支持这种预设。

**Comment by ByLiangCheng** [comment]
你好，指的翻译机有示例吗？我这边看一下

**Comment by person2217** [comment]
他的意思应该是“自动识别”功能可自定义。这样可以让学习多语种的人顺畅使用，而不用每次重复点选语言。
通常其他翻译软件是列一个优先翻译的选项。
例如：
外语优先翻译为：
英语     日语        俄语      法语....
汉语优先翻译为：
..................
@ByLiangCheng

**Comment by person2217** [comment]
补个易翻翻译的图
![截图_20230912005148](https://github.com/InkTimeRecord/TTime/assets/106829332/67056e2c-cad5-4ca6-9ce6-5868aa46ad3e)
![截图_20230912005238](https://github.com/InkTimeRecord/TTime/assets/106829332/79059956-10be-4466-ac81-c7a4e58aa39b)
![截图_20230912005259](https://github.com/InkTimeRecord/TTime/assets/106829332/6b8b1836-462b-487c-8712-cd51d2c041b7)

**Comment by ByLiangCheng** [comment]
> 补个易翻翻译的图 ![截图_20230912005148](https://user-images.githubusercontent.com/106829332/267091872-67056e2c-cad5-4ca6-9ce6-5868aa46ad3e.png) ![截图_20230912005238](https://user-images.githubusercontent.com/106829332/267091935-79059956-10be-4466-ac81-c7a4e58aa39b.png) ![截图_20230912005259](https://user-images.githubusercontent.com/106829332/267092013-6b8b1836-462b-487c-8712-cd51d2c041b7.png)

后续我看看这块，3q
