### ISSUE TITLE
[Feature] 增加原文文本处理显示 & 增加取词自定义

### ISSUE THREAD

**Issue by QiguaiR** [InkTimeRecord/TTime#171]
**功能描述 / Function Description**

**上下方文本内容对称**：勾选了“文本处理”后，在化词翻译时，只有翻译结果是纯文本形式的，但原文文本显示的还是没有处理过的文本，见下图：

![image](https://github.com/InkTimeRecord/TTime/assets/128595110/0921e262-6ef2-46d6-ac08-04c30da9ff0a)

希望能增加对原文文本的处理结果，让上方翻译窗口里的文本和下方翻译结果的内容对称。

**取词**：能否增加自定义或其他选择，比如对着单词按住“ctrl"可显示悬浮标或直接呈现翻译内容。

**Comment by ByLiangCheng** [comment]
你好，对原文处理会先记录下来，后续有空了会考虑做处理

取词对单词按住“ctrl"，指的是不需要鼠标选中单词，只是单纯的鼠标放在单词上，按下ctrl出现悬浮球直接翻译吗？

**Comment by QiguaiR** [comment]
> 取词对单词按住“ctrl"，指的是不需要鼠标选中单词，只是单纯的鼠标放在单词上，按下ctrl出现悬浮球直接翻译吗？
是的，这个功能在有道词典上有，我个人感觉很有用，缓解了一些手指频繁点击鼠标的疲劳。

此外，还有两个功能上的请求。增加翻译窗口和翻译结果的水平显示布局（就是翻译窗口在左边，翻译结果在右边；这在翻译长句子或段落时，视觉更好），以及整个翻译框架可以调整（比如鼠标拖动边框调整）。

辛苦啦~

**Comment by ByLiangCheng** [comment]
新版本已发布，原文处理功能已支持
