### ISSUE TITLE
[Feature] 希望翻译源新增“同花顺翻译”

### ISSUE THREAD

**Issue by Cland-SKY** [InkTimeRecord/TTime#176]
**功能描述 / Function Description**
1、功能建议：同花顺翻译API目前**全部免费**，而且支持**术语库**，希望添加支持~
2、使用疑问：对接的火山翻译等api是否默认支持翻译术语库功能？

**Comment by ByLiangCheng** [comment]
你好
1.此接口先记录下来了，后续有空看一下
2.翻译术语库功能因为看目前提出此问题的用户不多，并且有些翻译源好像并不支持此方式，就一直没加

**Comment by Cland-SKY** [comment]
非常感谢您的回复！软件很好用，感谢你的无私付出~
