### ISSUE TITLE
能不能添加手动取消窗口动态调整宽度

### ISSUE THREAD

**Issue by zy2357** [InkTimeRecord/TTime#178]
翻译大篇文本使得窗口宽度增大,以至于遮挡屏幕
希望可以添加手动取消窗口宽度动态调整选项或者添加固定窗口宽度数值

**Comment by ByLiangCheng** [comment]
抱歉，你的电脑是不是有调整分辨率或缩放比例？目前部分用户设置了之后会出现自动调整的情况，这是个BUG，将会在近期版本中修复

**Comment by ByLiangCheng** [comment]
功能已增加，版本已发布
