### ISSUE TITLE
TTime翻译无法使用

### ISSUE THREAD

**Issue by lisch7** [InkTimeRecord/TTime#179]
请提供下述完整信息以便快速定位问题 / Please provide the following information to quickly locate the problem

- 系统环境 / System Environment：
macOS M芯片

- TTime版本号 / TTime Version：
0.8.3

- 问题描述 / Description of the issue：
TTime翻译无法使用

<img width="419" alt="image" src="https://github.com/InkTimeRecord/TTime/assets/103273640/69228b90-2b83-48cb-a42e-5c84148c7570">

**Comment by ByLiangCheng** [comment]
已经恢复了
