### ISSUE TITLE
[Feature] 能不能添加“待翻译文本自动删除换行”的功能

### ISSUE THREAD

**Issue by celebrki** [InkTimeRecord/TTime#180]
弹窗速度很快这一点特别好，但是翻译文本的换行符不能去除。作者可能考虑这个功能但不好实现，所以变相提供了“将翻译结果的换行符替换”的功能？隔壁Pot有这个功能，但是TTime的窗口做得更好，各有优势，要是有自动去除翻译文本换行符，TTime会更有优势😙。

**Comment by celebrki** [comment]
但是复制弹窗里的原文是去除了换行了，就是窗口里显示的原文还带有换行

**Comment by ByLiangCheng** [comment]
抱歉，前面没注意看到issues，遗漏了

没太理解，指的是想要输入框和翻译结果的整段文本内容换行符全部去除吗？

**Comment by hjm7** [comment]
> 抱歉，前面没注意看到issues，遗漏了
> 
> 没太理解，指的是想要输入框和翻译结果的整段文本内容换行符全部去除吗？

输入框可以增加去除换行符的功能吗

**Comment by ByLiangCheng** [comment]
> > 抱歉，前面没注意看到issues，遗漏了
> > 没太理解，指的是想要输入框和翻译结果的整段文本内容换行符全部去除吗？
> 
> 输入框可以增加去除换行符的功能吗

这个有什么场景吗？目前设置中支持翻译结果的换行符替换为空格

**Comment by ByLiangCheng** [comment]
由于长时间未回复，issues关闭
