### ISSUE TITLE
[BUG] TTime 无法在重启电脑时被成功退出

### ISSUE THREAD

**Issue by yoghurtdewdew** [InkTimeRecord/TTime#181]
请提供下述完整信息以便快速定位问题 / Please provide the following information to quickly locate the problem

- 系统环境 / System Environment：
MacOS 13.5.2 (22G91) （M1）

- TTime版本号 / TTime Version：
0.7.0

- 问题描述 / Description of the issue：
发现重启电脑时，好像会因为 TTime 退出失败，导致 重启失败。目前每次重启电脑前，必须得手动退出 TTime (这个退出过程好像需要等一段时间才能看到退完) 才能成功重启电脑。

**Comment by yoghurtdewdew** [comment]
<img width="587" alt="iShot_2023-09-26_21 45 50" src="https://github.com/InkTimeRecord/TTime/assets/63794438/cec0f6a6-7ce9-4973-bc39-4ba8256a7bd5">
<img width="559" alt="iShot_2023-09-26_21 46 58" src="https://github.com/InkTimeRecord/TTime/assets/63794438/231d7e41-3456-442b-96c6-ebdd22b0867d">

**Comment by ByLiangCheng** [comment]
新版本已发布，问题已修复
