### ISSUE TITLE
[BUG] idea中触发截图时弹层消失问题

### ISSUE THREAD

**Issue by cloud-wyf** [InkTimeRecord/TTime#185]
请提供下述完整信息以便快速定位问题 / Please provide the following information to quickly locate the problem

- 系统环境 / System Environment：
win11 idea2022.3.3

- TTime版本号 / TTime Version：
0.8.3

- 问题描述 / Description of the issue：
在idea中，如有报错，当鼠标放在上面时会有弹窗提示，此时如果使用ttime进行截图ocr或翻译，弹窗会消失。也就是无法翻译弹窗内容。希望大佬可以优化一下

**Comment by ByLiangCheng** [comment]
你好，当前确实存在此问题，后续版本中会先办法解决，目前可以通过划词去进行解决

**Comment by ByLiangCheng** [comment]
问题已修复，新版本已发布
