### ISSUE TITLE
[BUG] M1安装报错

### ISSUE THREAD

**Issue by clcaod** [InkTimeRecord/TTime#186]
请提供下述完整信息以便快速定位问题 / Please provide the following information to quickly locate the problem

- 系统环境 / System Environment：
MacOS M1

- TTime版本号 / TTime Version：
0.8.3

- 问题描述 / Description of the issue：
![image](https://github.com/InkTimeRecord/TTime/assets/108561101/d5401d83-a140-4b31-b69d-f8092f9e5f4e)

有点尴尬，还没上手体验就卡在安装上了。

**Comment by ByLiangCheng** [comment]
#48 这个问题可以参考下这个Issues哈
