### ISSUE TITLE
使用截屏翻译之后无法使用输入翻译

### ISSUE THREAD

**Issue by yincheng0807** [InkTimeRecord/TTime#19]

**Comment by ByLiangCheng** [comment]
你好，无法使用输入翻译指的是，调用的截图翻译之后，使用快捷键Alt + Q无法触发输入翻译吗？如果是这种情况可以尝试在设置中修改输入翻译的快捷键，看是不是有其他应用的快捷键和TTime快捷键冲突了

如果不是上述情况，麻烦可以详细描述一下操作流程吗？

**Comment by yincheng0807** [comment]
感谢回复。我又尝试复现问题，应该是由于使用截图翻译时，截图中不包含文字，导致程序一直处于文字识别状态，使用alt+Q唤起输入查词时仍然提示文字识别中，且这个过程只能通过重新截带有正常文字的图或者使用划词翻译结束。

现场信息：
版本	Windows 10 家庭中文版
版本号	22H2
安装日期	‎2023/‎3/‎17
操作系统内部版本	19045.2728
体验	Windows Feature Experience Pack 120.2212.4190.0

**Comment by ByLiangCheng** [comment]
新版已发布，此问题已修复，下载最新版即可
