### ISSUE TITLE
[Feature] 谷歌翻译源问题

### ISSUE THREAD

**Issue by freeyangs** [InkTimeRecord/TTime#190]
**功能描述 / Function Description**
大佬，最新版本怎么没有谷歌翻译了呀

**Comment by ByLiangCheng** [comment]
你好，我看是有的，你是不是没有在设置中自己添加？

**Comment by freeyangs** [comment]
![_WLMUBMHR4%5YLY%LX{JT)V](https://github.com/InkTimeRecord/TTime/assets/129839154/9fa909f8-5cd1-43f2-9c2f-f176f103d167)
只有这四个呀，要手动添加吗

**Comment by ByLiangCheng** [comment]
对的 默认只添加了这四个 这个界面下面不是有个＋号可以自行添加

**Comment by freeyangs** [comment]
好的谢谢
