### ISSUE TITLE
[Feature]  英语单词翻译带音标

### ISSUE THREAD

**Issue by bmmpp** [InkTimeRecord/TTime#194]
**功能描述 / Function Description**
之前的版本 必应翻译源 翻译英语是带英标的， 更新新版本后现在这些翻译源 翻译单词都没有英标了， 这样非常不利于学习啊

**Comment by ByLiangCheng** [comment]
是翻译源的接口更新了，下个版本修复

**Comment by ByLiangCheng** [comment]
问题已修复，新版本已发布

**Comment by bmmpp** [comment]
> 问题已修复，新版本已发布
感谢大佬
