### ISSUE TITLE
[BUG] 更新后无法打开

### ISSUE THREAD

**Issue by qiangweihewu** [InkTimeRecord/TTime#195]
请提供下述完整信息以便快速定位问题 / Please provide the following information to quickly locate the problem

- 系统环境 / System Environment：
windows 11

- TTime版本号 / TTime Version：
打不开了，应该是最新版

- 问题描述 / Description of the issue：
![image](https://github.com/InkTimeRecord/TTime/assets/91766951/9b609cf5-a6c6-4f9a-9e35-96a90d978a6e)

**Comment by Violetkylin** [comment]
同样的问题

**Comment by 445081431** [comment]
MacOS M芯片版本也是同样的问题

**Comment by ByLiangCheng** [comment]
#197 已存在相同问题，具体关注这边哈
