### ISSUE TITLE
[BUG] 0.9.1更新报错问题

### ISSUE THREAD

**Issue by Sha-Gao** [InkTimeRecord/TTime#198]
请提供下述完整信息以便快速定位问题 / Please provide the following information to quickly locate the problem

- 系统环境 / System Environment：

- TTime版本号 / TTime Version：

- 问题描述 / Description of the issue：

**Comment by Sha-Gao** [comment]
系统环境 / System Environment：Win10 
TTime版本号：最新版本
问题描述：无法打开
![Snipaste_2023-10-19_08-04-19](https://github.com/InkTimeRecord/TTime/assets/58065956/c396d122-7dff-4a3a-9406-3d0e0c1f0eec)

删除缓存目录/重启/重新官网下载安装都无法正常使用

**Comment by wtjperi2003** [comment]
+1.期望修复

**Comment by 445081431** [comment]
MacOS M芯片版本也是同样的问题

**Comment by ByLiangCheng** [comment]
#197 已存在相同问题，具体关注这边哈
