### ISSUE TITLE
[Feature]  3个建议😃 

### ISSUE THREAD

**Issue by Ruizhi-Deng** [InkTimeRecord/TTime#199]
**功能描述 / Function Description**
1. 可以在必应词典翻译界面添加更详细的内容，例如英文definition，例句等等
2. PDF划词翻译时换行可以自动去掉
3. 可以单独开发一组快捷键，例如Alt+Ctrl+C，其功能是进行文本复制，但是自动将换行符替换为空格。这样极大方便了PDF复制带连续换行符要手动删除的问题

**Comment by Ruizhi-Deng** [comment]
2/3. 比如在adobe arcobat DC里， 这样选中复制
![image](https://github.com/InkTimeRecord/TTime/assets/137520965/f8a6ee2b-db73-4cd2-b729-76b61d448b6d)
的结果是
```
"the choice of the
word insignificant relays the association of being small, lacking in power and of lowly status in this
setting" (107). Such an emotional approach eloquently demonstrates the anxiety and isolation of
second language learners when exposed to foreign environments.
```
翻译器里的结果是
![image](https://github.com/InkTimeRecord/TTime/assets/137520965/486e0be0-2980-426b-aed6-c49c703b331b)
对于某些自定义翻译源，换行可能对翻译结果有影响（比如说我的ChatGPT）
同时如果要拷贝PDF里的内容到其他软件里，要手动删掉换行比较繁琐，就是希望能实现自动把换行替换为空格的功能

**Comment by ByLiangCheng** [comment]
换行符替换为空格功能设置中是有的，你可以看看哈
