### ISSUE TITLE
Windows 显示设置不是100%时，截图位置不正确

### ISSUE THREAD

**Issue by iamdzk** [InkTimeRecord/TTime#2]
如题。
![image](https://user-images.githubusercontent.com/58968475/222612575-f87261ba-9973-4fd6-ade7-a3ec6528c218.png)
截图会错位，你自己试一下应该就可以知道了

**Comment by ByLiangCheng** [comment]
这个问题会在下一个版本中修复

**Comment by ByLiangCheng** [comment]
新版本已发布，此问题已修复，下载最新版本即可
