### ISSUE TITLE
[Feature] GPT-4 Support

### ISSUE THREAD

**Issue by WhiteByeBye** [InkTimeRecord/TTime#200]
**功能描述 / Function Description**
现在的OpenAI翻译源只支持3.5系列的模型，但现在GPT4已经是主流了，希望作者闲时能更新一下对OpenAI翻译源模型的支持列表。
万分感谢！
![image](https://github.com/InkTimeRecord/TTime/assets/45162092/89b84935-8916-41a4-ba3a-fbb657c8e75b)

**Comment by ByLiangCheng** [comment]
你好，下个版本加入 ~

**Comment by ByLiangCheng** [comment]
功能已增加，版本已发布
