### ISSUE TITLE
[BUG] Bing词典依然没有音标.

### ISSUE THREAD

**Issue by xiaoshengshuohua** [InkTimeRecord/TTime#203]
请提供下述完整信息以便快速定位问题 / Please provide the following information to quickly locate the problem

- 系统环境 / System Environment：
Windows 10 x64

- TTime版本号 / TTime Version：
0.9.2 便携版

- 问题描述 / Description of the issue：
Bing词典依然没有音标.
![image](https://github.com/InkTimeRecord/TTime/assets/84071282/c8a47d49-3b6b-43f0-86b4-fcebac5bbed1)

**Comment by ByLiangCheng** [comment]
你好，你可以检查下网络或版本再尝试一下，目前看起来像是查词失败了，我这边看是正常的

**Comment by xiaoshengshuohua** [comment]
> 你好，你可以检查下网络或版本再尝试一下，目前看起来像是查词失败了，我这边看是正常的

![image](https://github.com/InkTimeRecord/TTime/assets/84071282/fe4ae331-7ac7-4cdd-b2f3-f64be3c2f98f)
从新在Releases下载的便携版, 网络环境为全局透明代理, 应该没有问题.
![image](https://github.com/InkTimeRecord/TTime/assets/84071282/85923835-e87d-4336-9ff0-c331fd4f8f99)

**Comment by ByLiangCheng** [comment]
我用便携版，并且切换了几台电脑测试都没有问题，目前没有看到有其他用户有反馈此类问题

初步怀疑和网络或代理有关系，你可以把日志发到我们的邮箱：support@timerecord.cn，协助我们进行排查问题

**Comment by xiaoshengshuohua** [comment]
> 我用便携版，并且切换了几台电脑测试都没有问题，目前没有看到有其他用户有反馈此类问题
> 
> 初步怀疑和网络或代理有关系，你可以把日志发到我们的邮箱：[support@timerecord.cn](mailto:support@timerecord.cn)，协助我们进行排查问题

[TTime logs.txt](https://github.com/InkTimeRecord/TTime/files/13163270/TTime.logs.txt)

好的, 你看看日志吧.

**Comment by ByLiangCheng** [comment]
抱歉，日志看起来没有输出问题，你看这边方便加下我vx（官网有写）吗？我需要进一步进行排查

**Comment by ByLiangCheng** [comment]
功能已修复，版本已发布
