### ISSUE TITLE
[BUG] 无法在一些软件中划词翻译问题

### ISSUE THREAD

**Issue by aaaz6** [InkTimeRecord/TTime#206]
请提供下述完整信息以便快速定位问题 / Please provide the following information to quickly locate the problem

- 系统环境 / System Environment：
win11

- TTime版本号 / TTime Version：
0.9.2

- 问题描述 / Description of the issue：
无法在一些软件中划词翻译，类如:Hello word跨境电商助手，我认为你的翻译比他的还要好，所以我更喜欢用你的翻译软件.如果你能开发此类软件那就更棒了！我愿意为你推广

**Comment by ByLiangCheng** [comment]
我看了一下，他这个工具可以理解为是属于一个内置很多常见的网站，然后他在这些网站中自带翻译吗？

**Comment by aaaz6** [comment]
是的，他在这些网站聊天中是自带翻译的，就是我发送时就会自动翻译成英文给客户.但是由于翻译的准确性，我不会使用他的翻译，因为发送出去的内容有可能是错误的.

划词请看截图
![image](https://github.com/InkTimeRecord/TTime/assets/146999733/69514fd2-7c7b-4c75-b1af-6d55d5f9ad6e)

![image](https://github.com/InkTimeRecord/TTime/assets/146999733/295ab9ee-177f-45bb-9664-7b8bd882ef95)

我无法在这个聊天框中划词翻译，这是什么原因造成的呢？

**Comment by aaaz6** [comment]
我有一个建议，因为我使用翻译器，都需要重复翻译两遍. 中文翻译成英文，再从英文翻译为中文.确保词语的准确性. 
作者有什么好的方式来做到这一步吗？
还有一个是，我想开通会员，但是由于我在国外，没有+86的手机号码，可以增加注册方式吗？

**Comment by ByLiangCheng** [comment]
划词的问题是只在这个聊天框中出现问题的吗？还是其他地方也是呢？划词的原理理论上就是触发的键盘的ctrl+c复制，你手动按下ctrl+c是可以正常复制的吗？

**Comment by ByLiangCheng** [comment]
> 我有一个建议，因为我使用翻译器，都需要重复翻译两遍. 中文翻译成英文，再从英文翻译为中文.确保词语的准确性. 作者有什么好的方式来做到这一步吗？ 还有一个是，我想开通会员，但是由于我在国外，没有+86的手机号码，可以增加注册方式吗？

关于需要重复再翻译回去确保词语的准确性问题，也有其他用户提到过，这种方式后续我这可以在翻译源功能区下增加一个回译的按钮，点击之后翻译结果内容自动替换到输入框，不过感觉这种帮助可能不会算是很大
还有一种方式是在翻译结果下再增加一个回译的结果，不过这种的工作量对于目前我来说存在一定的开发时间，考虑如果遇到的人不多，就先作为记录

关于注册问题，目前开放的官网上暂还未支持其他方式，后续可能会支持，如果你想要注册，可以加上我的联系方式 或 联系邮箱：support@timerecord.cn，会给你提供内部注册渠道
