### ISSUE TITLE
[BUG] 利用PowerToy调换windows ctrl和win键位后，划词翻译无法使用

### ISSUE THREAD

**Issue by nigel7huyc** [InkTimeRecord/TTime#207]
请提供下述完整信息以便快速定位问题 / Please provide the following information to quickly locate the problem

- 系统环境 / System Environment：
win11 22621.2428

- TTime版本号 / TTime Version：
0.9.2

- 问题描述 / Description of the issue：
利用PowerToy调换windows键位ctrl和win后，使用划词翻译时会启动teams app导致划词翻译无法使用；尝试更改TTime默认划词翻译快捷键 / 卸载teams app后（卸载后调用划词翻译时的截图如下），该问题仍存在。

![image](https://github.com/InkTimeRecord/TTime/assets/71838555/5cb9a9d0-5da9-477c-a8b7-c3a4020077bd)

**Comment by ByLiangCheng** [comment]
你好，使用悬浮球翻译会有这种情况吗？

**Comment by nigel7huyc** [comment]
> 使用悬浮球翻译会有这种情况吗？

刚试了下，与划词翻译的情况是一致的

![image](https://github.com/InkTimeRecord/TTime/assets/71838555/3155bdfa-7d4f-4279-969e-8a4e30aefc84)
![image](https://github.com/InkTimeRecord/TTime/assets/71838555/956cfc16-1542-4cf1-8bc2-fd802bc351ca)

**Comment by ByLiangCheng** [comment]
这种情况你知道是否可以通过快捷键手动调出teams应用程序吗？

**Comment by nigel7huyc** [comment]
> 这种情况你知道是否可以通过快捷键手动调出teams应用程序吗？

可以，当前team原有快捷键“win+C”依旧可用

**Comment by ByLiangCheng** [comment]
> > 这种情况你知道是否可以通过快捷键手动调出teams应用程序吗？
> 
> 可以，当前team原有快捷键“win+C”依旧可用

我这边预估排查到问题了，不过你看这边方便加下我vx（官网有写）帮忙测试一下吗？我需要进一步确定一下

**Comment by nigel7huyc** [comment]
> > > 这种情况你知道是否可以通过快捷键手动调出teams应用程序吗？
> > 
> > 
> > 可以，当前team原有快捷键“win+C”依旧可用
> 
> 我这边预估排查到问题了，不过你看这边方便加下我vx（官网有写）帮忙测试一下吗？我需要进一步确定一下

okk
