### ISSUE TITLE
[Feature] 自带的ocr功能对英文识别支持不好

### ISSUE THREAD

**Issue by cherub0507** [InkTimeRecord/TTime#208]
**功能描述 / Function Description**
![微信截图_20231028102648](https://github.com/InkTimeRecord/TTime/assets/58015207/7f35e5dd-1571-4ca7-8145-87a702176885)

识别英文的时候，断开位置总是特别奇怪，大概率在大写字母位置断开

如截图，TTime 被断成了 T Time，MacOS M 被断成了 Ma cOSM，MacOS Intel 被断成了 Mac O SIntel

**Comment by ByLiangCheng** [comment]
抱歉，目前自带的确实还存在这个问题，后续会想办法优化一下这块

**Comment by ByLiangCheng** [comment]
新版本已发布，问题已修复

**Comment by cherub0507** [comment]
最新的0.9.6需要登录才能使用识别功能，海外手机号注册不了

建议开放邮箱注册

**Comment by ByLiangCheng** [comment]
> 最新的0.9.6需要登录才能使用识别功能，海外手机号注册不了
> 
> 
> 
> 建议开放邮箱注册

正常和之前一样可以使用的，只是下载语言包按理说是需要登录的，近期会支持邮箱或海外手机号码注册方式

如果想提前体验，可发送我们support@timerecord.cn邮件，提供电子邮箱或海外手机号码，我们为你开通账户 ～
