### ISSUE TITLE
[BUG] 不能关机

### ISSUE THREAD

**Issue by heyeruoqi** [InkTimeRecord/TTime#209]
请提供下述完整信息以便快速定位问题 / Please provide the following information to quickly locate the problem：当我关机或者重新启动MAC电脑的时候，电脑其他软件都自动关闭了，唯独留下这个ttime不能自动关闭退出，从而让我的电脑重启或关闭。只能我每次手动将其退出，才能关机，其他软件都没有这个问题，希望早日修复。

- 系统环境 / System Environment：
ventura 13.6 (22G120)

- TTime版本号 / TTime Version：
0.92

- 问题描述 / Description of the issue：当我关机或者重新启动MAC电脑的时候，电脑其他软件都自动关闭了，唯独留下这个ttime不能自动关闭退出，从而让我的电脑重启或关闭。只能我每次手动将其退出，才能关机，其他软件都没有这个问题，希望早日修复。

**Comment by ByLiangCheng** [comment]
你好，这个问题已记录，近期我会进行测试一下

**Comment by ByLiangCheng** [comment]
新版本已发布，问题已修复
