### ISSUE TITLE
快捷键翻译时会开启大写，关闭软件后正常

### ISSUE THREAD

**Issue by lidizi** [InkTimeRecord/TTime#21]

**Comment by ByLiangCheng** [comment]
你好，感谢反馈，能否提供一下发生问题的系统版本及详细描述一下操作流程和情况

因为TTime中没有涉及到开启大写的操作，所以我这边需要试试看能不能复现出来

**Comment by lidizi** [comment]
@ByLiangCheng 不知道版本在哪看，前天才下载的，windows11下划词翻译无论设置什么快捷 alt+e |alt+r 等等都能开启大写

**Comment by lidizi** [comment]
@ByLiangCheng  设备名称	
处理器	Intel(R) Core(TM) i5-10500 CPU @ 3.10GHz   3.10 GHz
机带 RAM	32.0 GB (31.8 GB 可用)
系统类型	64 位操作系统, 基于 x64 的处理器
笔和触控	没有可用于此显示器的笔或触控输入  

版本	Windows 11 专业版
版本	22H2
安装日期	‎2022/‎12/‎12
操作系统版本	22621.1413
体验	Windows Feature Experience Pack 1000.22639.1000.0

**Comment by ByLiangCheng** [comment]
收到，后面我这会根据版本测试一下，看能否复现，感谢反馈

**Comment by lidizi** [comment]
感谢 @ByLiangCheng
