### ISSUE TITLE
[BUG] 360极速浏览器X无法启动鼠标悬浮球

### ISSUE THREAD

**Issue by izelle** [InkTimeRecord/TTime#210]
请提供下述完整信息以便快速定位问题 / Please provide the following information to quickly locate the problem

- 系统环境 / System Environment：
360极速浏览器版本：22.1.1011.64(64位)  内核版本：119.0.6045.9

- TTime版本号 / TTime Version：
v0.9.2

- 问题描述 / Description of the issue：
无法在360极速浏览器X无法启动鼠标悬浮球，实测小智双核浏览器正常，Edge v120.0.2172.1正常
因为最常用的就是360极速浏览器，实在是太不方便了

**Comment by ByLiangCheng** [comment]
你好，我这边测试使用360极速浏览器X是正常的，你看看是否因为浏览器插件的原因于TTime冲突了，之前有其他用户也有过这种类似的情况
