### ISSUE TITLE
[Feature] 希望增加云端OCR识别

### ISSUE THREAD

**Issue by Idealisten** [InkTimeRecord/TTime#212]
**功能描述 / Function Description**
希望像Bob一样使用云端OCR识别，例如火山、Google的API，主要是本地识别的太烂了，手动改太费时间

**Comment by ByLiangCheng** [comment]
你好，现在是支持的，你可以在设置里面看看

**Comment by Idealisten** [comment]
找到了，希望在OCR识别里可以增加Google的API

**Comment by ByLiangCheng** [comment]
新版本已发布，功能已新增
