### ISSUE TITLE
[Feature] 希望增加换行翻译，我原来以为可以用shift+enter进行换行翻译 ，可惜不行

### ISSUE THREAD

**Issue by CYJ-UP123** [InkTimeRecord/TTime#213]
**功能描述 / Function Description**
希望增加换行翻译，例如用shift+enter来实现

**Comment by ByLiangCheng** [comment]
你好，是指的在输入框中换行吗？是支持的，快捷键：Ctrl + Enter

**Comment by H3nryM4** [comment]
> 你好，是指的在输入框中换行吗？是支持的，快捷键：Ctrl + Enter

在大多数地方都是使用 Shift + Enter 换行。如果可以一致就好了

**Comment by ByLiangCheng** [comment]
下个版本中会支持

**Comment by ByLiangCheng** [comment]
已更新，版本已经发布
