### ISSUE TITLE
[Feature] 希望可以为翻译窗口添加一个最小化按钮  

### ISSUE THREAD

**Issue by CYJ-UP123** [InkTimeRecord/TTime#214]
**功能描述 / Function Description**
希望可以为翻译窗口添加一个最小化按钮

**Comment by ByLiangCheng** [comment]
你好，目前窗口是可以自动隐藏的，加入这个意义不太大吧

**Comment by yyrjlw** [comment]
我也赞同添加一个最小化按钮，有时候窗口自动隐藏了，我想打开还得去点托盘图标。
