### ISSUE TITLE
[Feature] 图标大大了，能缩小一点吗

### ISSUE THREAD

**Issue by whboy10000** [InkTimeRecord/TTime#216]
**功能描述 / Function Description**
<img width="1353" alt="iShot_2023-11-04_17 19 09" src="https://github.com/InkTimeRecord/TTime/assets/26360478/aa4b33ca-274f-424c-8d87-62fc64781aaa">

**Comment by whboy10000** [comment]
图标太大，和系统图标不协调，希望下个版本缩小一些

**Comment by ByLiangCheng** [comment]
你好，此问题目前是有记录的，但是由于因为时间关系，加上目前并没有太多影响实际功能的使用，所以优先级还没到这里来，后续会更新 ~

**Comment by ByLiangCheng** [comment]
已更新，版本已经发布
