### ISSUE TITLE
[Feature] 百度领域翻译

### ISSUE THREAD

**Issue by learningdog1** [InkTimeRecord/TTime#218]
Description
虽然软件中已有百度翻译，但还是希望能增加百度的垂直领域翻译接口，以满足特定领域的翻译需求，如计算机、金融经济和生物医学等。

Application Scenario
满足特定领域的翻译需求

References
灵感来自zotero插件，可在以下链接查看并参考：https://zotero.yuque.com/staff-gkhviy/pdf-trans/wewaia

**Comment by ByLiangCheng** [comment]
你好，此问题先记录下来了，后续会考虑加入

**Comment by ByLiangCheng** [comment]
功能已更新，版本已发布
