### ISSUE TITLE
[BUG] 百度OCR验证

### ISSUE THREAD

**Issue by learningdog1** [InkTimeRecord/TTime#219]
请提供下述完整信息以便快速定位问题 / Please provide the following information to quickly locate the problem

- 系统环境 / System Environment：

win11
- TTime版本号 / TTime Version：

0.9.3
- 问题描述 / Description of the issue：

**增加文字识别时，百度OCR验证失败，具体报错为：调用频率受限，请降低调用频率。**

> 前提：已确保完全安装教程申请和填写百度OCR。

**Comment by learningdog1** [comment]
问题截图
<img width="443" alt="375ee7db02c5061ad85ef9169cd1f69a" src="https://github.com/InkTimeRecord/TTime/assets/110441496/b4831893-35e3-444c-863c-7bd6ce17f261">

**Comment by ByLiangCheng** [comment]
你好，这个应该是你点击太快了，触发了百度OCR的频率限制吧，我这边看是正常的

**Comment by learningdog1** [comment]
> 你好，这个应该是你点击太快了，触发了百度OCR的频率限制吧，我这边看是正常的

我过几天后，慢点击还是一样的问题。

**Comment by ByLiangCheng** [comment]
> > 你好，这个应该是你点击太快了，触发了百度OCR的频率限制吧，我这边看是正常的
> 
> 我过几天后，慢点击还是一样的问题。

可以把日志发到我邮箱看看，我确认一下问题 byliangcheng@sina.com
