### ISSUE TITLE
[Feature] 改进本地OCR功能

### ISSUE THREAD

**Issue by NodeNerd1** [InkTimeRecord/TTime#220]
**功能描述 / Function Description**
本地OCR功能 识别率太低了

**Comment by ByLiangCheng** [comment]
你好，本地OCR大部分场景下，不细分时是还可以，目前想要精准一些的效果话，建议可以在设置中添加配置第三方OCR，自带的本地OCR后续也会进行优化一下，感谢建议

**Comment by ByLiangCheng** [comment]
新版本已发布，已优化此问题
