### ISSUE TITLE
[Feature] 输入框可以增加一个折叠按钮吗

### ISSUE THREAD

**Issue by Mizro-wu** [InkTimeRecord/TTime#221]
**功能描述 / Function Description**
输入框希望能增加一个折叠按钮，当不需要的时候可以折叠，需要的时候可以展开，它是一个可选的操作
发生的场景是当我大部分时候只需要查看翻译结果，这时如果主要展示翻译结果，默认收起输入框，可以让界面变得更加简洁，让注意力更加集中在翻译结果上面，
同时如果输入内容太长的时候，会占用第一屏的高度（其实界面上已经有需要翻译的内容），我还需要滑动查看
![image](https://github.com/InkTimeRecord/TTime/assets/71362039/1f3e1c2d-1f4a-4167-8937-1ed8cde589e1)
![image](https://github.com/InkTimeRecord/TTime/assets/71362039/459a1914-bf58-417c-8a01-a3353cb9babf)

**Comment by ByLiangCheng** [comment]
你好，先记录下来，会考虑一下

**Comment by ByLiangCheng** [comment]
功能已更新，版本已发布
