### ISSUE TITLE
[Feature] 静默截图ocr后自动搜索

### ISSUE THREAD

**Issue by heyeruoqi** [InkTimeRecord/TTime#222]
**功能描述 / Function Description**

不管是mac电脑上的popclip的搜索功能，还是Windows系统的Quicker软件的一些功能，都能实现将内容自动在一些网站上搜索关键词，具体为：mac电脑上的popclip用鼠标划了一个词，点击popclip的搜索图标，在自定义好搜索网址之后，就能直接在网址上搜索这个划得词。quicker软件的功能实现：点击动作，然后截图，ocr识别出截图中的文字，然后将该文字在自定义的网站上搜索关键词，希望ttime能增加这个歌功能，很需要这个功能。

**Comment by ByLiangCheng** [comment]
TTime目前来说主要针对的场景为翻译和ocr，针对这种搜索功能场景有点偏离方向了，并且感觉这种的目前需求不是很多，反而会给软件增加负担
