### ISSUE TITLE
[Feature] 希望添加DeepLX翻译源的支持

### ISSUE THREAD

**Issue by gsvuo** [InkTimeRecord/TTime#223]
**功能描述 / Function Description**
类似网页翻译插件沉浸式翻译的功能，可以添加DeepLX翻译源的API URL
![Snipaste_2023-11-13_21-49-17](https://github.com/InkTimeRecord/TTime/assets/138410655/e1c3a05d-0fbe-4b0b-8325-fdb6b2181ec3)

**Comment by weiyideai520** [comment]
+1

**Comment by Chandler-Lu** [comment]
[DeepLX](https://github.com/InkTimeRecord/TTime#%E7%9B%AE%E5%89%8D%E5%B7%B2%E9%9B%86%E6%88%90%E7%BF%BB%E8%AF%91%E6%96%87%E5%AD%97%E8%AF%86%E5%88%AB%E6%9C%8D%E5%8A%A1)
内置的DeepL就是DeepLX
