### ISSUE TITLE
[BUG] Mac 多桌面下翻译界面无法在当前桌面打开

### ISSUE THREAD

**Issue by g199209** [InkTimeRecord/TTime#224]
请提供下述完整信息以便快速定位问题 / Please provide the following information to quickly locate the problem

- 系统环境 / System Environment：
OS: 13.3.1 (a) (22E772610a)
Chip: Apple M1 Max

- TTime版本号 / TTime Version：
0.9.3

- 问题描述 / Description of the issue：
存在多显示器多桌面情况下，使用快捷键 `Option+E` 进行翻译，弹出的翻译界面没有显示在当前桌面上，而是固定显示在了某个桌面上，且会强制把当前显示的桌面切换到目标桌面。

**Comment by beilo** [comment]
System:
    OS: macOS 12.5.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 35.77 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Browsers:
    Chrome: 118.0.5993.88
    Safari: 15.6.1
    Safari Technology Preview: 16.0

TTime版本 0.9.3
我也遇到了同样的问题

**Comment by ByLiangCheng** [comment]
新版本已发布，功能已支持

可以在设置 -> 偏好设置 -> 开启 静默显示窗口
