### ISSUE TITLE
[Feature] 希望鼠标悬停可以增加中英对照的效果

### ISSUE THREAD

**Issue by Mizro-wu** [InkTimeRecord/TTime#225]
**功能描述 / Function Description**
希望鼠标悬停可以增加中英对照的效果，这样可以在视觉对照中英的时候，更快速清晰地看到中英结果
![image](https://github.com/InkTimeRecord/TTime/assets/71362039/267c2cfe-0562-400e-b0e8-3968e9d9d374)

**Comment by ByLiangCheng** [comment]
你好，这个目前技术上没有好的实现思路，很难区别出这种
