### ISSUE TITLE
[Feature] 希望打开设置的时候，翻译窗口能置顶显示

### ISSUE THREAD

**Issue by Mizro-wu** [InkTimeRecord/TTime#226]
希望打开设置的时候，翻译窗口能置顶显示
现在点开设置，翻译窗口会相当于最小化，不利于看实时的窗口变化效果
打开设置的时候，如果可以，希望翻译窗口能和设置窗口并排显示
![image](https://github.com/InkTimeRecord/TTime/assets/71362039/63257c91-b6f6-4d78-8707-a49b971d2384)

**Comment by ByLiangCheng** [comment]
你好，不太理解，为什么需要有设置出现的时候翻译窗口也置顶的场景

**Comment by Mizro-wu** [comment]
因为设置里面，有一些对窗口的改动是实时变动的，如果翻译窗口能和设置窗口并排显示，即翻译窗口置顶，这样我改变某一个设置的时候，就能直接看到变化了

**Comment by ByLiangCheng** [comment]
这个可以在翻译窗口右上角点击置顶开关就行，没有必要在设置打开时自动开启置顶，感觉这样很影响体验

**Comment by Mizro-wu** [comment]
也不是说必须开启置顶，其实就是能两个并排显示，对比看设置更改的效果，现在效果是翻译窗口会消失了，我要自己去任务栏重新点开，点置顶，再改设置，看效果
如果是自己一开始点击置顶开关，得建立在我已知哪些设置项可以看到效果，我点击设置按钮前才会先置顶

**Comment by ByLiangCheng** [comment]
这种暂时不考虑吧，现在需要开发的功能太多了，这种其实只需要在翻译窗口点一下置顶即可解决这个问题，如果很多人存在此问题，会考虑做优化
