### ISSUE TITLE
[Feature] 快速启用特定翻译源

### ISSUE THREAD

**Issue by Chandler-Lu** [InkTimeRecord/TTime#227]
**功能描述 / Function Description**
考虑到部分翻译源价格较高，以及同时开启多个翻译源的时候会占用大量空间，希望增加快速启用特定翻译源的功能，如图所示

点击后即可快速对当前翻译内容启用特定翻译源
![image](https://github.com/InkTimeRecord/TTime/assets/18322610/7fdd73bf-e9dc-441f-b914-a7f1ceda8147)

**Comment by ByLiangCheng** [comment]
你好，这个是有计划的

**Comment by ByLiangCheng** [comment]
功能已增加，新版本已发布

**Comment by Chandler-Lu** [comment]
> 功能已增加，新版本已发布

麻烦问一下会员近期有折扣计划嘛

**Comment by ByLiangCheng** [comment]
元旦那段时间有折扣活动计划 ~
