### ISSUE TITLE
[Feature] 管理员权限启动

### ISSUE THREAD

**Issue by Arsiendle** [InkTimeRecord/TTime#229]
希望能够默认以管理员权限启动，如snipaste的管理员启动模式。如果是自己手动以管理员权限启动每次都会弹出询问窗口，开机自启动的时候就很烦。
为什么需要管理员权限启动，经常有些时候TTime的截图用不了，得点击一下任务栏或者其他一些非系统级别的东西才能截图

**Comment by ByLiangCheng** [comment]
你好，请问下你这是什么系统下出现的呢？正常来说不会有这些情况的，目前也没有其他用户反馈有这样子，看起来像是个例

**Comment by Arsiendle** [comment]
win11，最容易复现的一个情况就是 任务管理器，打开任务管理器后 不点击其他地方（点击任务栏或者其他地方会更改目标），会默认目标是任务管理器，这个时候就无法使用TTime截图，除非关闭后使用管理员权限打开TTime，这个时候就可以正常截图了。应该是权限不够的问题。

**Comment by ByLiangCheng** [comment]
抱歉，我先这两天尝试复现了一下，没有复现出你这种情况，或者你可以加一下我的联系方式，我远程给你看看这个问题

**Comment by QianMoXi** [comment]
> 抱歉，我先这两天尝试复现了一下，没有复现出你这种情况，或者你可以加一下我的联系方式，我远程给你看看这个问题

这个，我大概知道原因，应该是他的快捷键设置成F1-F12这种单按键触发方式了，然后任务管理器是管理员权限启动的，他按F1-F12这种快捷键的时候，按键信息是不会给没管理员权限的窗口的，具体原因忘记了。

如果是带Ctrl或者Alt这种的快捷键，就能正常触发。

所以要不然是他改一下快捷键，要不然就只能用管理员启动TTime才能正常使用

**Comment by ByLiangCheng** [comment]
> > 抱歉，我先这两天尝试复现了一下，没有复现出你这种情况，或者你可以加一下我的联系方式，我远程给你看看这个问题
> 
> 这个，我大概知道原因，应该是他的快捷键设置成F1-F12这种单按键触发方式了，然后任务管理器是管理员权限启动的，他按F1-F12这种快捷键的时候，按键信息是不会给没管理员权限的窗口的，具体原因忘记了。
> 
> 如果是带Ctrl或者Alt这种的快捷键，就能正常触发。
> 
> 所以要不然是他改一下快捷键，要不然就只能用管理员启动TTime才能正常使用

采纳此方案，issues关闭
