### ISSUE TITLE
macos12安装后出现 “您无法打开应用程序“TTime”，因为这台Mac不支持此应用程序。”

### ISSUE THREAD

**Issue by chaofanhaochi12** [InkTimeRecord/TTime#23]

**Comment by ByLiangCheng** [comment]
你好，请问 Mac 是 Intel 版本的吗？如果是，暂时不支持，近期版本中会加上 Intel 版本的安装包

**Comment by chaofanhaochi12** [comment]
> 你好，请问 Mac 是 Intel 版本的吗？如果是，暂时不支持，近期版本中会加上 Intel 版本的安装包
是的 2019款的mbp

好的

**Comment by ByLiangCheng** [comment]
新版已发布，此问题已修复，下载最新版即可
