### ISSUE TITLE
[Feature] 希望可以增加音标的标注

### ISSUE THREAD

**Issue by Mizro-wu** [InkTimeRecord/TTime#230]
**功能描述 / Function Description**
有时语音朗读可能会有不够清晰或者和日常读音不同的情况，希望可以增加音标的标注
![image](https://github.com/InkTimeRecord/TTime/assets/71362039/ba86e011-6ab9-4369-b95f-97127faa68e0)

**Comment by ByLiangCheng** [comment]
关于这个建议可以添加词典翻译源，里面有英标
