### ISSUE TITLE
[BUG] 更换系统用户名后无法启动

### ISSUE THREAD

**Issue by yuandoudou928** [InkTimeRecord/TTime#231]
请提供下述完整信息以便快速定位问题 / Please provide the following information to quickly locate the problem

- 系统环境 / System Environment：
Windows11

- TTime版本号 / TTime Version：
0.9.3

- 问题描述 / Description of the issue：
我换了系统用户名，不能启动，卸载了重新安装也不能启动
<img width="419" alt="Snipaste_2023-11-28_20-35-11" src="https://github.com/InkTimeRecord/TTime/assets/16776103/c819f7b8-0d9a-4ca6-8b41-6acf12c79188">

**Comment by ByLiangCheng** [comment]
你好，可以尝试修改：C:\Users\系统用户名\AppData\Roaming\time-translate\system.json 这个文件里面的配置路径或删除这个文件后再进行打开TTime试试
