### ISSUE TITLE
悬浮球点击就关闭当前播放的视频，或将当前静默的视频打开。

### ISSUE THREAD

**Issue by ropsdjl0000** [InkTimeRecord/TTime#235]
悬浮球一点击就关闭当前播放的视频，或将当前静默的视频打开。怎么设置才能不影响当前网页的视频？或者根本就是个bug?

**Comment by ByLiangCheng** [comment]
你好，有示例吗？还是说所有的网页播放视频都有这样的情况呢？电脑是什么系统呢？
