### ISSUE TITLE
[BUG] 鼠标悬浮球显示异常

### ISSUE THREAD

**Issue by WittyMao** [InkTimeRecord/TTime#236]
- 系统环境 / System Environment：Windows 10 专业版 22H2 （19045.3693）

- TTime版本号 / TTime Version：0.9.4

- 问题描述 / Description of the 

1. 添加OCR源tooltip显示错误

![PixPin_2023-12-07_02-46-03](https://github.com/InkTimeRecord/TTime/assets/24718923/ce63209c-2079-4705-96c9-efc7dd850dd7)

2. 鼠标悬浮球（已开启增强模式）显示异常：遇到可选择文本的文本，在未选中文本的情况下单击鼠标即触发悬浮球显示（出现一次触发后连续切换单击不同文本触发概率极高）
![PixPin_2023-12-07_03-25-44](https://github.com/InkTimeRecord/TTime/assets/24718923/e0171586-78c4-4077-8ea4-91590bc206ff)

**Comment by ByLiangCheng** [comment]
你好，添加OCR源tooltip显示错误下个版本修复

关于悬浮球的问题，是在任何地方都会出现吗？是否有尝试过重新开关悬浮球，我这边目前没有复现出来这种情况

**Comment by WittyMao** [comment]
> 你好，添加OCR源tooltip显示错误下个版本修复
> 
> 关于悬浮球的问题，是在任何地方都会出现吗？是否有尝试过重新开关悬浮球，我这边目前没有复现出来这种情况

您好，悬浮球的问题在任何地方都会出现，重新开关也是一样的情况，我刚在win11的虚拟机上试了下一样会出现，您试试先选中一段文本触发悬浮球，然后在同一界面单击其他文本会不会复现。

**Comment by WittyMao** [comment]
我发现单击文本的瞬间鼠标指针微微往上偏移百分百复现

**Comment by ByLiangCheng** [comment]
> 我发现单击文本的瞬间鼠标指针微微往上偏移百分百复现

这个可以演示一下吗？我这边怎么操作都没有单击的时候出来

**Comment by WittyMao** [comment]
> > 我发现单击文本的瞬间鼠标指针微微往上偏移百分百复现
> 
> 这个可以演示一下吗？我这边怎么操作都没有单击的时候出来

那你试试单击鼠标不放然后指针往上偏移一点再放开
![PixPin_2023-12-08_16-44-08](https://github.com/InkTimeRecord/TTime/assets/24718923/2bd14f91-80d5-4ab1-9cc5-253856203f95)

**Comment by WittyMao** [comment]
我开了沙拉查词的悬浮球和鼠标点击效果能看更直观一点
![PixPin_2023-12-08_17-38-02](https://github.com/InkTimeRecord/TTime/assets/24718923/18b6c4f9-4907-4d7d-b05c-d79fc9669290)

**Comment by ByLiangCheng** [comment]
> 我开了沙拉查词的悬浮球和鼠标点击效果能看更直观一点

你好，目前我这边测试效果是这样的，当鼠标光标为选中状态时，会监听是否划词，如果你鼠标有单击长按并拖动，那么就会触发显示悬浮球

**Comment by ByLiangCheng** [comment]
由于长时间未回复，issues关闭
