### ISSUE TITLE
[BUG] 与PowerToys按键映射的冲突

### ISSUE THREAD

**Issue by im6chen** [InkTimeRecord/TTime#238]
请提供下述完整信息以便快速定位问题 / Please provide the following information to quickly locate the problem

- 系统环境 / System Environment：
win 11 + PowerToys

- TTime版本号 / TTime Version：
0.9.4

- 问题描述 / Description of the issue：
![screen](https://github.com/InkTimeRecord/TTime/assets/48371247/29e60007-3bcd-4104-9fc4-b3ef64d031ba)

一个很奇怪的冲突：
使用PowerToys 开启按键映射后，划词翻译快捷键变成了大小写切换，而且是无论怎样更换快捷键组合都会冲突。
关闭PowerToys按键映射后正常，奇怪的是PowerToys中并没有关于Alt的按键映射。

特此反馈，感谢。

**Comment by ByLiangCheng** [comment]
你好，按下划词快捷键后，软件内部是模拟按下了 Ctrl + C 进行触发复制操作的，你这里修改了Ctrl的改为了大小写切换，所以导致的吧

**Comment by im6chen** [comment]
这样的话就明白了，感谢回复~
