### ISSUE TITLE
[BUG] 0.9.4启动时会显示设置界面

### ISSUE THREAD

**Issue by QianMoXi** [InkTimeRecord/TTime#239]
请提供下述完整信息以便快速定位问题 / Please provide the following information to quickly locate the problem

- 系统环境 / System Environment：
Win11 23H2

- TTime版本号 / TTime Version：
0.9.4

- 问题描述 / Description of the issue：

无论是设置开机自启，还是双击EXE启动程序，都会显示出设置界面，这导致开机时还得手动关闭窗口

但是0.9.3是没这个问题的，会默认最小化到任务栏图标里

**Comment by ByLiangCheng** [comment]
这是BUG，下个版本修复，现在解决方案是登录后就不会再弹出了

**Comment by ByLiangCheng** [comment]
功能已更新，版本已发布
