### ISSUE TITLE
在果核剥壳上发现的,打开后报错,来github下载原版也报错

### ISSUE THREAD

**Issue by ingxhe** [InkTimeRecord/TTime#24]
不需要修复,我打算用有道
![image](https://user-images.githubusercontent.com/30750321/227190728-fa1a8c00-62cd-4ad7-84b6-f754f9691161.png)

**Comment by ByLiangCheng** [comment]
你好，感谢反馈

这个问题是因为电脑缺少驱动导致的，更新下电脑驱动可以解决

**Comment by ByLiangCheng** [comment]
此问题已修复，新版本已发布，如还有问题，请重新提交Issues
