### ISSUE TITLE
[BUG] 在MacBook上安装App后提示已损坏

### ISSUE THREAD

**Issue by amxuejin** [InkTimeRecord/TTime#240]
请提供下述完整信息以便快速定位问题 / Please provide the following information to quickly locate the problem

- 系统环境 / System Environment：MacBook Air (M1)，macOS 14.1.2 (23B92)

- TTime版本号 / TTime Version：TTime-0.9.4-arm64

- 问题描述 / Description of the issue：在MacBook上安装App后提示已损坏，见附件截图
<img width="968" alt="Snipaste_2023-12-09_09-26-54" src="https://github.com/InkTimeRecord/TTime/assets/14815399/df340b1c-a086-4cbd-a939-ed8e5a97e5ce">

**Comment by ByLiangCheng** [comment]
#48  这个问题可以参考下这个Issues哈
