### ISSUE TITLE
[BUG] OCR后文字不能换行

### ISSUE THREAD

**Issue by Mizro-wu** [InkTimeRecord/TTime#241]
请提供下述完整信息以便快速定位问题 / Please provide the following information to quickly locate the problem

- 系统环境 / System Environment：
Win11 22H2

- TTime版本号 / TTime Version：
0.9.4

- 问题描述 / Description of the issue：
OCR文字后，在文字中间换行，会变成在最后换行
![image](https://github.com/InkTimeRecord/TTime/assets/71362039/422a6ed8-e8fe-4d63-a081-454e760104ee)

**Comment by ByLiangCheng** [comment]
目前确实存在此问题，已记录，后续版本中会进行修复

**Comment by ByLiangCheng** [comment]
新版本已发布，问题已修复
