### ISSUE TITLE
[Feature] Plugin system.

### ISSUE THREAD

**Issue by iG8R** [InkTimeRecord/TTime#243]
**功能描述 / Function Description**
Hi.
Could you please implement the plugin system similar to QTranslate, i.e. when simple text files containing javascripts are used for each translation service.
More information here: https://www.52pojie.cn/thread-1695613-1-1.html

**Comment by ByLiangCheng** [comment]
#250 You may consult this response.

**Comment by iG8R** [comment]
The QTranslate plugin system is convenient precisely because it will be easy to maintain, because they are just plain text files containing javascript that can be edited by any javascript-savvy user without the need to compile or tamper with the internal TTime structure.

**Comment by ByLiangCheng** [comment]
> The QTranslate plugin system is convenient precisely because it will be easy to maintain, because they are just plain text files containing javascript that can be edited by any javascript-savvy user without the need to compile or tamper with the internal TTime structure.

While this option exists, its implementation may not be prioritized in the near future. Let us first gauge public demand and consider that existing translation sources already offer a more extensive range of services.

This decision is driven by the higher costs associated with developing and maintaining a feature that caters to a limited audience.
