### ISSUE TITLE
[BUG] SystemMenu 未支持暗黑主题

### ISSUE THREAD

**Issue by emako** [InkTimeRecord/TTime#244]
请提供下述完整信息以便快速定位问题 / Please provide the following information to quickly locate the problem

- 系统环境 / System Environment：
W11 23H2 22631.2715

- TTime版本号 / TTime Version：
0.9.4

- 问题描述 / Description of the issue：
正常的应用：
![image](https://github.com/InkTimeRecord/TTime/assets/24737061/f563c889-c58f-4448-a445-3edba9cac6ea)

TT：
![image](https://github.com/InkTimeRecord/TTime/assets/24737061/9db0f9a5-e74d-4577-97e0-3ccdf325ba7f)

**Comment by ByLiangCheng** [comment]
你好，确实存在这种情况，因为右键上菜单的效果理应是无效的，下个版本中会关闭此右键事件，直接不显示 ~

**Comment by emako** [comment]
有个菜单不也挺好的

**Comment by ByLiangCheng** [comment]
> 有个菜单不也挺好的

是有这种使用的需求吗？

我记得这个菜单里面的选项点击时没有效果，而且右键后好像无法关闭吧，你是 win11 吗？是可以正常使用的吗？

**Comment by emako** [comment]
win11，可以正常使用，而且有个习惯就是右键菜单关窗口

**Comment by emako** [comment]
这个好像不好调整，暂时关闭了

**Comment by ByLiangCheng** [comment]
> 这个好像不好调整，暂时关闭了

不好调整指的是不需要这个功能吗？还是？我准备有空的时候看一下，要是不用我就后续的移除此功能了
