### ISSUE TITLE
[BUG] 截图翻译很慢

### ISSUE THREAD

**Issue by bzjckl** [InkTimeRecord/TTime#246]
请提供下述完整信息以便快速定位问题 / Please provide the following information to quickly locate the problem

- 系统环境 / System Environment：win11

- TTime版本号 / TTime Version：0.9.4

- 问题描述 / Description of the issue：快捷键打开截图翻译很慢，右键点击截图翻译功能能也有这个问题

**Comment by uniquMonte** [comment]
是不是你电脑或者网络的问题，我这边截图翻译速度很快啊

**Comment by bzjckl** [comment]
不是的，我是说快捷键唤起截图界面慢要等一两秒才能截图，不是翻译过程慢，快捷键唤起不需要访问网络啊

**Comment by ByLiangCheng** [comment]
> 不是的，我是说快捷键唤起截图界面慢要等一两秒才能截图，不是翻译过程慢，快捷键唤起不需要访问网络啊

你好，可以录屏看看效果吗？我测试多台设备看都挺快的
