### ISSUE TITLE
[Feature] 软件挺好用，openai翻译可否增加最新的11-06的gpt模型？

### ISSUE THREAD

**Issue by uniquMonte** [InkTimeRecord/TTime#247]
GPT的最新模型gpt-3.5-turbo-1106已经发布一段时间了，可否在Openai翻译里面增加这个新模型，毕竟新模型更便宜了，功能应该也不会差，当然能同时增加GPT4的最新模型那就更好了，谢谢

**Comment by ByLiangCheng** [comment]
你好，下个版本中加入 ~

**Comment by ByLiangCheng** [comment]
功能已更新，版本已发布
