### ISSUE TITLE
[BUG] 多显示器下，截图翻译界面的操作按钮位置异常

### ISSUE THREAD

**Issue by Chandler-Lu** [InkTimeRecord/TTime#248]
请提供下述完整信息以便快速定位问题 / Please provide the following information to quickly locate the problem

- 系统环境 / System Environment：
Windows 11 23H2 22631

屏幕1：
![Snipaste_2023-12-14_20-02-47](https://github.com/InkTimeRecord/TTime/assets/18322610/bc1dc49a-4a5d-4aeb-8e24-082ed903d108)

屏幕2：
![Snipaste_2023-12-14_20-02-56](https://github.com/InkTimeRecord/TTime/assets/18322610/b5570050-3a6c-4bfb-b7c2-2cc4cc7008b7)

- TTime版本号 / TTime Version：
0.9.4

- 问题描述 / Description
多显示器下，截图翻译界面的操作按钮位置异常
![Snipaste_2023-12-14_20-01-00](https://github.com/InkTimeRecord/TTime/assets/18322610/9b3f3a7c-0938-49a4-b643-a77fbdc0c460)
 of the issue：

**Comment by ByLiangCheng** [comment]
你好，发现确实存在，后续版本中会进行修复 ~

**Comment by ByLiangCheng** [comment]
新版本已发布，功能已修复
