### ISSUE TITLE
[Feature] 开机启动后不显示窗口

### ISSUE THREAD

**Issue by heheda123123** [InkTimeRecord/TTime#249]
**功能描述 / Function Description**
每次开机后就会自动弹出ttime的设置界面，
![image](https://github.com/InkTimeRecord/TTime/assets/97490782/21bd010e-318d-4532-9e29-5445e4e51e88)

是否可以弄成默认不显示

**Comment by ByLiangCheng** [comment]
#239 这个已经回答过了，可以参考一下
