### ISSUE TITLE
[BUG] 修改用户文件夹名称后启动报错

### ISSUE THREAD

**Issue by noobshmily** [InkTimeRecord/TTime#252]
请提供下述完整信息以便快速定位问题 / Please provide the following information to quickly locate the problem

- 系统环境 / System Environment：windows 10

- TTime版本号 / TTime Version：0.9.4

- 问题描述 / Description of the issue：

windows10 修改用户文件夹名称后，也同时修改了注册表，启动 TTime 时报错，其中马赛克部分为修改前的用户名文件夹名称

![image](https://github.com/InkTimeRecord/TTime/assets/70653977/7c0a926e-be68-409f-b131-2bb5400e0038)

**Comment by ByLiangCheng** [comment]
#231 参考一下这个issues哈
