### ISSUE TITLE
[BUG] 关于bing词典和bing翻译特定词汇出错

### ISSUE THREAD

**Issue by aaaz6** [InkTimeRecord/TTime#253]
请提供下述完整信息以便快速定位问题 / Please provide the following information to quickly locate the problem

- 系统环境 / System Environment：
windows 11

- TTime版本号 / TTime Version：
0.9.4

- 问题描述 / Description of the issue：
当我使用bing词典或翻译，翻译句子中附带“学习”这两个字时，翻译都会翻成XI
![image](https://github.com/InkTimeRecord/TTime/assets/146999733/662d2a1d-f2f0-4acf-b43a-484b2b8719e3)

**Comment by ByLiangCheng** [comment]
你好 , 目前看这个是 bing 翻译源的问题 , 我尝试在 bing 翻译中也会出现 XI 这样的效果 , 如图 :

<img width="756" alt="image" src="https://github.com/InkTimeRecord/TTime/assets/45414993/a58c8531-4f7d-4020-9f6a-a45bba5167bd">

**Comment by aaaz6** [comment]
该问题已被官网修复
