### ISSUE TITLE
[Feature] 支持自定义模型

### ISSUE THREAD

**Issue by DillionApple** [InkTimeRecord/TTime#254]
**功能描述 / Function Description**
有一些公司的模型 API 是遵循 OpenAI 格式的，但是名字不叫 gpt-4 之类的，希望能够支持自定义模型，让用户能直接接入这些模型 API。

**Comment by ByLiangCheng** [comment]
收到，先记录下来了后续会考虑下这块

**Comment by ByLiangCheng** [comment]
新版本已支持
