### ISSUE TITLE
[BUG] 无法启动TTime

### ISSUE THREAD

**Issue by arjun-home** [InkTimeRecord/TTime#255]
请提供下述完整信息以便快速定位问题 / Please provide the following information to quickly locate the problem

- 系统环境 / System Environment：

Windows 11 专业版 23H2

- TTime版本号 / TTime Version：

0.9.3 & 0.9.4

- 问题描述 / Description of the issue：

TTime 安装后无法启动，表现为2-3秒的鼠标移动卡顿，任务栏短暂出现图标后消失，但后台显示 TTime.exe 已启动
![issue](https://github.com/InkTimeRecord/TTime/assets/154496313/67f4e5c1-aed0-4395-8e96-678121a6b794)
![issue](https://github.com/InkTimeRecord/TTime/assets/154496313/0e17c336-c3c7-41a5-a30f-693c575c8b60)

**Comment by ByLiangCheng** [comment]
指的是会在任务栏显示出来，过几秒后就不见了，但实际在任务管理器看得到，但是无法使用是吗 ？

你看看尝试安装到C盘试试

**Comment by arjun-home** [comment]
感谢，已通过安装到C盘默认路径解决
