### ISSUE TITLE
[Feature] 希望账号注册支持邮箱注册或者非大陆手机号注册

### ISSUE THREAD

**Issue by gsvuo** [InkTimeRecord/TTime#257]
**功能描述 / Function Description**
如题，没有账号点登录跳转到官网登录，在注册页面填写手机号无法选择国家区号，没有大陆手机号直接无法注册账号，也不支持邮箱注册。

**Comment by ByLiangCheng** [comment]
收到，近期会支持上去

**Comment by ByLiangCheng** [comment]
此功能已支持 ~
