### ISSUE TITLE
[Feature] 划词翻译是否支持连续翻译

### ISSUE THREAD

**Issue by shaopeijie** [InkTimeRecord/TTime#258]
**功能描述 / Function Description**
能否实现在划词模式下，自动检测鼠标选中的单词并翻译，不必划一个词按一下快捷键的功能？

**Comment by ByLiangCheng** [comment]
你好，这块目前可以使用悬浮球翻译进行解决吧，如果划词一下就翻译，干扰性较大

并且由于目前还没有完美兼容各个系统间划词选中文字问题，可能会有不可预料的问题
