### ISSUE TITLE
[BUG] Mac桌面端安装反复提示需要辅助功能，然而辅助功能早已开启

### ISSUE THREAD

**Issue by SeqCrafter** [InkTimeRecord/TTime#260]
请提供下述完整信息以便快速定位问题 / Please provide the following information to quickly locate the problem

- 系统环境 / System Environment：
MacOS

- TTime版本号 / TTime Version：

最新
- 问题描述 / Description of the issue：
<img width="471" alt="image" src="https://github.com/InkTimeRecord/TTime/assets/43256809/05731310-2809-4155-b6d1-584745a831f1">
启动TT,就让开启辅助功能，而辅助功能已经开启，导致应用程序无法启动

**Comment by ByLiangCheng** [comment]
把这个权限先删除，再重新添加一下就可以了

**Comment by SeqCrafter** [comment]
> 把这个权限先删除，再重新添加一下就可以了

肯定试过了不行的

**Comment by ByLiangCheng** [comment]
> > 把这个权限先删除，再重新添加一下就可以了
> 
> 肯定试过了不行的

确认是先删除了这个权限，而后再重新添加不行吗？

这个目前已知不只是TTime，其他软件也会有这种情况，都是这样的解决方案

如果还是不行的话，你可以加一下我的联系方式

**Comment by kadarechen** [comment]
我更新到了最新版本，也遇到了同样的问题，删掉重新添加权限没有用（Mac/M芯片）
（还有就是希望能够不要整天弹更新弹窗，真的很烦人，更新了之后又有问题，现在软件也打不开，TTime已经用习惯了突然不能用真的很影响学习工作，付费用户，之前捐赠过也买过月度会员，希望能有这方面改进，感谢。世界和平love&peace）
（哦对了，每次更新还要重新自签名一下，真的真的真的真的真的真的很麻烦，这种痛你懂吗）
（最后感谢开发者，感恩）
（目前已经回滚到0.9.4了，然后一直看着更新弹窗反复弹出...真的奔溃了）

**Comment by ByLiangCheng** [comment]
> 我更新到了最新版本，也遇到了同样的问题，删掉重新添加权限没有用（Mac/M芯片） （还有就是希望能够不要整天弹更新弹窗，真的很烦人，更新了之后又有问题，现在软件也打不开，TTime已经用习惯了突然不能用真的很影响学习工作，付费用户，之前捐赠过也买过月度会员，希望能有这方面改进，感谢。世界和平love&peace） （哦对了，每次更新还要重新自签名一下，真的真的真的真的真的真的很麻烦，这种痛你懂吗） （最后感谢开发者，感恩） （目前已经回滚到0.9.4了，然后一直看着更新弹窗反复弹出...真的奔溃了）

这块我回复下哈

如果遇到“删掉重新添加权限没有用”可以联系我们，我们协助解决此问题，这块一般是在操作流程某一步出现了问题，因为我们有少部分用户有反馈此问题时，基本上是这样解决的

关于目前每次重新需要自签名和重复添加权限了解到是Mac端的问题，其次了解到目前解决，是需要缴纳99美元一年的认证费，我们现在提供的服务日常及运营已耗费部分资金，所以也正在努力把营收提高，再回馈到产品中，有了大家的支持我们才有更多功能增添的能力 ！

（“真的真的真的真的真的真的很麻烦，这种痛你懂吗” 关于这个我也真的很理解和能感受到痛苦，作为很在意用户体验的我们来说，我一直都认为这块是我们的一个巨大的缺陷，我们也会近期尽量尽快的优化这里😭）

关于更新弹窗的话，目前是希望有新版本大家能尽量更新，所以才会每次软件启动的时候或12小时提示一次，因为现在的版本多多少少还有一些问题或功能不完善的地方，这些也都在一一解决中，有了更多人的体验和意见我们才能更快的修复问题，当然如果实在不希望更新和看到提示的话，可以在设置 -> 偏好设置 -> 自动检测新版本 进行关闭就可以了

最后也感谢大家的使用和支持 🙏🙏🙏
