### ISSUE TITLE
[Feature] 截图OCR识别建议集成tesseract

### ISSUE THREAD

**Issue by haibaradc** [InkTimeRecord/TTime#261]
**功能描述 / Function Description**
tesseract比目前自带的OCR成功率高很多，建议参考下

**Comment by ByLiangCheng** [comment]
tesseract 识别率不高吧？我之前试过，识别效果很差就没加了

**Comment by haibaradc** [comment]
我用过pot的翻译软件，OCR设置成tesseract.js以后，用ttime不能识别的图片pot都可以识别。

**Comment by ByLiangCheng** [comment]
> 我用过pot的翻译软件，OCR设置成tesseract.js以后，用ttime不能识别的图片pot都可以识别。

下个版本中关于部分图片识别失败的问题我们将会修复

如果认为tesseract.js不错的话，可以举例一下吗？因为由于我在尝试对比识别效果上，试用过一段时间，很多方面都无法得到好的效果，最后不得不放弃了

**Comment by haibaradc** [comment]
![image](https://github.com/InkTimeRecord/TTime/assets/8393644/d1e9288f-24c7-4d18-86fa-6d8b9755ea78)
你可以看下对于同一句话的对比识别

**Comment by ByLiangCheng** [comment]
这个是之前遗留下来的BUG，我们已经修复，将会在下个版本中进行发布，同时也增添了更多语言的支持哈

**Comment by ByLiangCheng** [comment]
新版本已发布，问题已修复
