### ISSUE TITLE
[BUG] 在chrome里划词翻译不能正常使用

### ISSUE THREAD

**Issue by bd-dxg** [InkTimeRecord/TTime#262]
请提供下述完整信息以便快速定位问题 / Please provide the following information to quickly locate the problem

- 系统环境 / System Environment：

版本	Windows 11 专业版
版本	23H2
操作系统版本	22631.2715

Chrome 版本 121.0.6167.86（正式版本） （64 位）

- TTime版本号 / TTime Version：0.9.5

- 问题描述 / Description of the issue：

在chrome中使用快捷键划词翻译 一直提示 识别内容为空

![image](https://github.com/InkTimeRecord/TTime/assets/34816426/a18f3436-37b3-4406-a84e-7deb9579fae0)

**Comment by ByLiangCheng** [comment]
之前其他用户出现这样的情况时，排查基本上都是由于chrome浏览器中的插件导致冲突，这块的话，建议后续再出现的话可以开启浏览器的无痕模式进行尝试看是否可用哈

因为开启这个模式后，插件都默认没有的，这样的话可以确认是否因为插件导致的

#102 具体也可以参考下这里
