### ISSUE TITLE
[BUG] 有时选中的文字调用划词翻译不能正常识别

### ISSUE THREAD

**Issue by Mizro-wu** [InkTimeRecord/TTime#263]
请提供下述完整信息以便快速定位问题 / Please provide the following information to quickly locate the problem

- 系统环境 / System Environment：
Win11 23H2

- TTime版本号 / TTime Version：
0.9.5

- 问题描述 / Description of the issue：
有时选中的文字调用划词翻译不能正常识别

https://github.com/InkTimeRecord/TTime/assets/71362039/ebbcfcb6-b02f-408c-9d23-6904bed61c48

**Comment by ByLiangCheng** [comment]
可以在设置 -> 偏好设置 -> 划词默认前后延迟 调高一点试试

**Comment by uniquMonte** [comment]
这种情况，我有时候也遇到：有时选中的文字调用划词翻译不能正常识别。

**Comment by ByLiangCheng** [comment]
> 可以在设置 -> 偏好设置 -> 划词默认前后延迟 调高一点试试

@uniquMonte 上面这种方式有试过吗？

> 这种情况，我有时候也遇到：有时选中的文字调用划词翻译不能正常识别。

**Comment by uniquMonte** [comment]
> > 可以在设置 -> 偏好设置 -> 划词默认前后延迟 调高一点试试
> 
> @uniquMonte 上面这种方式有试过吗？
> 
> > 这种情况，我有时候也遇到：有时选中的文字调用划词翻译不能正常识别。

试过，还是一样的，有时候就是识别为空了

**Comment by ByLiangCheng** [comment]
你好，按照这三个方法，大部分情况下都可以解决

1.在设置 -> 偏好设置 -> 划词默认前后延迟 的值调大一些后看看能不能正常划词
2.如果是在浏览器中划词失败 , 请检查是否有插件冲突
3.windows 环境下是否有使用工具修改过系统快捷键，有的话需要改回去

如果还不行，可以按照官网的联系方式联系我，我这边详细再看看
