### ISSUE TITLE
[BUG] 无法打开软件，显示报错

### ISSUE THREAD

**Issue by laochenfei233** [InkTimeRecord/TTime#264]
请提供下述完整信息以便快速定位问题 / Please provide the following information to quickly locate the problem

- 系统环境 / System Environment：
Windows10 loT企业版（22H2）

- TTime版本号 / TTime Version：
0.9.5（其实从0.9.0开始就有类似问题）

- 问题描述 / Description of the issue：
升级以后无法打开软件，显示报错如图
![QQ截图20240131105811](https://github.com/InkTimeRecord/TTime/assets/42639527/07bec1d2-e1c5-45b5-9439-f0e35f538f5e)
重新安装以及使用便捷版也是如此报错

**Comment by ByLiangCheng** [comment]
你好，目前看起来是权限不够引起的问题，你打开一下这个路径：C:\Users\chenfei\AppData\Roaming\time-translate\userDataConfig\

看看 config.json 和 config.json.tmp-6669871559128561 这两个文件是否存在

**Comment by laochenfei233** [comment]
有config.json，没有config.json.tmp-6669871559128561这个文件

**Comment by laochenfei233** [comment]
有config.json，没有config.json.tmp-6669871559128561这个文件

**Comment by ByLiangCheng** [comment]
> 有config.json，没有config.json.tmp-6669871559128561这个文件

发现是使用 electron-store https://github.com/sindresorhus/electron-store/issues/261 存储库的问题，我正在查看解决方案，可以加一下我的联系方式（官网上有）进行协助测试一下吗？我将会打包一个测试版给你进行联调
