### ISSUE TITLE
[Feature] 增量翻译

### ISSUE THREAD

**Issue by lisontowind** [InkTimeRecord/TTime#265]
**功能描述 / Function Description**
希望可以添加一个快捷键，使用该快捷键，会将选中文字添加到之前已翻译的原文本后面再进行翻译

适用于pdf跨页断句不好划选的情况

**Comment by ByLiangCheng** [comment]
你好，下个版本会新增连续翻译模式

**Comment by ByLiangCheng** [comment]
新版本已发布，功能已新增
