### ISSUE TITLE
[BUG] V1会员 将翻译源模式设置为折叠模式后将软件重启 会自动变为普通模式

### ISSUE THREAD

**Issue by CeivenLean** [InkTimeRecord/TTime#268]
请提供下述完整信息以便快速定位问题 / Please provide the following information to quickly locate the problem

- 系统环境 / System Environment：
win10 ltsc 1809

- TTime版本号 / TTime Version：
0.9.5

- 问题描述 / Description of the issue：
已购V1会员，将翻译源（内置源与自己添加的第三方源）模式设置为折叠模式后将软件重启，会自动变为普通模式

**Comment by ByLiangCheng** [comment]
你好，确实存在此问题，下个版本将会修复

**Comment by ByLiangCheng** [comment]
新版本已发布，问题已修复
