### ISSUE TITLE
[BUG] 安装时的缺失DLL检测逻辑有问题

### ISSUE THREAD

**Issue by heheda123123** [InkTimeRecord/TTime#272]
请提供下述完整信息以便快速定位问题 / Please provide the following information to quickly locate the problem

- 系统环境 / System Environment：
windows 11 

- TTime版本号 / TTime Version：

- 问题描述 / Description of the issue：
安装时会提示检测缺少dll文件，但是实际我并不缺，安装这个vc redist也会失败，我都是点了确定，弹出安装vc redist之后直接关闭
应该是检测的逻辑有点问题把
![image](https://github.com/InkTimeRecord/TTime/assets/97490782/1eb98692-12a5-41b2-8955-f84c1567c548)
![image](https://github.com/InkTimeRecord/TTime/assets/97490782/93dacbc0-f66f-441d-9de7-40618b4eaece)

**Comment by ByLiangCheng** [comment]
您好，我们已记录此问题，近期会看看解决方案

**Comment by XMendylo** [comment]
这个导致无法更新，实际电脑有这个vc组件，点安装的这个14.34无法安装，因为已经安装了官方的14.38。这个问题很久了。

**Comment by bookbindinggithub** [comment]
好像還沒解決。現在還有。win11系統。

**Comment by ByLiangCheng** [comment]
已修复，下个版本将会更新

**Comment by ByLiangCheng** [comment]
问题已修复，新版本已发布
