### ISSUE TITLE
[BUG] 安装时的缺失DLL检测逻辑有问题2

### ISSUE THREAD

**Issue by emako** [InkTimeRecord/TTime#273]
请提供下述完整信息以便快速定位问题 / Please provide the following information to quickly locate the problem

- 系统环境 / System Environment：
w11 23H2

- TTime版本号 / TTime Version：
0.9.7的安装包

- 问题描述 / Description of the issue：
![image](https://github.com/InkTimeRecord/TTime/assets/24737061/b143fb85-e2ae-4320-b21c-21800bcc53d5)

**Comment by ByLiangCheng** [comment]
问题重复，我们将会关闭此 issues，后续将会在 #272 进行回复，近期会看看这个问题的解决方案
