### ISSUE TITLE
源代码版本问题

### ISSUE THREAD

**Issue by SchneeHertz** [InkTimeRecord/TTime#275]
你好，我Fork了这个项目打算做一些更改，发现目前main分支的版本还是0.9.2，请问是新的代码还没有同步到这个repo中吗

**Comment by ByLiangCheng** [comment]
抱歉，开源以来考虑到贡献及发展问题，决定从0.9.2版本后不再继续开源，后续也会同步更新到 README.md，此仓库考虑作为收集问题使用

**Comment by SchneeHertz** [comment]
了解了
