### ISSUE TITLE
[Feature] 使用自己的 OpenAI API 做为 AI 应用的后端

### ISSUE THREAD

**Issue by uJZk** [InkTimeRecord/TTime#276]
**功能描述 / Function Description**
我希望可以使用自己的 OpenAI API 做为 AI 应用的后端。或者可以设置自定义的 Prompt。目前的官方提供的大概是 gpt 35，不足以胜任文字处理以外的任务。

**Comment by uJZk** [comment]
另外问一下，官方提供的后端是 gpt35 还是 gpt4。

**Comment by ByLiangCheng** [comment]
好的，已收到建议，我们会考虑一下方案 ~

**Comment by whz-pku** [comment]
> 好的，已收到建议，我们会考虑一下方案 ~

我觉得给自己的openapi，用自定义prompt的功能真的很需要

**Comment by kafkazov** [comment]
这个真的非常需要，开了会员之后发现没法用自己的API作为AI应用的后端，真的很奇怪。也就是说自定义了AI应用，然后必须充值官方的AI额度才能用。

**Comment by ByLiangCheng** [comment]
新版本已发布，功能已支持
