### ISSUE TITLE
[Feature] 百度OCR增加通用文字识别（高精度版）

### ISSUE THREAD

**Issue by petersb888** [InkTimeRecord/TTime#277]
**功能描述 / Function Description**
默认应该调用的是通用文字识别（标准版），但是感觉识别度一般，希望可以增加调用选项，让我们可以更加灵活的选择调用哪个

**Comment by ByLiangCheng** [comment]
好的，已收到建议，我们后续会考虑一下

不过百度的OCR应该效果挺不错的了吧，并且我们实际测试的时候发现效果几种不同的类型似乎并没有相差很远

**Comment by ByLiangCheng** [comment]
新版本已发布，功能已新增
