### ISSUE TITLE
[Feature] 观看视频被暂停

### ISSUE THREAD

**Issue by markvlenvision** [InkTimeRecord/TTime#283]
**功能描述 / Function Description**
在观看视频时（油管），选中视频底部的评论文字，使用快捷键翻译时，视频会被暂停。
建议：是否可以不被暂停，或者增加可选项配置。

系统环境 / System Environment：
Windows 10 专业版 22H2

TTime版本号 / TTime Version：
097

**Comment by ByLiangCheng** [comment]
你好，测试发现确实存在此问题，后续版本将会修复

**Comment by ByLiangCheng** [comment]
新版本已发布，问题已修复
