### ISSUE TITLE
[Feature] pdf多行去掉换行符问题

### ISSUE THREAD

**Issue by Mriew** [InkTimeRecord/TTime#284]
**功能描述 / Function Description**
从pdf选择多行内容翻译的时候能不能去掉换行符 还原成一句话 有点影响翻译效果 
![image](https://github.com/InkTimeRecord/TTime/assets/105431707/6d3df76b-e479-472a-bc28-53a616dde5af)

**Comment by ByLiangCheng** [comment]
你好，这种情况是在特定的软件内划词出现的吧？这种目前了解到的原因是由于特定软件中他们没有进行合并多段内容的原因，所以这里我们也无法判定是否为同一行

可以在设置 -> 高级设置 -> 文本处理 ( 将翻译结果的【换行符】替换为【空格】) 开启，这样翻译前会自动把换行符替换为空格，并进行翻译
