### ISSUE TITLE
[Feature] 自定义悬浮球位置

### ISSUE THREAD

**Issue by Xtscat** [InkTimeRecord/TTime#285]
**功能描述 / Function Description**

是否可以添加自定义悬浮球位置呢，有时候默认的位置会和一些软件的功能冲突。如图：

![image](https://github.com/InkTimeRecord/TTime/assets/56481656/3e2369d3-d5ae-48e2-8ba1-03ebda2f2606)

**Comment by ByLiangCheng** [comment]
收到，后续的版本会增加 ～

**Comment by ByLiangCheng** [comment]
新版本已发布，功能已支持
