### ISSUE TITLE
[Feature] 支持Ollama AI翻译

### ISSUE THREAD

**Issue by yanecc** [InkTimeRecord/TTime#288]
[Ollama](https://github.com/ollama/ollama)包含很多开源大语言模型，而且可以通过相同的API接口调用这些模型
希望能添加Ollama AI翻译源，这样可以在用户本地提供AI翻译服务。
由于大部分开源模型并未针对中文进行训练，同时希望增加设置Prompt的功能
以更好地手动优化翻译效果，及适用于其他需求

**Comment by yanecc** [comment]
这里是Ollama的API文档：https://github.com/ollama/ollama/blob/main/docs/api.md

**Comment by ByLiangCheng** [comment]
下个版本会加入

**Comment by ByLiangCheng** [comment]
新版本已发布，功能已新增
