### ISSUE TITLE
[BUG] 2.5k屏下面ocr模糊

### ISSUE THREAD

**Issue by jielansudo** [InkTimeRecord/TTime#289]
请提供下述完整信息以便快速定位问题 / Please provide the following information to quickly locate the problem

- 系统环境 / System Environment：
win11 

- TTime版本号 / TTime Version：
0.9.7

- 问题描述 / Description of the issue：
2.5K的屏幕，发现使用ocr识别  会导致屏幕模糊，特别是拉动的时候

**Comment by H3nryM4** [comment]
![image](https://github.com/InkTimeRecord/TTime/assets/53041402/4c6a1fb5-f125-4d0b-ab1f-9830f4f98790)

**Comment by ByLiangCheng** [comment]
问题已修复，新版本已发布
