### ISSUE TITLE
希望可以增加代理设置功能

### ISSUE THREAD

**Issue by ijunzhe** [InkTimeRecord/TTime#29]
![111](https://user-images.githubusercontent.com/24651716/229432775-6786de75-9118-403f-b575-910b1e32eca6.jpg)

**Comment by ByLiangCheng** [comment]
你好，目前的都为国内翻译源场景下需要代理设置吗？能描述下你的使用场景吗？

**Comment by ijunzhe** [comment]
在公司访问外网需要设置代理服务器。
麻烦大佬抽空增加这个功能，感谢！

**Comment by ByLiangCheng** [comment]
抱歉，没有太理解你指的“在公司访问外网需要设置代理服务器”的场景，能详细描述一下吗？

因为后续会加入Google等翻译源，如果电脑有使用代理工具，默认会走代理工具配置的代理
而直接加入这种整个应用代理配置，可能会对其他翻译源造成影响，所以需要详细描述一下场景后，我这边做一下评估

**Comment by gehate** [comment]
同问，可不可以加一个http或socks5代理功能，用到google和chatgpt翻译源，需要用代理工具，如何可以设置socks5代理，本地就不用开代理工具

**Comment by ByLiangCheng** [comment]
> 同问，可不可以加一个http或socks5代理功能，用到google和chatgpt翻译源，需要用代理工具，如何可以设置socks5代理，本地就不用开代理工具

你好，关于代理问题目前有计划开发，不过现在都是业余时间做的，得一点点加了

**Comment by ByLiangCheng** [comment]
此功能已增加，新版本已发布，如还有问题，请重新提交Issues

**Comment by PANLI77** [comment]
代理节点需要用户名和密码在哪里输入？
