### ISSUE TITLE
[Feature] 托盘图标中应用名称缺失

### ISSUE THREAD

**Issue by youlan2333** [InkTimeRecord/TTime#290]
**功能描述 / Function Description**
托盘图标中应用名称缺失
![image](https://github.com/InkTimeRecord/TTime/assets/64688148/c6257731-324c-42ec-b940-8a96744e024f)
![image](https://github.com/InkTimeRecord/TTime/assets/64688148/abc2cc0b-7ea9-4139-8c2c-7abce8bb193a)

**Comment by ByLiangCheng** [comment]
你好，请问一下这种情况是一直存在吗？还是偶发现象呢？有重启软件试过可以恢复吗？

**Comment by youlan2333** [comment]
> 你好，请问一下这种情况是一直存在吗？还是偶发现象呢？有重启软件试过可以恢复吗？

经过几天测试，问题没有复现
