### ISSUE TITLE
[BUG] 截图时，连接的另一台显示器显示的内容会异常放大，导致只能显示一部分，无法看清完整内容和截取内容

### ISSUE THREAD

**Issue by hongenzkk** [InkTimeRecord/TTime#291]
请提供下述完整信息以便快速定位问题 / Please provide the following information to quickly locate the problem

- 系统环境 / System Environment：
WIndows11

- TTime版本号 / TTime Version：
V0.9.7

- 问题描述 / Description of the issue：
- 连接的显示器页面显示的内容（这是用另一款截图软件PixPin截取的完整内容）：
![image](https://github.com/InkTimeRecord/TTime/assets/32128765/345ad8e2-bdf9-4831-a3d2-b7a3ba4e3b61)
当用TTime的截图功能时：
![image](https://github.com/InkTimeRecord/TTime/assets/32128765/bc805f06-e260-4aba-bf6c-11f2a0b72de6)
显示内容会异常放大，导致只能显示一部分，无法看清完整内容和截取内容

**Comment by ByLiangCheng** [comment]
你好，请问显示器分辨率是多少呢？有调整缩放比例后分辨率吗？

**Comment by hongenzkk** [comment]
主显示器是笔记本的，3120×2080，缩放比例200%，副显示器是1920*1080，显示比例100%。
也许有显示器缩放比例的问题，但在另一款截图软件PixPin上没有这个问题。。。

**Comment by ByLiangCheng** [comment]
> 主显示器是笔记本的，3120×2080，缩放比例200%，副显示器是1920*1080，显示比例100%。 也许有显示器缩放比例的问题，但在另一款截图软件PixPin上没有这个问题。。。

抱歉，目前我们已经排查出问题，是电脑有设置缩放比例的情况下出现的，将会在下个版本中将其修复

**Comment by hongenzkk** [comment]
好的好的，感谢修复，我会及时更新，谢谢！

**Comment by ByLiangCheng** [comment]
@hongenzkk 你好，可以提供一下你的联系方式到我们邮箱吗？我们想测试一下这个问题

我们邮箱是：support@timerecord.cn

**Comment by ByLiangCheng** [comment]
问题已修复，新版本已发布

可再次尝试 或 设置 -> 偏好设置 -> 截图类型 -> 系统截图
