### ISSUE TITLE
[BUG] 在远程桌面下被控电脑无法使用划词翻译

### ISSUE THREAD

**Issue by SantoGG** [InkTimeRecord/TTime#292]
请提供下述完整信息以便快速定位问题 / Please provide the following information to quickly locate the problem

- 系统环境 / System Environment：
Win11

- TTime版本号 / TTime Version：
0.9.7

- 问题描述 / Description of the issue：
1、使用远程软件Todesk操作被控电脑时，被控电脑无法通过划词翻译识别选定内容
2、被控电脑与控制端均装有TTime，已尝试关闭控制端TTime，被控电脑仍无法识别选定内容
![01](https://github.com/InkTimeRecord/TTime/assets/164522671/993bdb77-c9ef-4548-9a91-5d2f96477e05)

**Comment by ByLiangCheng** [comment]
你好，这个目前测试似乎是 todesk 的问题，我在用向日葵的时候好像没有出现这样的情况

**Comment by SantoGG** [comment]
感谢，我将尝试向todesk反馈问题
