### ISSUE TITLE
[BUG] 图片大引发的请求失败

### ISSUE THREAD

**Issue by yanecc** [InkTimeRecord/TTime#293]
![Large entity error](https://github.com/InkTimeRecord/TTime/assets/89304297/396f5554-8edb-4c5d-bcc3-007d9439ec85)

遇到了因图片大引发的错误，电脑屏幕16寸 2.5k，截图面积超过屏幕1/4左右就会引发错误。

**Comment by ByLiangCheng** [comment]
你好，测试确实存在此问题，近期将会修复 ～

**Comment by ByLiangCheng** [comment]
嗨喽你好，此问题已优化，我们调整了更大的空间，可以再试一下看看 @18183883296

**Comment by yanecc** [comment]
> 嗨喽你好，此问题已优化，我们调整了更大的空间，可以再试一下看看 @18183883296

现在全屏也可以了，这很好！👍
