### ISSUE TITLE
[BUG] 更新 0.9.8后ESC键不能关闭窗口

### ISSUE THREAD

**Issue by dddXzz** [InkTimeRecord/TTime#294]
请提供下述完整信息以便快速定位问题 / Please provide the following information to quickly locate the problem

- 系统环境 / System Environment：
Windows11

- TTime版本号 / TTime Version：
v0.9.8

- 问题描述 / Description of the issue：

**Comment by ByLiangCheng** [comment]
你好，目前测试确实存在部分情况下会导致，下个版本中将会修复

**Comment by CeivenLean** [comment]
> 你好，目前测试确实存在部分情况下会导致，下个版本中将会修复

开发者您好，我知道对于开源软件来讲 催作者更新是绝对不对的，但是这个软件也有付费功能，因此作为付费用户 我希望您能对已知的bug尽快修复，或者出一个更新计划时间，谢谢。如果您对于我这次修复请求感到冒犯，请告知，我不会再提出任何请求了，对不起。

**Comment by ByLiangCheng** [comment]
> > 你好，目前测试确实存在部分情况下会导致，下个版本中将会修复
> 
> 开发者您好，我知道对于开源软件来讲 催作者更新是绝对不对的，但是这个软件也有付费功能，因此作为付费用户 我希望您能对已知的bug尽快修复，或者出一个更新计划时间，谢谢。如果您对于我这次修复请求感到冒犯，请告知，我不会再提出任何请求了，对不起。

实在抱歉，前段时间因为有些事情给耽误了，我们近期的几天内将会发版新的版本，如果您认为这个问题对你的影响很大的话可以联系我们，我们发一个内测包给您

同时，不必感到抱歉，这个确实是我们的问题，我们也非常重视和欢迎大家提出的请求及建议，后续也欢迎继续反馈

**Comment by ByLiangCheng** [comment]
新版本已发布，问题已修复
