### ISSUE TITLE
图片翻译窗口无法操作

### ISSUE THREAD

**Issue by yanecc** [InkTimeRecord/TTime#295]
在`0.9.8`版本的图片翻译窗口中任意点击都会导致窗口关闭，必须固定窗口才能使用各项功能。
希望得到修复，能够像翻译窗口那样拖动及执行各项操作

**Comment by ByLiangCheng** [comment]
你好，目前测试发现是显示器有设置缩放比例的问题会导致，调整回 100 后就没问题了，下个版本中将会修复此问题

**Comment by ByLiangCheng** [comment]
新版本已发布，问题已修复
