### ISSUE TITLE
[BUG] Mac将翻译窗口放大后不能缩小

### ISSUE THREAD

**Issue by JandyLi** [InkTimeRecord/TTime#297]
请提供下述完整信息以便快速定位问题 / Please provide the following information to quickly locate the problem

- 系统环境 / System Environment：Mac os 

- TTime版本号 / TTime Version：v0.9.8

- 问题描述 / Description of the issue：Mac将翻译窗口放大后不能缩小

**Comment by ByLiangCheng** [comment]
你好，指的是把窗口宽度调整后设置不回去吗？

**Comment by JandyLi** [comment]
对的

**Comment by ByLiangCheng** [comment]
鼠标再翻译窗口右上角调整没有反应吗？方便提供一个演示吗？我这边测试目前看好像是没有问题

**Comment by JandyLi** [comment]
https://github.com/InkTimeRecord/TTime/assets/151015519/c32be949-9c02-47ae-98ae-d8411e229ddb

快捷键 COMMAND - 并不能将窗口缩小，而COMMAND + 能够将窗口放大，只能将登陆日志删除

**Comment by ByLiangCheng** [comment]
> 2024-04-10_08-13-54.mp4 
> 快捷键 COMMAND - 并不能将窗口缩小，而COMMAND + 能够将窗口放大，只能将登陆日志删除

抱歉，理论上窗口是不支持这种方式的放大和缩小，这或许是个bug，后续会禁用此方式，建议可以通过拖拽拉伸的形式

**Comment by ByLiangCheng** [comment]
新版本已发布，问题已修复
