### ISSUE TITLE
划词翻译 windows 11 失效

### ISSUE THREAD

**Issue by amsz** [InkTimeRecord/TTime#3]
系统信息：Windows 11 专业版 22H2 22621.1344

无法获取选中的内容

**Comment by ByLiangCheng** [comment]
“无法获取选择中的内容 ”指的是划词失败吗？

**Comment by amsz** [comment]
是的，按下划词快捷键后，弹出的翻译主界面，只出现粘贴板中的内容，而不是选中的内容

**Comment by ByLiangCheng** [comment]
这个目前部分设备是有存在这个问题，正在寻找解决方案，后续版本会想办法解决

**Comment by ByLiangCheng** [comment]
此问题已修复，新版本已发布，如还有问题，请重新提交Issues
