### ISSUE TITLE
[BUG] 朗读语音不会关闭

### ISSUE THREAD

**Issue by markvlenvision** [InkTimeRecord/TTime#301]
请提供下述完整信息以便快速定位问题 / Please provide the following information to quickly locate the problem

- 系统环境 / System Environment：
Windows 10 专业版 22H2

- TTime版本号 / TTime Version：
098

- 问题描述 / Description of the issue：
翻译长句子使用朗读时，翻译窗口失去焦点关闭后，朗读的语音仍在后台朗读。
个人认为在显示窗口关闭后，朗读应该停止，在固定显示窗口，才保持一直朗读直至结束。

**Comment by ByLiangCheng** [comment]
你好，测试确实存在这种情况，我们记录一下近期修改

**Comment by ByLiangCheng** [comment]
新版本已发布，问题已修复
