### ISSUE TITLE
[BUG] 语音播放源 ttime只能外放

### ISSUE THREAD

**Issue by CatAndBeer** [InkTimeRecord/TTime#302]
请提供下述完整信息以便快速定位问题 / Please provide the following information to quickly locate the problem

- 系统环境 / System Environment：

win11 22h3
- TTime版本号 / TTime Version：

0.9.8
- 问题描述 / Description of the issue：
高级设置里的语音播放源选默认的TTime的话语音不能在耳机里面播放，只能外放，网易的没问题

**Comment by ByLiangCheng** [comment]
指的是笔记本上使用默认的 TTime 语音播放时，带上耳机就没有声音，而拔下耳机就有声音吗？

**Comment by CatAndBeer** [comment]
对，笔记本，但是声音一直有，只是不管带不带耳机都只从扬声器播放，耳机没有声音。切换到有道语音就是正常的没问题

**Comment by ByLiangCheng** [comment]
有尝试调整电脑的 默认播放设备设置 吗？我这边测试似乎是正常的

**Comment by CatAndBeer** [comment]
在电脑系统切换输出设备的话，不是使用当前选择的输出设备进行播放，似乎是列表中选中的上一个设备在播放。用有道源没有问题

**Comment by ByLiangCheng** [comment]
> 在电脑系统切换输出设备的话，不是使用当前选择的输出设备进行播放，似乎是列表中选中的上一个设备在播放。用有道源没有问题

是说发现电脑系统用 TTime 的播放源播放时，电脑系统播放的设备默认选择的还是上一次的设备播放，没有自动切换？而用有道的就自动切换了？

尝试使用其他软件有过类似的情况吗？

**Comment by ByLiangCheng** [comment]
由于长时间未回复，issues 关闭
