### ISSUE TITLE
[BUG] 当翻译源为Ocr Space时，将OCR结果的[换行符]替换为[空白]/[空格]两项设置未生效

### ISSUE THREAD

**Issue by yanecc** [InkTimeRecord/TTime#304]
- 系统环境 / System Environment：
Win11

- TTime版本号 / TTime Version：
0.9.8

- 问题描述 / Description of the issue：
当翻译源为Ocr Space时，
开启`将OCR结果的[换行符]替换为[空白]`，换行符仍存在，设置未生效；
开启`将OCR结果的[换行符]替换为[空格]`，会在换行处第二行首增加一空格，换行符仍存在。

    使用其他OCR源时，该两项设置工作正常。

**Comment by ByLiangCheng** [comment]
你好，确实存在此问题，下个版本中将会修复

**Comment by ByLiangCheng** [comment]
新版本已发布，问题已修复
