### ISSUE TITLE
[Feature] 强烈希望可以添加多窗口功能

### ISSUE THREAD

**Issue by 573523145** [InkTimeRecord/TTime#305]
简单说就是可以同时存在多个窗口翻译不同的内容
比如翻译了一篇文章,但是希望保留这份翻译,再去翻译其他内容进行对比
现在是只能有一个翻译窗口,当想要翻译新内容时,上一个翻译的内容就会消失,只能去历史中查看

我建议加一个选项,在用户选择固定窗口后,再进行的新翻译就在新的窗口中翻译,被固定的窗口就留存下来,通过esc或者取消固定来让其关闭

强烈建议加一个这个功能, 大大提高生产力和学习效率

**Comment by ByLiangCheng** [comment]
这个建议查看历史就可以了吧，存在这种场景的用户似乎并不多，专门适配多窗口很麻烦
