### ISSUE TITLE
[Feature] 希望有音标功能

### ISSUE THREAD

**Issue by emako** [InkTimeRecord/TTime#308]
**功能描述 / Function Description**
不知道能不能做到，显示发音音标

![image](https://github.com/InkTimeRecord/TTime/assets/24737061/d0ce6117-7d9d-4d89-971c-2bde4e854560)

**Comment by ByLiangCheng** [comment]
你好，bing词典之前似乎是有的，我们排查一下

也可以考虑使用一下 “简明英汉词典(离线)” 也是有显示音标的
