### ISSUE TITLE
A JavaScript error occurred in the main process.  

### ISSUE THREAD

**Issue by bubbletg** [InkTimeRecord/TTime#31]
官网下载最新的报错：
![image](https://user-images.githubusercontent.com/46395997/229825784-59e37a20-efc2-4a81-ae9e-83bcabe9bb30.png)

**Comment by ByLiangCheng** [comment]
你好，感谢反馈

这个问题是因为电脑缺少驱动导致的，目前是更新下电脑驱动可以解决

后面版本会研究一下这个问题看能不能在安装时解决

**Comment by bubbletg** [comment]
大佬，缺了啥驱动？昨天安装一些软件后，莫名其妙好了。

**Comment by ByLiangCheng** [comment]
目前也有其他用户遇到这种情况的，当下解决方法是安装类似微软常用运行库之类的就好了

猜测可能你安装的部分软件自带安装了这些运行库所以可以了

**Comment by ByLiangCheng** [comment]
此问题已修复，新版本已发布，如还有问题，请重新提交Issues
