### ISSUE TITLE
[BUG] OCR识别效果变差

### ISSUE THREAD

**Issue by anatoliux2233** [InkTimeRecord/TTime#310]
请提供下述完整信息以便快速定位问题 / Please provide the following information to quickly locate the problem

- 系统环境 / System Environment：
Windows 10 企业版 LTSC 21H2

- TTime版本号 / TTime Version：
0.9.8

- 问题描述 / Description of the issue：
在一月份的版本中截图识别俄文准确度高，工作中使用很有帮助，而新版本出现两个问题：
1.识别精度下降，字母丢失，空格丢失
![微信截图_20240416202139](https://github.com/InkTimeRecord/TTime/assets/38915367/f360eb62-e65b-4516-9f11-43c37fcf76f1)
2.在语言设置中已经设定为俄语和简体中文，但图像识别总是识别为英语
![微信截图_20240416202925](https://github.com/InkTimeRecord/TTime/assets/38915367/5483dfb8-8c6b-414a-8267-6e68bb260f13)

请作者大大帮忙改进，谢谢！

**Comment by ByLiangCheng** [comment]
你好，我回答一下

1.一月份的时候内置的文字识别似乎还不支持俄语，当时你是否在文字识别设置中开启的是第三方呢？
2.截图的文字识别的语言不是在翻译界面设置的，翻译界面的语言是识别的输入框中的语言，而文字识别的语言需要你在“设置” -> "翻译源设置" -> “文字识别” -> 选择对应翻译源配置俄语
