### ISSUE TITLE
[BUG] 在vscode中会出现识别内容为空，监听剪切板也无效。

### ISSUE THREAD

**Issue by thornboo** [InkTimeRecord/TTime#311]
请提供下述完整信息以便快速定位问题 / Please provide the following information to quickly locate the problem

- 系统环境 / System Environment：
windows10

- TTime版本号 / TTime Version：
0.9.8

- 问题描述 / Description of the issue：
在vscode中会出现识别内容为空，监听剪切板也无效。
![image](https://github.com/InkTimeRecord/TTime/assets/73095523/29404c2b-07a5-411f-80f1-1d62fd142677)

**Comment by ByLiangCheng** [comment]
你好，我们检查一下，似乎这个问题目前只在部分电脑上出现

**Comment by 0x132406C** [comment]
我也是这样,不止是vscode,都会识别为空,我的系统是Win10专业版 22H2

**Comment by ByLiangCheng** [comment]
> 我也是这样,不止是vscode,都会识别为空,我的系统是Win10专业版 22H2

你这种情况在 设置 -> 偏好设置 -> 划词默认前后延迟 的值调大一些后看看能不能正常划词

**Comment by 0x132406C** [comment]
> > 我也是这样,不止是vscode,都会识别为空,我的系统是Win10专业版 22H2
> 
> 你这种情况在 设置 -> 偏好设置 -> 划词默认前后延迟 的值调大一些后看看能不能正常划词

很奇怪,现在就算是默认的划词延迟他也能翻译了,似乎不是固定会出现这个问题

**Comment by 0x132406C** [comment]
> > 我也是这样,不止是vscode,都会识别为空,我的系统是Win10专业版 22H2
> 
> 你这种情况在 设置 -> 偏好设置 -> 划词默认前后延迟 的值调大一些后看看能不能正常划词

现在又出现这个问题了,在翻译youtube评论的时候,延迟拉到1000ms也没用,但是我估计重启之后就会好,我试试

**Comment by 0x132406C** [comment]
> > 我也是这样,不止是vscode,都会识别为空,我的系统是Win10专业版 22H2
> 
> 你这种情况在 设置 -> 偏好设置 -> 划词默认前后延迟 的值调大一些后看看能不能正常划词

电脑重启之后就没问题了,我现在再试试,看看能不能复现

**Comment by asdlaowu** [comment]
![123131](https://github.com/InkTimeRecord/TTime/assets/169012607/0a6d09f2-1a0a-47af-8824-091c918a9b5c)
这个有大佬知道咋解决不

**Comment by ByLiangCheng** [comment]
> ![123131](https://private-user-images.githubusercontent.com/169012607/334687007-0a6d09f2-1a0a-47af-8824-091c918a9b5c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5ODM1OTcsIm5iZiI6MTcxNjk4MzI5NywicGF0aCI6Ii8xNjkwMTI2MDcvMzM0Njg3MDA3LTBhNmQwOWYyLTFhMGEtNDdhZi04ODI0LTA5MWM5MThhOWI1Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyOVQxMTQ4MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZjBiOGMxYTM1NTNiYWU5NzRhMWM0OTdiMWExMjYxOGM3NmRkZWUwOWEzMzBmODNkZjE1NDNmYThhY2UwOTA0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PMAbQIS8omQE7M55lB33Ug9ByJOKgUX-rX867Y_9Z7s) 这个有大佬知道咋解决不

1.在设置 -> 偏好设置 -> 划词默认前后延迟 的值调大一些后看看能不能正常划词
2.如果是在浏览器中划词失败 , 请检查是否有插件冲突
3.windows 环境下是否有使用工具修改过系统快捷键
