### ISSUE TITLE
[Feature] 翻译结果出来后自动复制译文

### ISSUE THREAD

**Issue by suibianzai** [InkTimeRecord/TTime#312]
**功能描述 / Function Description**
开发者好！是否可以增加这样一个功能：翻译原文输入翻译框，译文输出之后，自动复制译文，或者增加一个复制译文的快捷键，目的是整个工作流减少用到鼠标的次数，手可以尽量留在键盘上，提高效率。如果配合https://github.com/InkTimeRecord/TTime/issues/151 这个功能，甚至不用按alt+tab切换窗口。
不过“复制译文”可能要注意和剪贴板监听的功能进行区分https://github.com/InkTimeRecord/TTime/issues/286 否则容易出现冲突。

这个功能在其他同类产品上我有看到过，但是在TTime上我找了半天没找到，不知道是我眼拙，还是真的没有。如果能考虑增加，非常感谢！

**Comment by ByLiangCheng** [comment]
你好，感谢建议，后续会增加自动复制第一个翻译源结果到剪贴板的配置

**Comment by suibianzai** [comment]
> 你好，感谢建议，后续会增加自动复制第一个翻译源结果到剪贴板的配置

谢谢回复！我刚刚还突然想到，如果可以静默翻译，加上直接复制第一个翻译源结果，都不用考虑切窗口了🤣 不过这也只是其中一种场景。再次谢谢你们考虑采纳我的建议~

**Comment by ByLiangCheng** [comment]
> > 你好，感谢建议，后续会增加自动复制第一个翻译源结果到剪贴板的配置
> 
> 谢谢回复！我刚刚还突然想到，如果可以静默翻译，加上直接复制第一个翻译源结果，都不用考虑切窗口了🤣 不过这也只是其中一种场景。再次谢谢你们考虑采纳我的建议~

了解，这种情况下直接使用替换翻译即可

**Comment by ByLiangCheng** [comment]
新版本已发布，功能已新增
