### ISSUE TITLE
[Feature] 窗口大小（宽度）可调的功能

### ISSUE THREAD

**Issue by w87164951** [InkTimeRecord/TTime#313]
**功能描述 / Function Description**
在目前的使用过程中，发现翻译的窗口的大小是不可调整的。

如果翻译的内容较长时，想要把窗口调大时，就无法实现。

希望能优化一下，实现窗口能通过拖拉的方式调整其大小，尤其是宽度。

**Comment by ByLiangCheng** [comment]
你好，现在是支持的，你把鼠标放在翻译窗口的右上角进行调整即可

**Comment by w87164951** [comment]
谢谢回复，问题已解决


---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年4月22日 06:24 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [InkTimeRecord/TTime] [Feature] 窗口大小（宽度）可调的功能 (Issue #313) |

你好，现在是支持的，你把鼠标放在翻译窗口的右上角进行调整即可

**Comment by NY-WaKeUp** [comment]
@ByLiangCheng 您好，可否增大窗口宽度可调的范围？个人使用起来觉得现在最小也很宽。
