### ISSUE TITLE
[BUG] 在Youtube上暂停视频使用划词翻译评论时会导致视频播放

### ISSUE THREAD

**Issue by 0x132406C** [InkTimeRecord/TTime#315]
TTime 0.9.8

有时候看视频会先暂停视频然后用划词翻译来翻译下面的评论,但是会导致视频停止暂停并播放.
跟快捷键是什么没有关系,不管绑到什么按键上都会这样.

**Comment by ByLiangCheng** [comment]
你好，已经有 #283 重复问题了，我们后续将会修复

**Comment by ByLiangCheng** [comment]
新版本已发布，问题已修复
