### ISSUE TITLE
[Feature] 希望点击切换语言时能自动重新翻译

### ISSUE THREAD

**Issue by gptzm** [InkTimeRecord/TTime#316]
**功能描述 / Function Description**
现在设置【中翻英】并划词搜索英文语句后，点击切换按钮改成【英翻中】，但是下方的翻译框不会立即变化，需要在输入框中输入任意内容才会重新翻译，比较不流畅。
希望点击切换语言时能自动重新翻译。

**Comment by ByLiangCheng** [comment]
你好，我们下个版本更新进去

**Comment by ByLiangCheng** [comment]
功能已增加，版本已发布
