### ISSUE TITLE
[Feature] 增加美式发音音标，在简明英汉词典中

### ISSUE THREAD

**Issue by Nitmi** [InkTimeRecord/TTime#317]
**功能描述 / Function Description**
在简明英汉词典中，增加美式发音音标。

**一个疑惑**
为何有道翻译似乎在最近的一次的更新后，翻译结果不再是以词典条目的形式（单词、英音、美音、各种释义、复数、过去式等）输出了，而仅仅是一个释义。

TTime 很好用，感谢开发者的辛苦开发。

**Comment by ByLiangCheng** [comment]
有道原翻译接口不再提供词典信息了，可以使用其他词典翻译源，简明英汉词典我们后续了解一下看看 ～

**Comment by fajianren** [comment]
希望在翻译结果中增加英文的音标

**Comment by Nitmi** [comment]
能否支持更多的离线词典呢？（词汇量更大，有英音、美音音标）


## 建议支持 AI翻译自定义提示词Prompt
或者能否支持 **AI翻译自定义提示词Prompt** 呢，以下是使用一个词典Prompt进行单词查询的示例，可以看到效果是非常好的，而且支持自定义Prompt之后，用户可以很方便地自定义单词查询结果的格式。这将是一个很好的体验点，可以 TTime 的竞争力，非常建议开发者考虑一下。
![image](https://github.com/InkTimeRecord/TTime/assets/114425147/64320f6a-ce5a-445c-a926-9be4aafd28c8)

**Comment by ByLiangCheng** [comment]
当前可在设置 -> 翻译源设置 选择翻译源后，可以对应选择开启显示词典
