### ISSUE TITLE
[BUG] macOS 系统设置了多个桌面时，使用 option+E 翻译会跳转到别的桌面打开翻译窗口。

### ISSUE THREAD

**Issue by arthurqiao** [InkTimeRecord/TTime#318]
请提供下述完整信息以便快速定位问题 / Please provide the following information to quickly locate the problem

- 系统环境 / System Environment：
macOS Sonoma 版本14.4.1 (23E224)
芯片：Apple M2 Pro

- TTime版本号 / TTime Version：
0.9.9

- 问题描述 / Description of the issue：
macOS 系统设置了多个桌面时，使用 option+E 翻译会跳转到别的桌面打开翻译窗口，而不是在当前桌面打开翻译窗口。这个bug在最早在 2023 年 6 月份购买 MacBook 时就发现了，随着版本一直更新到 0.9.9 依然存在。

**Comment by ByLiangCheng** [comment]
你好，翻译窗口近期会尽量支持进去，现在图片翻译和静默识别已经支持了

**Comment by aishuaikang** [comment]
![recording](https://github.com/user-attachments/assets/856d0033-2596-45a6-8796-6612e04f7a32)
期望的是在当前全屏桌面之上打开翻译窗口，而不是跳转到空闲桌面，这是一个优化的点

**Comment by aishuaikang** [comment]
![recording](https://github.com/user-attachments/assets/b0f77f85-73e2-4f72-a896-96b1680e7cf0)
这是某翻译工具的打开效果

**Comment by yelan** [comment]
是的这个问题非常非常烦人，想弃了～

**Comment by ByLiangCheng** [comment]
新版本已发布，功能已支持

可以在设置 -> 偏好设置 -> 开启 静默显示窗口
