### ISSUE TITLE
[Feature] 请问怎么给snip.do增加扩展插件来调用划词？

### ISSUE THREAD

**Issue by ceozero** [InkTimeRecord/TTime#319]
**功能描述 / Function Description**
已经习惯了snip.do来划词了，之前bob和pot都有配套插件来调用。TTime找了半天没看到接口。

pot用的扩展是直接调用powershell 来呼出窗口的。
`
$encode_text = [System.Text.Encoding]::UTF8.GetBytes($PLAIN_TEXT)

curl 127.0.0.1:60828/translate -Method POST -Body $encode_text -UseBasicParsing
`
![image](https://github.com/InkTimeRecord/TTime/assets/22513657/c499e62b-7fc5-4318-8c2a-1b48eb193eaf)
![image](https://github.com/InkTimeRecord/TTime/assets/22513657/b62e41e1-090a-44cd-8c1a-1c1499ea6a9a)
![image](https://github.com/InkTimeRecord/TTime/assets/22513657/d39593eb-c44f-4e6c-9e04-ce02d726685a)

**Comment by ByLiangCheng** [comment]
你好，下个版本将会支持接口调用

**Comment by ByLiangCheng** [comment]
已新增插件支持，下载 [TTime.pbar](https://github.com/InkTimeRecord/TTime/releases/download/v0.9.10/TTime.pbar) 安装即可

**Comment by uniquMonte** [comment]
这个功能我之前期待挺久了，谢谢提供此功能。试用了一下，有时候会卡住，就是在snip上点了，没有调出来翻译窗口。总体还可以

**Comment by ByLiangCheng** [comment]
> 这个功能我之前期待挺久了，谢谢提供此功能。试用了一下，有时候会卡住，就是在snip上点了，没有调出来翻译窗口。总体还可以

如果有问题，可以创建一个issues，录个视频看看哈，我们排查一下原因
