### ISSUE TITLE
划词翻译识别内容慢

### ISSUE THREAD

**Issue by zdh119** [InkTimeRecord/TTime#32]
环境：windows10
版本：0.0.5
问题：划词进行翻译时，操作过快会导致无法识别选中内容，而是翻译剪贴板中的内容，比较影响体验。

**Comment by ByLiangCheng** [comment]
你好，感谢反馈，这个目前部分机型上是存在这个问题，正在寻找解决方案中

**Comment by ByLiangCheng** [comment]
此问题已修复，新版本已发布，如还有问题，请重新提交Issues
