### ISSUE TITLE
[BUG] 有时候截图翻译识别不出空格

### ISSUE THREAD

**Issue by Aiviokoo** [InkTimeRecord/TTime#320]
请提供下述完整信息以便快速定位问题 / Please provide the following information to quickly locate the problem

- 系统环境 / System Environment：macOS Sonoma Version 14.4.1（mac mini m2）

- TTime版本号 / TTime Version：0.9.9

- 问题描述 / Description of the issue：
![image](https://github.com/InkTimeRecord/TTime/assets/87182333/d885ab9f-8971-4f91-ae2f-c44ccc5f7614)

**Comment by ByLiangCheng** [comment]
你好，目前这种情况可以在设置中切换文字识别语言为英文可以解决，后续我们会优化
