### ISSUE TITLE
[BUG] 没法基于openai api定义prompt，非常不方便，窗口跟随鼠标时会移出屏幕，应当加以限制

### ISSUE THREAD

**Issue by whz-pku** [InkTimeRecord/TTime#322]
请提供下述完整信息以便快速定位问题 / Please provide the following information to quickly locate the problem

- 系统环境 / System Environment：windows

- TTime版本号 / TTime Version：最新版本

- 问题描述 / Description of the issue：两个问题：1是没法基于openai api定义prompt，非常不方便，希望能开放这个功能，2是窗口跟随鼠标时会移出屏幕，应当加以限制

**Comment by ByLiangCheng** [comment]
这两个问题已存在 #192 #276
