### ISSUE TITLE
[BUG] Error:文字识别失败，请重试

### ISSUE THREAD

**Issue by HenryLau0220** [InkTimeRecord/TTime#323]
请提供下述完整信息以便快速定位问题 / Please provide the following information to quickly locate the problem

- 系统环境 / System Environment：
Windows 10 专业版 22H2

- TTime版本号 / TTime Version：
0.9.10

- 问题描述 / Description of the issue：
文字识别失败
![image](https://github.com/InkTimeRecord/TTime/assets/70014887/73c78d84-f174-4b90-b654-81bc72b681e7)

**Comment by ByLiangCheng** [comment]
你好，麻烦在电脑的右下角找到TTime图标，然后鼠标右键点击查看日志把最新的日志文件发送到邮箱：support@timerecord.cn
，我们看看报错信息
