### ISSUE TITLE
[BUG] 火山翻译无法翻译

### ISSUE THREAD

**Issue by sitdownkevin** [InkTimeRecord/TTime#324]
请提供下述完整信息以便快速定位问题 / Please provide the following information to quickly locate the problem

- 系统环境 / System Environment：

Windows 11 家庭中文版
23H2

- TTime版本号 / TTime Version：

0.9.10

- 问题描述 / Description of the issue：

使用火山翻译时出现：Cannot read properties of undefined (reading '0')

![image](https://github.com/InkTimeRecord/TTime/assets/77308378/4013ed4e-436d-428f-bdd5-d783434237d6)

**Comment by ByLiangCheng** [comment]
你好，麻烦在电脑的右下角找到TTime图标，然后鼠标右键点击查看日志，把对应错误发生的日期的日志文件发送到邮箱：[support@timerecord.cn](mailto:support@timerecord.cn)
，我们看看报错信息

**Comment by ByLiangCheng** [comment]
由于长时间未回复，Issues 关闭
