### ISSUE TITLE
[BUG] 小牛翻译无法验证 AppKey

### ISSUE THREAD

**Issue by sitdownkevin** [InkTimeRecord/TTime#325]
请提供下述完整信息以便快速定位问题 / Please provide the following information to quickly locate the problem

- 系统环境 / System Environment：

Windows 11家庭中文版
23H2

- TTime版本号 / TTime Version：

0.9.10

- 问题描述 / Description of the issue：

添加小牛翻译时出现验证失败。同样的 AppKey 放在其他软件中可以使用，排除 AppKey 输入错误的问题。

![image](https://github.com/InkTimeRecord/TTime/assets/77308378/08073693-ea99-467a-8f6e-94d68078673b)

**Comment by ByLiangCheng** [comment]
你好，麻烦在电脑的右下角找到TTime图标，然后鼠标右键点击查看日志，把对应错误发生的日期的日志文件发送到邮箱：[support@timerecord.cn](mailto:support@timerecord.cn)
，我们看看报错信息

**Comment by ByLiangCheng** [comment]
小牛翻译的请求错误日志已收到

参考一下这个看看是否能解决 ：https://ttime.v1.timerecord.cn/pages/9cc27d/#_3-%E8%BF%91%E6%9C%9F-ttime-%E8%B0%83%E7%94%A8%E6%8F%90%E7%A4%BA%E5%A4%B1%E8%B4%A5%E9%97%AE%E9%A2%98

**Comment by ByLiangCheng** [comment]
由于长时间未回复，Issues 关闭
