### ISSUE TITLE
[BUG] 更新后开机自启会关闭问题

### ISSUE THREAD

**Issue by xxuun** [InkTimeRecord/TTime#326]
请提供下述完整信息以便快速定位问题 / Please provide the following information to quickly locate the problem

- 系统环境 / System Environment：
Windows 11 专业版

- TTime版本号 / TTime Version：
0.9.10

- 问题描述 / Description of the issue：
每次更新以后，设置里的自动启动就变成关闭了

**Comment by ByLiangCheng** [comment]
你好，这个情况只会在更新的时候出现吗？方便测试下，看看手动下载安装包，覆盖安装时也会这样不？

**Comment by xxuun** [comment]
> 你好，这个情况只会在更新的时候出现吗？方便测试下，看看手动下载安装包，覆盖安装时也会这样不？

是的，我一会试下

**Comment by Mizro-wu** [comment]
情况一样，只要更新就会出现，最近几个版本都会

**Comment by ByLiangCheng** [comment]
> 你好，这个情况只会在更新的时候出现吗？方便测试下，看看手动下载安装包，覆盖安装时也会这样不？

@Mizro-wu 可以尝试下这个吗？

**Comment by xxuun** [comment]
![image](https://github.com/InkTimeRecord/TTime/assets/160392679/a5e9f66f-b16d-4d79-99b2-a6c72be5ee8f)
下载安装包覆盖安装会有开机自启的选项，勾选了就有，不勾选就没有

**Comment by ByLiangCheng** [comment]
@xxuun 如果你设置中是开启自启的状态时候，然后再重新覆盖安装，默认是勾选的状态吗？

**Comment by xxuun** [comment]
> @xxuun 如果你设置中是开启自启的状态时候，然后再重新覆盖安装，默认是勾选的状态吗？

默认是勾选的

**Comment by ByLiangCheng** [comment]
收到，我这边尝试复现一下看看

**Comment by ByLiangCheng** [comment]
新版本已发布，问题已修复，将会在下一个版本更新开始生效

**Comment by xxuun** [comment]
> 新版本已发布，问题已修复，将会在下一个版本更新开始生效

感谢回复
