### ISSUE TITLE
[BUG] 截图翻译窗口关闭问题

### ISSUE THREAD

**Issue by DreammStill** [InkTimeRecord/TTime#327]
请提供下述完整信息以便快速定位问题 / Please provide the following information to quickly locate the problem

- 系统环境 / System Environment：
Win11

- TTime版本号 / TTime Version：
0.9.10

- 问题描述 / Description of the issue：
截图翻译窗口如果不钉选将无法操作,点击无论点击哪里都会自动关闭,钉选了又不能手动关闭,不像应用主窗口那样点击窗口外部才会关闭,亟需修复,很搞人心态

**Comment by ByLiangCheng** [comment]
指的是图片翻译窗口吧？这个情况是部分电脑显示器修改了缩放比例的情况下出现的，下个版本会修复

**Comment by ByLiangCheng** [comment]
新版本已发布，问题已修复
