### ISSUE TITLE
[Feature] 需要一个快捷键功能——> 快速复制 翻译内容、翻译结果

### ISSUE THREAD

**Issue by zhz-we** [InkTimeRecord/TTime#328]
**功能描述 / Function Description**

如下图的功能，就能新增一个快捷键吗？ 一键复制 翻译内容、翻译结果，不然 手还要离开键盘区碰鼠标...
![image](https://github.com/InkTimeRecord/TTime/assets/42529417/3e0ef619-5799-4174-a750-e17c8adcac3a)

**Comment by ByLiangCheng** [comment]
首个翻译结果自动写入剪贴板的配置有支持的，这个功能意义似乎也不大，专门用快捷键的方式暂不考虑了，现有快捷键已经够多了
