### ISSUE TITLE
[BUG] 使用内置DeepL翻译源时，显示查询频率受限

### ISSUE THREAD

**Issue by SantoGG** [InkTimeRecord/TTime#329]
请提供下述完整信息以便快速定位问题 / Please provide the following information to quickly locate the problem

- 系统环境 / System Environment：
台式PC，Win11

- TTime版本号 / TTime Version：
0.9.10

- 问题描述 / Description of the issue：
使用划词翻译或输入翻译时，内置DeepL翻译间歇性无法翻译内容，如附件显示，此前未出现过类型情况，不确定是什么问题
![DeepL](https://github.com/InkTimeRecord/TTime/assets/164522671/ae02f53c-06f9-46ea-b603-b9729426f18c)

**Comment by uniquMonte** [comment]
估计是用的人多了吧

**Comment by gsvuo** [comment]
经常出现这种情况，希望可以自定义DeepL翻译源，自行填写自建的网址。

**Comment by ByLiangCheng** [comment]
DeepL 没有配置 Key 的情况下频繁请求就会这样

**Comment by gsvuo** [comment]
> DeepL 没有配置 Key 的情况下频繁请求就会这样

如果能设置自定义的DeepLX的API URL就能解决这个问题，沉浸式翻译用自己配置的DeepLX每秒几十次的请求都能丝滑的翻译网页，不需要用到DeepL官方的key。

**Comment by uniquMonte** [comment]
确实，如果能像bob一样可以配置DeepLX，那就perfect了

> > DeepL 没有配置 Key 的情况下频繁请求就会这样
> 
> 如果能设置自定义的DeepLX的API URL就能解决这个问题，沉浸式翻译用自己配置的DeepLX每秒几十次的请求都能丝滑的翻译网页，不需要用到DeepL官方的key。

**Comment by DreammStill** [comment]
确实，我用有官方的API，完全可以自己配置

**Comment by ByLiangCheng** [comment]
新版本已发布，功能已支持
