### ISSUE TITLE
[BUG] "贴图翻译"功能中"截图识别"出现问题  等

### ISSUE THREAD

**Issue by DreammStill** [InkTimeRecord/TTime#330]
请提供下述完整信息以便快速定位问题 / Please provide the following information to quickly locate the problem

- 系统环境 / System Environment：
Win11Pro

- TTime版本号 / TTime Version：
0.9.12

- 问题描述 / Description of the issue：
1.贴图翻译中打开"译图"关闭"显示文字"、"翻译结果"时,使用"截图识别"时只识别文字不会触发翻译,需要点击再次识别后才会触发翻译,"粘贴图片识别"功能正常
2.在主界面翻译栏回车不会触发翻译,只有修改才会触发翻译,希望可以添加按回车重新翻译(因为OPENAI翻译不稳定,有时候答非所问需要重新翻译)
3.每次更新都提示我的DLL库异常然后给我弹出C++运行库的安装,但实际上我通过DirectX Repair检查并没有发现问题,不知是什么原因

**Comment by ByLiangCheng** [comment]
1.可以提供一下视频演示吗？
2.是不是开启了 设置 -> 高级设置 -> 输入自动翻译
3.这个算是 BUG，下个版本会修复

**Comment by DreammStill** [comment]
谢谢,输入自动翻译是个挺好用的功能,能否考虑一下开启这个功能依旧保留回车翻译逻辑呢?
这是问题1的视频演示,目前在我这里100%复现
链接: https://pan.baidu.com/s/1zCuFg3o16epmUIG6Fop-aQ?pwd=1234 提取码: 1234 复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by ByLiangCheng** [comment]
问题 1 发现是在图片翻译窗口上点击功能按钮，触发图片截图翻译时会出现这种情况，通过快捷键触发图片翻译不会出现，下个版本将会修复
问题 2 下个版本也将会优化，开启后依旧保留回车翻译逻辑

**Comment by DreammStill** [comment]
十分感谢
