### ISSUE TITLE
希望在翻译结果里增加英语的音标

### ISSUE THREAD

**Issue by fajianren** [InkTimeRecord/TTime#331]
因为有的单词长，仅仅是听听不清，怕学的发音不准。

**Comment by ByLiangCheng** [comment]
<img width="800" alt="image" src="https://github.com/InkTimeRecord/TTime/assets/45414993/bf1fb4f2-c863-4339-9fce-201c40f5d16e">

 这两个翻译源都有英文英标的

**Comment by fajianren** [comment]
事实情况是都没有.

**Comment by fajianren** [comment]
都没有。即便安装了简明英汉词典（离线版）插件，也看不到音标。
---- 回复的原邮件 ----
发件人	***@***.***>
发送日期	2024年6月6日 19:21
收件人	***@***.***>
抄送人	***@***.***>,
***@***.***>
主题	Re: [InkTimeRecord/TTime] 希望在翻译结果里增加英语的音标 (Issue #331)
image.png (view on web)
这两个翻译源都有英文英标的
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.
---- 回复的原邮件 ----
***@***.***>发送日期2024年6月6日 ***@***.***>***@***.***>,
***@***.***>主题Re: [InkTimeRecord/TTime] 希望在翻译结果里增加英语的音标 (Issue #331)
image.png (view on web)这两个翻译源都有英文英标的

**Comment by fajianren** [comment]
都没有。即便安装了简明英汉词典（离线版）插件，也看不到音标。

**Comment by fajianren** [comment]
都没有。即便安装了所谓简明英汉词典（离线版）插件，音标也不显示。
---- 回复的原邮件 ----
***@***.***>发送日期2024年6月6日 ***@***.***>***@***.***>,
***@***.***>主题Re: [InkTimeRecord/TTime] 希望在翻译结果里增加英语的音标 (Issue #331)
image.png (view on web)这两个翻译源都有英文英标的

**Comment by ByLiangCheng** [comment]
你自己看是否有添加成功，我这里是有的，如示例：

<img width="450" alt="image" src="https://github.com/InkTimeRecord/TTime/assets/45414993/630ba343-b237-44dc-b276-85b98807e4e1">
