### ISSUE TITLE
太耗电脑性能了。看图

### ISSUE THREAD

**Issue by whboy10000** [InkTimeRecord/TTime#333]
![Longshot-20240613134513](https://github.com/InkTimeRecord/TTime/assets/26360478/654de57e-2919-4f47-8f22-7739ed96e59c)

**Comment by ByLiangCheng** [comment]
TTime 是一直后台挂起的，所以显示的是 在过去 12 小时内或从 Mac 电脑启动时的电源能耗

不过后续我们也会尽量做优化
