### ISSUE TITLE
[BUG] 无法自动识别西班牙语

### ISSUE THREAD

**Issue by dsunzhiming** [InkTimeRecord/TTime#335]
请提供下述完整信息以便快速定位问题 / Please provide the following information to quickly locate the problem

- 系统环境 / System Environment：

 macos sonoma

- TTime版本号 / TTime Version：
0.9.12

- 问题描述 / Description of the issue：
无法自动识别出西班牙语
<img width="489" alt="image" src="https://github.com/InkTimeRecord/TTime/assets/11456105/abf039df-aba8-4f5c-9e19-bcbb88b000ec">

**Comment by ByLiangCheng** [comment]
你好，可以给出完整示例吗？我尝试复现一下

**Comment by ByLiangCheng** [comment]
长时间未回复，issues 关闭
