### ISSUE TITLE
[BUG] 每次更新都会把开启启动项关掉

### ISSUE THREAD

**Issue by Mizro-wu** [InkTimeRecord/TTime#336]
- 问题描述 / Description of the issue：
每次更新都会把开启启动项关掉，如下，更新新版本的时候，其他设置项暂时没发现问题，
但是开机启动每次都会给关掉，这次打开了，下次只要更新就会关闭
![image](https://github.com/InkTimeRecord/TTime/assets/71362039/02be3c4c-76d1-4155-b45a-8b624cedd130)

**Comment by ByLiangCheng** [comment]
#326 问题已存在，还是在这个问题下回复即可
