### ISSUE TITLE
[Feature] 增加输入汉语翻译为英文的离线词典

### ISSUE THREAD

**Issue by ipuhao** [InkTimeRecord/TTime#337]
**功能描述 / Function Description**
由于实用环境的限制，经常会断网，目前的简明英汉词典（离线），仅能输入英文翻译为中文，输入中文并不能翻译为英文。
可否增加输入中文翻译为英文的离线词典？

**Comment by ByLiangCheng** [comment]
可以尝试使用Ollama翻译，支持离线翻译
