### ISSUE TITLE
[Feature] 支持同时启用多个相同翻译源

### ISSUE THREAD

**Issue by H3nryM4** [InkTimeRecord/TTime#338]
**功能描述 / Function Description**
![recording](https://github.com/InkTimeRecord/TTime/assets/53041402/6ded4fda-e863-4b4e-acda-b386057c9b7a)

**Comment by ByLiangCheng** [comment]
收到，后续版本会优化这个问题

**Comment by ByLiangCheng** [comment]
新版本已发布，功能已支持
