### ISSUE TITLE
[Feature] 支持对不同的翻译源选择是否开启代理

### ISSUE THREAD

**Issue by H3nryM4** [InkTimeRecord/TTime#339]
**功能描述 / Function Description**
目前在软件中配置代理后，所有的翻译源都走了代理。实际上只有特定的一个或两个需要走代理，如果可以支持对翻译源单独配置是否走代理就好了。
![image](https://github.com/InkTimeRecord/TTime/assets/53041402/b639d2bc-92df-4779-a9c9-715bebb5c056)
这里面有些走代理反而会变得慢

**Comment by ByLiangCheng** [comment]
这个暂不考虑，我所了解中，一般代理工具，只要你不是配置的全局模式，似乎都会有路由规则进行支配，哪些域名请求会走代理，哪些不会
所以理论上国内厂商的服务不会出现走代理的情况，如果没有路由规则，可以自行进行配置即可
