### ISSUE TITLE
划词翻译不生效

### ISSUE THREAD

**Issue by mumudm** [InkTimeRecord/TTime#34]
划词翻译不生效，每次都是读取历史剪贴板翻译
版本 0.0.5，系统 w11
且在多显示器情况下每次都显示在主显示器，希望跟随鼠标，或者支持鼠标所在屏幕

**Comment by ByLiangCheng** [comment]
你好，划词目前部分设备是有存在这个问题，正在寻找解决方案解决中

多显示器跟随鼠标问题已经记录，后续版本中会考虑加入

**Comment by ByLiangCheng** [comment]
此问题已修复，新版本已发布，如还有问题，请重新提交Issues
