### ISSUE TITLE
[Feature] 支持AI翻译自定义提示词  Support for custom AI translation prompts

### ISSUE THREAD

**Issue by Nitmi** [InkTimeRecord/TTime#340]
建议支持 **AI翻译自定义提示词Prompt** ，以下是使用一个词典Prompt进行单词查询的示例，可以看到效果是非常好的，而且支持自定义Prompt之后，用户可以很方便地自定义单词查询结果的格式。这将是一个很好的体验点，可以增加 TTime 的竞争力，非常建议开发者考虑一下。
![image](https://github.com/InkTimeRecord/TTime/assets/114425147/64320f6a-ce5a-445c-a926-9be4aafd28c8)

**Comment by ByLiangCheng** [comment]
你好，我们有计划后续版本中会加入的

**Comment by kafkazov** [comment]
> 你好，我们有计划后续版本中会加入的

好奇预计哪个版本会加入

**Comment by ByLiangCheng** [comment]
> > 你好，我们有计划后续版本中会加入的
> 
> 好奇预计哪个版本会加入

尽量近期版本加入

**Comment by linkerlau** [comment]
强需求+1，期待一波

**Comment by ByLiangCheng** [comment]
新版本已发布，功能已支持
