### ISSUE TITLE
[BUG] 鼠标拖移的时候，窗口会跑

### ISSUE THREAD

**Issue by Mizro-wu** [InkTimeRecord/TTime#341]
- 问题描述 / Description of the issue：
偶尔会出现，拖移窗口的时候，窗口会跑，
鼠标不松开，窗口还处在拖移的状态，
只是窗口不是一开始鼠标按压的位置，
大概是下图的样子，因为不是必定发生的，所以没录屏
![image](https://github.com/InkTimeRecord/TTime/assets/71362039/2fd21e7c-8a54-4ec7-a562-44c4ba9cf715)

**Comment by ByLiangCheng** [comment]
这种情况似乎是在翻译状态下才会出现吧？我们有记录过，但是很少复现出来，所以一直搁置到现在

**Comment by ByLiangCheng** [comment]
新版本已发布，可以尝试在：设置 -> 偏好设置 -> 关闭翻译窗口动态高度 后再观察一下是否还会存在这种情况
