### ISSUE TITLE
[BUG] 电脑缺少驱动问题

### ISSUE THREAD

**Issue by kexidd** [InkTimeRecord/TTime#343]
请提供下述完整信息以便快速定位问题 / Please provide the following information to quickly locate the problem

- 系统环境 / System Environment：win11 64

- TTime版本号 / TTime Version：0.9.13

- 问题描述 / Description of the issue：说找不到msvcp140.dll  让重装软件  但重装了还是没用
![20240716-113340](https://github.com/user-attachments/assets/51064f88-d068-4c45-9cba-9fcadf457b06)
![20240716-113400](https://github.com/user-attachments/assets/b5f484f4-859a-4353-95ea-0eb42141e07e)

**Comment by ByLiangCheng** [comment]
可以先手动安装一下VC库，这个是因为电脑缺少驱动库导致的，我们后面版本会再优化一下这个检测逻辑

https://github.com/InkTimeRecord/TTime/blob/main/build/VC_redist.x64.exe

**Comment by ByLiangCheng** [comment]
新版本已发布，问题已修复
