### ISSUE TITLE
[BUG] 无法翻译，连接失败，连接超时，未知错误

### ISSUE THREAD

**Issue by hmf1235789** [InkTimeRecord/TTime#346]
请提供下述完整信息以便快速定位问题 / Please provide the following information to quickly locate the problem

- 系统环境 / System Environment：
Processor	Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz   1.80 GHz
Installed RAM	8.00 GB (7.86 GB 可用)
System type	64 位操作系统, 基于 x64 的处理器
Pen and touch	Touch support with 10 touch points

Edition	Windows 10 企业版
Version	22H2
Installed on	‎2021/‎12/‎14
OS build	19045.4529
Experience	Windows Feature Experience Pack 1000.19058.1000.0

- TTime版本号 / TTime Version：
TTime 0.9.3

- 问题描述 / Description of the issue：
之前一直可以使用，突然有一天无法翻译，连接失败，连接超时。不管是内置还是自己添加的翻译源，内置翻译源提示翻译请求失败。自己添加的翻译源提示未知错误。
![PixPin_2024-07-24_13-56-18](https://github.com/user-attachments/assets/5953576e-06c1-4bb2-a3a9-c4cb9a929b12)
![PixPin_2024-07-24_13-51-24](https://github.com/user-attachments/assets/e2ae9a3f-2635-4152-b021-4f49970fb55e)

**Comment by ByLiangCheng** [comment]
你好，这个问题需要自行排查一下
1.网络情况，看是不是代理影响到了
2.看是不是电脑其他安全软件之类的拦截了
