### ISSUE TITLE
[BUG] 多屏状态下，使用截图翻译会使显示出现异常

### ISSUE THREAD

**Issue by wrtppp** [InkTimeRecord/TTime#347]
请提供下述完整信息以便快速定位问题 / Please provide the following information to quickly locate the problem

- 系统环境 / System Environment：
win10

- TTime版本号 / TTime Version：
0.9.13

- 问题描述 / Description of the issue：
多屏状态下，在聚焦到副屏时，使用截图翻译会使显示异常，具体表现为将主屏内容强行平移至副屏左上角（如图）

![屏幕截图 2024-07-25 143734](https://github.com/user-attachments/assets/8b678ad7-2b19-4638-a8da-751a1f09316c)

**Comment by ByLiangCheng** [comment]
你好，需要重新补充一下图片，你没有上传成功

**Comment by wrtppp** [comment]
> 你好，需要重新补充一下图片，你没有上传成功

很抱歉没有及时回复，现在图片已重新上传

**Comment by ByLiangCheng** [comment]
抱歉，可以录制一个视频看看流程吗？我根据提供的图片理解了截取的图片跑到了左上角，但是似乎没有太明白，截图中的左边和右边是两个显示器的屏幕区域吗？还是？

**Comment by wrtppp** [comment]
> 抱歉，可以录制一个视频看看流程吗？我根据提供的图片理解了截取的图片跑到了左上角，但是似乎没有太明白，截图中的左边和右边是两个显示器的屏幕区域吗？还是？

[2024-07-27 16-26-46.zip](https://github.com/user-attachments/files/16398753/2024-07-27.16-26-46.zip)
你好，视频压缩包已上传。左边和右边是两个显示器的屏幕区域，具体组合方式及标识在视频里面均有提及，系统设置的主屏幕为正常横置处于组合右侧的屏幕。

**Comment by ByLiangCheng** [comment]
明白了，左边的显示器处于横向，右边的显示器处于横向，当在鼠标光标在左边的显示器时，出发截图，会出现如图的错位情况对不？

你尝试在设置 -> 偏好设置 -> 截图类型 改为系统截图后看看能不能解决这个情况

**Comment by wrtppp** [comment]
非常感谢，它正常工作了
