### ISSUE TITLE
[Feature] 单个单词，增加音标，和发音选择

### ISSUE THREAD

**Issue by congmucc** [InkTimeRecord/TTime#349]
**功能描述 / Function Description**
您好，可以在单个单词情况下增加一下音标和发音选择吗？
![image](https://github.com/user-attachments/assets/3a6574f0-ded3-4f8c-87a8-969772871a1a)
例如这样，这个可以选择英式发音或者美式发音，并且可以有音标，类似网易翻译和百度翻译的那个样子。

**Comment by ByLiangCheng** [comment]
你好，我们正在计划中 ～
