### ISSUE TITLE
[BUG] 截图翻译时帧数过低  貌似没有与显示器同步刷新率

### ISSUE THREAD

**Issue by qq462518439** [InkTimeRecord/TTime#350]
请提供下述完整信息以便快速定位问题 / Please provide the following information to quickly locate the problem

- 系统环境 / System Environment：

Windows

- TTime版本号 / TTime Version：

0.9.13

- 问题描述 / Description of the issue：
截图翻译时帧数过低  没有与显示器同步刷新率  （请在高刷新率模式测试）

**Comment by ByLiangCheng** [comment]
你好，可否提供一个视频示例？

**Comment by qq462518439** [comment]
> 你好，可否提供一个视频示例？

您可以和其他软件附带的截图功能对比一下(例如QQ）。观察两者捕获画面时鼠标移动的流畅度是否一致（请在大于60Hz刷新率模式下测试）

**Comment by ByLiangCheng** [comment]
windwos 环境下我暂时没有复现出来，或者你可以在设置 -> 偏好没置 -> 截图类型改为“系统截图”，看看是不是有好转

> > 你好，可否提供一个视频示例？
> 
> 您可以和其他软件附带的截图功能对比一下(例如QQ）。观察两者捕获画面时鼠标移动的流畅度是否一致（请在大于60Hz刷新率模式下测试）
