### ISSUE TITLE
[BUG] 翻译窗口移动

### ISSUE THREAD

**Issue by Skywalker144** [InkTimeRecord/TTime#352]
请提供下述完整信息以便快速定位问题 / Please provide the following information to quickly locate the problem

- 系统环境 / System Environment：Windows11

- TTime版本号 / TTime Version：0.9.13

- 问题描述 / Description of the issue：翻译窗口莫名其妙移动 见视频

https://github.com/user-attachments/assets/a3ddb057-6d33-4c82-a5b6-7b82df5c43d0

**Comment by ByLiangCheng** [comment]
你好，这个问题我们已经尝试修复了，下个版本发布

**Comment by ByLiangCheng** [comment]
新版本已发布，请尝试在：设置 -> 偏好设置 -> 关闭翻译窗口动态高度 后再试试看 @Skywalker144
