### ISSUE TITLE
[Feature] 希望翻译输入框不显示

### ISSUE THREAD

**Issue by sosmy** [InkTimeRecord/TTime#354]
**功能描述 / Function Description**
建议增加截屏翻译后，显示截屏中英文对照or可选只保留翻译结果，，现在截屏翻译功能OCR识别后字数多有可能是一堆英文单词乱码，
比较好的图片翻译类似功能是百度翻译，跟有道翻译，桌面版，，感谢作者的付出，

**Comment by ByLiangCheng** [comment]
没理解，指的是截图翻译后，希望输入框不显示吗？如果是这种的，建议可以试试 开启设置 -> 高级设置 -> 翻译输入框可收缩

**Comment by sosmy** [comment]
***@***.***

就是类似翻译后能够这样显示，现在软件翻译后是不是只是提取英文字母，只是把字母翻译成汉语，

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

________________________________
发件人: ByLiangCheng ***@***.***>
发送时间: Saturday, September 7, 2024 11:47:11 AM
收件人: InkTimeRecord/TTime ***@***.***>
抄送: sosmy ***@***.***>; Author ***@***.***>
主题: Re: [InkTimeRecord/TTime] [Feature] (Issue #354)


没理解，指的是截图翻译后，希望输入框不显示吗？如果是这种的，建议可以试试 开启设置 -> 高级设置 -> 翻译输入框可收缩

―

**Comment by ByLiangCheng** [comment]
@sosmy 是有附加图片吗？好像没有看到

**Comment by sosmy** [comment]
是的，有附加图片，就是网易有道翻译，跟百度翻译，widows桌面版，截图翻译的效果，

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

________________________________
发件人: ByLiangCheng ***@***.***>
发送时间: Sunday, September 8, 2024 1:50:54 AM
收件人: InkTimeRecord/TTime ***@***.***>
抄送: sosmy ***@***.***>; Mention ***@***.***>
主题: Re: [InkTimeRecord/TTime] [Feature] 希望翻译输入框不显示 (Issue #354)


@sosmy<https://github.com/sosmy> 是有附加图片吗？好像没有看到

―

**Comment by ByLiangCheng** [comment]
关于这段描述我没有太理解，如果可以提供一下示例的话，需要你再次上传一下示例图片，以帮助我定位这个需求

**Comment by sosmy** [comment]
https://ibb.co/B2fWGKX    示例图片已经上传图片，，希望翻译后达到这种效果，，，现在你软件截图翻译后是提取图中的英文字母翻译，
________________________________
发件人: ByLiangCheng ***@***.***>
发送时间: 2024年9月8日 10:20
收件人: InkTimeRecord/TTime ***@***.***>
抄送: sosmy ***@***.***>; Mention ***@***.***>
主题: Re: [InkTimeRecord/TTime] [Feature] 希望翻译输入框不显示 (Issue #354)


关于这段描述我没有太理解，如果可以提供一下示例的话，需要你再次上传一下示例图片，以帮助我定位这个需求

―

**Comment by ByLiangCheng** [comment]
你指的是图片翻译吧？我们现在已经是支持的，你可以在设置 -> 全局快捷键设置 -> 图片翻译
