### ISSUE TITLE
[Feature] 增加音标显示功能

### ISSUE THREAD

**Issue by 526838923** [InkTimeRecord/TTime#355]
**功能描述 / Function Description**
![4bad20e741713c376b32c0063fe6cc91_translate](https://github.com/user-attachments/assets/5b036e6d-4453-45f1-81ed-54b16f88a5b5)
官网界面图片显示有音标，但是实际使用中没有音标

**Comment by ByLiangCheng** [comment]
按照有道官网通知，现在已经不给词典数据了，目前的解决方案可以在设置 -> 翻译源设置 然后哪个翻译源需要词典就选择并勾选显示词典选项即可
