### ISSUE TITLE
[Feature] 希望增加翻译源“DeeplX”，即：可配置请求接口的DeeplX接口 | Hope to add translation source "DeeplX", that is: DeeplX interface with configurable request interface

### ISSUE THREAD

**Issue by Zerek-Cheng** [InkTimeRecord/TTime#356]
**功能描述 / Function Description**
希望增加翻译源“DeeplX”，即：可配置请求接口的DeeplX接口
参考其他应用：
![image](https://github.com/user-attachments/assets/1e125443-ad4e-49a3-9a61-f160f087eabe)

Hope to add translation source "DeeplX", that is: DeeplX interface with configurable request interface

**Comment by ByLiangCheng** [comment]
你好，这个我们有计划，后续版本会加入

**Comment by ByLiangCheng** [comment]
新版本已发布，功能已支持
