### ISSUE TITLE
输入框输入任意字符窗口都会往左移动一个像素，包括删除键

### ISSUE THREAD

**Issue by qet006** [InkTimeRecord/TTime#36]
输入框输入任意字符窗口都会往左移动一个像素，包括删除键

**Comment by ByLiangCheng** [comment]
你好，可以提供一下，系统版本，是否多显示器？显示器缩放比例等信息吗？

因为之前也有别的用户反馈过此问题，但是我这边一直没有复现出来

**Comment by qet006** [comment]
系统是WIN10，显示器缩放110

**Comment by ByLiangCheng** [comment]
好的，我这边之后再试试看看想办法复现一下

**Comment by ByLiangCheng** [comment]
新版本已发布，问题已修复，请尝试在：设置 -> 偏好设置 -> 关闭翻译窗口动态高度 后再试试看
