### ISSUE TITLE
[BUG] 下载跳转到 CSDN 还得登录才能下载，登录了之后还找不到仓库，SB 吧

### ISSUE THREAD

**Issue by HahaCodeLife** [InkTimeRecord/TTime#360]
请提供下述完整信息以便快速定位问题 / Please provide the following information to quickly locate the problem

- 系统环境 / System Environment：

- TTime版本号 / TTime Version：

- 问题描述 / Description of the issue：

**Comment by ByLiangCheng** [comment]
刚已经迁移走了，官网里也有提供备用下载地址
