### ISSUE TITLE
[BUG] 划词翻译"识别内容为空"

### ISSUE THREAD

**Issue by tangzeyu7** [InkTimeRecord/TTime#361]
请提供下述完整信息以便快速定位问题 / Please provide the following information to quickly locate the problem

- 系统环境 / System Environment：
Windows 11 家庭中文版 21H2 22000.2538

- TTime版本号 / TTime Version：
0.9.14

- 问题描述 / Description of the issue：
在 Edge 129.0.2792.65 (正式版本) (64 位) 中"划词翻译"无法识别选中文本,提示"识别内容为空"

**Comment by ByLiangCheng** [comment]
你好，按照这三个方法尝试看看能正常使用哈

1.在设置 -> 偏好设置 -> 划词默认前后延迟 的值调大一些后看看能不能正常划词
2.如果是在浏览器中划词失败 , 请检查是否有插件冲突
3.windows 环境下是否有使用工具修改过系统快捷键

**Comment by tangzeyu7** [comment]
按方式1调整后已解决.
