### ISSUE TITLE
[BUG] 教程不显示了

### ISSUE THREAD

**Issue by ghost** [InkTimeRecord/TTime#364]
请提供下述完整信息以便快速定位问题 / Please provide the following information to quickly locate the problem

- 系统环境 / System Environment：win10

- TTime版本号 / TTime Version：0.9.14

- 问题描述 / Description of the issue：
![image](https://github.com/user-attachments/assets/1ae42d09-1552-4de9-a81a-85b3f23f7a7e)
不显示了

**Comment by ByLiangCheng** [comment]
感谢反馈，已经修复啦，这块默认软件只显示一次，可以上官网看看 ～
