### ISSUE TITLE
[BUG] Ollama不可用

### ISSUE THREAD

**Issue by ljn-aaa** [InkTimeRecord/TTime#372]
请提供下述完整信息以便快速定位问题 / Please provide the following information to quickly locate the problem

- 系统环境 / System Environment：
macos
Sonoma 14.6.1

- TTime版本号 / TTime Version：
![image](https://github.com/user-attachments/assets/e3704d7b-cb97-4be8-9a1b-88eea857cb09)

- 问题描述 / Description of the issue：
![image](https://github.com/user-attachments/assets/69edcbdb-afb8-46fc-a807-0ff4ae5c26fd)
![image](https://github.com/user-attachments/assets/ed0f28d6-575b-4f12-9a7d-7f2056323805)

配置了llama3的模型，但翻译页面显示未启动服务。

另外，全屏文档之后，翻译页面不能显示在全屏文档页面上？
如下图，如果将文档全屏后，翻译页面将留在当前窗口。
![image](https://github.com/user-attachments/assets/ad12d5aa-ab90-4701-9ff6-daeada183bf2)

**Comment by ByLiangCheng** [comment]
你好，我回答一下

1. 关于 Ollama 提示未启动问题：你先尝试浏览器页面访问 http://127.0.0.1:11434 看是否正常，如果地址无法访问的话，就说明要么是 Ollama 未启动，要么是端口号有过修改，如果正常，切换一个小的模型试试看看是否还是这个提示？

2. 翻译窗口全屏问题后续会优化，目前确实是不行的，暂时只支持上了图片翻译和静默OCR
