### ISSUE TITLE
[BUG] TTime OCR在识别连续大写英文字母组成的英文缩写时，经常会错误识别出多余的空格

### ISSUE THREAD

**Issue by Xarlley** [InkTimeRecord/TTime#373]
请提供下述完整信息以便快速定位问题 / Please provide the following information to quickly locate the problem

- 系统环境 / System Environment：Windows 11 for X86_64

- TTime版本号 / TTime Version：0.9.14

- 问题描述 / Description of the issue：TTime OCR 在识别连续大写英文字母组成的英文缩写时，经常会错误识别出多余的空格，例如 “ABCD” 被识别成 “AB CD”，再例如 “PC IE”，“I SA” 等等。在 OCR 整段英文文本时，问题尤其明显。

**Comment by ByLiangCheng** [comment]
你好，我测试中似乎没有出现这种情况，如下图，可否提供一个示例看看

<img width="810" alt="image" src="https://github.com/user-attachments/assets/9cedcf16-625a-43d6-82b5-fc57c9f1cacc">

**Comment by Xarlley** [comment]
![Snipaste_2024-12-01_21-59-09](https://github.com/user-attachments/assets/83d29da2-b2b2-4ee4-9d4e-5fb63fbf0783)

**Comment by Xarlley** [comment]
![image](https://github.com/user-attachments/assets/588b730d-2b3b-4491-945c-4bae8f58575d)

**Comment by Xarlley** [comment]
![image](https://github.com/user-attachments/assets/778de789-3ea4-41b1-8abe-0173bd31b86d)

**Comment by Xarlley** [comment]
这三个截图显示了关于“错误插入多余空格的问题“。另外，如第三个截图中把CIM给识别成CiM，似乎有时候大小写也不能准确分辨。

**Comment by Xarlley** [comment]
同一段文本，再截取一次（但不能保证完全框选出一模一样的截图，也许多几个少几个像素），就可能不再出现这个错误插入空格的问题。这也许是因为新的截取与旧的截取并不完全相同，也许加入了微小的扰动，OCR就会有不同的表现。

**Comment by ByLiangCheng** [comment]
1.可以尝试修改一下文字识别语言为英语，我尝试中英混合情况下出现这样的情况时，切换为英文时没有出现

2.或试试Rapid OCR

**Comment by Xarlley** [comment]
![image](https://github.com/user-attachments/assets/0b4afa87-137c-4945-aa00-fe4233a1e70f)
更换成英语后，没有解决问题，甚至更严重了

**Comment by Xarlley** [comment]
![image](https://github.com/user-attachments/assets/c8d742d9-412a-4479-958d-52400d201343)

**Comment by ByLiangCheng** [comment]
有切换到Rapid OCR试过吗？

**Comment by Xarlley** [comment]
![image](https://github.com/user-attachments/assets/14835080-2695-48bb-906a-3d97e59951bd)
纯从使用的角度说，这个中英混合目前是出错率最低的。【这只是一种使用上的感觉，倒没有统计支持】
此前使用的出问题的是安装软件后默认的“中英混合（旧）”。
以及，你建议的“英文”，出错率似乎更高。【同样，只是感觉】

**Comment by Xarlley** [comment]
不知道如何使用Rapid OCR。
以及，既然旧的中英混合存在问题，我建议要么修复，要么就不要让它成为安装软件后默认被选择的项。

**Comment by ByLiangCheng** [comment]
我大概综合测试了一下，基本上所有的离线模型的语言包或多或少会有一些细节的处理问题，目前如果对细节要求比较仔细，更建议在软件内添加第三方OCR，现有离线模型和语言包后续有空的话，我会尝试继续优化一下

添加方式其他文字识别服务方式：
1. 官方文档教程：https://ttime.timerecord.cn/service/setOCR.html
2. 当前截图的页面下面，有添加的按钮
<img width="850" alt="image" src="https://github.com/user-attachments/assets/2edcd816-ef8f-44de-85e9-5ab8bd3cee02">

关于为什么不直接替换掉(旧)中英混合
1.(旧)中英混合这个语言包是安装就内置的，而其他的语言包是需要安装软件后，再下载语言资源包，所以没办法一开始就直接切换
2.最初TTime版本只有(旧)中英混合，刚加上其他语言包支持时，是不确定影响的范围，如果贸然替换掉(旧)中英混合，如果新的有问题，会影响到其他正常使用的用户

当然后续我们也会再继续做优化的，但是因为这块是比较复杂的，所以进度可能会慢一些了
