### ISSUE TITLE
[BUG] 使用DeepL翻译服务时报错

### ISSUE THREAD

**Issue by DreammStill** [InkTimeRecord/TTime#374]
请提供下述完整信息以便快速定位问题 / Please provide the following information to quickly locate the problem

- 系统环境 / System Environment：
Win11 24H2

- TTime版本号 / TTime Version：
0.9.14

- 问题描述 / Description of the issue：
使用DeepL翻译服务时提示：
Request failed with status code 429
一开始我以为是加速的问题，后来关闭加速依旧没有解决
另外使用IOS版时如果长时间不使用软件登录会失效但软件没有提示重新登录，具体表现为使用快捷指令调用OCR识别翻译时提示未登录账户，但是打开个人中心显示已登录，必须要退出重新登录才行

**Comment by ByLiangCheng** [comment]
你好，DeepL的问题我们也关注到了，正在查看中

IOS的登录问题下个版本会修复

**Comment by WvW-vOiDs** [comment]
same issue

**Comment by ByLiangCheng** [comment]
新版本已发布，问题已修复

**Comment by DreammStill** [comment]
> 新版本已发布，问题已修复

收到，辛苦了
