### ISSUE TITLE
[BUG] OCR经常不能正确分辨0和O

### ISSUE THREAD

**Issue by Xarlley** [InkTimeRecord/TTime#375]
请提供下述完整信息以便快速定位问题 / Please provide the following information to quickly locate the problem

- 系统环境 / System Environment：Windows 11

- TTime版本号 / TTime Version：0.9.14

- 问题描述 / Description of the issue：OCR经常不能正确分辨0和O
![image](https://github.com/user-attachments/assets/b35a0426-48be-45ee-a3ac-464d35b30d8c)

**Comment by ByLiangCheng** [comment]
这种的可以接入第三方OCR 方案了，后续有空的话，我会尝试优化一下现有模型能力
