### ISSUE TITLE
[BUG] 不能翻译

### ISSUE THREAD

**Issue by xzxlove** [InkTimeRecord/TTime#377]
请提供下述完整信息以便快速定位问题 / Please provide the following information to quickly locate the problem

- 系统环境 / System Environment：
windows11

- TTime版本号 / TTime Version：

0.9.14
- 问题描述 / Description of the issue：
比如这种的英文就无法翻译成中文iotCardService
![image](https://github.com/user-attachments/assets/acebe54c-c87c-4a4d-8b2c-6fb01fb77834)

**Comment by ByLiangCheng** [comment]
你这个应该是手动输入或粘贴到输入框出现的，你使用截图翻译或者划词翻译不会出现这种情况，这种是翻译服务商那边的问题，他们不会处理多个英文单词之间不加空格的情况，只会当做是一个单词进行翻译了，而你用截图或划词翻译时，TTime内置是自动检测了，这种情况会进行自动分割的

如：

<img width="450" alt="image" src="https://github.com/user-attachments/assets/3988c957-fb46-4e28-a252-bd12cf336cb8">
