### ISSUE TITLE
[BUG] 内置Deepl翻译问题

### ISSUE THREAD

**Issue by SantoGG** [InkTimeRecord/TTime#378]
请提供下述完整信息以便快速定位问题 / Please provide the following information to quickly locate the problem

- 系统环境 / System Environment：
Win11，23H2，22631.4602

- TTime版本号 / TTime Version：
0.9.15

- 问题描述 / Description of the issue：
任何翻译方式下，Deepl翻译源均会出现以下内容，已在多台PC中尝试，出现同样结果
![微信截图_20241218093336](https://github.com/user-attachments/assets/9bbeaaf9-c0f8-45bd-966b-68036a881d1e)
：

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <title>Page Load Error</title>
    <style>
        .button {
            background-color: #0f2b46;
            border: none;
            color: #fff;
            padding: 15px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 16px;
            margin: 4px 2px;
            cursor: pointer;
            border-radius: 8px;
            max-width: 100px
        }

        div.content {
            margin: center;
            width: 500px
        }

        button, h1, object, p {
            text-align: center;
            font-family: -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Helvetica, Arial, sans-serif !important
        }

        .centering {
            display: flex;
            justify-content: center;
            align-items: center;
            flex-direction: column
        }

        #robot {
            max-width: 200px
        }

        #reload-button {
            padding: 2em
        }
    </style>
    <link rel="icon" type="image/png" href="https://static.deepl.com/img/favicon/favicon_16.png" sizes="16x16"/>
    <link rel="icon" type="image/png" href="https://static.deepl.com/img/favicon/favicon_32.png" sizes="32x32"/>
    <link rel="icon" type="image/png" href="https://static.deepl.com/img/favicon/favicon_96.png" sizes="96x96"/>
</head>
<body>
<main>
    <div class=centering><img width="100px" src="https://static.deepl.com/img/logo/DeepL_Logo_darkBlue_v2.svg"/>
        <h1>Slow Down Please!</h1>
        <div class=centering><img id="robot" src="https://static.deepl.com/img/404/robot.svg"/></div>
        <p>We have received too many requests from you too quickly.</p>
        <p>This error will automatically be cleared shortly. Please try again later.</p>
        <div class=centering id=reload-button>
            <button onClick="location.reload();" class="button">Reload</button>
        </div>
        <div class=centering>
            <pre>907900ad2d4f4666904e8034a05154b7</pre>
        </div>
    </div>
</main>
</body>
</html>

**Comment by ByLiangCheng** [comment]
抱歉，这个是 DeepL 限制了 IP，暂时没办法，建议使用填写密钥或了解一下 DeepLX 搭建试试看

**Comment by SantoGG** [comment]
> 抱歉，这个是 DeepL 限制了 IP，暂时没办法，建议使用填写密钥或了解一下 DeepLX 搭建试试看

了解了，感谢解答
