### ISSUE TITLE
截图翻译能否增加右键退出

### ISSUE THREAD

**Issue by rogercc116** [InkTimeRecord/TTime#38]
当前版本：0.0.5
快捷键出发截图翻译功能后  必须进行截图操作  能否增加鼠标右键退出截图功能

**Comment by ByLiangCheng** [comment]
你好，目前支持 Esc 或 Alt + Esc 快捷键退出的哈，因为当时考虑这是个习惯操作，文档就没有专门写出来了，我后面在文档上补充标注一下

**Comment by ByLiangCheng** [comment]
新版本发布，功能已增加
