### ISSUE TITLE
Alt+E容易识别到旧文本

### ISSUE THREAD

**Issue by micro-mieruko** [InkTimeRecord/TTime#40]
Alt+E划词翻译容易识别到旧的文本，需要手动CTRL+C再Alt+E才识别正确的文本。特别是在edge浏览器上，Alt+E识别到的文本，经常是上一次翻译的文本，不是当前选中的文本

**Comment by ByLiangCheng** [comment]
现在部分机型是有这个问题，已经在研究修改方案中了，尽量在下个版本中修复

**Comment by ByLiangCheng** [comment]
此问题已修复，新版本已发布，如还有问题，请重新提交Issues
