### ISSUE TITLE
软件体积好像有点太大了

### ISSUE THREAD

**Issue by CooperZhuang** [InkTimeRecord/TTime#41]
奇怪的，为什么会一百兆这么大？是不是打包的时候把无关的依赖包也打包进来了？，后续可以优化一下？

**Comment by ByLiangCheng** [comment]
你好，对于这个问题，其实我也很无奈，软件是基于的Electron开发的，目前来说这个对于跨平台、系统版本、支持库、兼容性等问题相对成熟一些，但其中缺点就是，无法做到特别小的体积

也对比过其他的方式开发，但相比较用户体验（当然还有开发、学习成本）与软件体积，我选择了以用户体验为主导

不过考虑现在大部分用户应该也不用纠结硬盘大小问题，所以目前暂时先维护好核心功能，后期会想办法尽量优化大小
