### ISSUE TITLE
截图分辨率问题

### ISSUE THREAD

**Issue by papershell** [InkTimeRecord/TTime#42]
在2K屏幕笔记本中使用，截图预览窗中图像分辨率比实际分辨率低了很多，是否会影响文字识别的准确率？

**Comment by ByLiangCheng** [comment]
你好，截图预览窗口显示有点糊，这个问题当前确实存在，后面有时间的话会考虑进行优化，之前有过大概测试，不是特殊场景的文字，正常识别应该都还行
