### ISSUE TITLE
望早日支持Linux系统

### ISSUE THREAD

**Issue by IbenZhou** [InkTimeRecord/TTime#43]
Electron对跨平台的支持特别好，希望作者能迟早发布Linux版本。

**Comment by ByLiangCheng** [comment]
你好，因为发布至今Linux系统环境下一直没测试过，所以发布Linux版本可能需要一定的时间做测试及兼容

现在主要重心是放在维护Windows版本的核心功能上，如果使用Linux版本的用户需求较多的话，会考虑把支持Linux的需求提前

**Comment by beta1scat** [comment]
> 你好，因为发布至今Linux系统环境下一直没测试过，所以发布Linux版本可能需要一定的时间做测试及兼容
> 
> 现在主要重心是放在维护Windows版本的核心功能上，如果使用Linux版本的用户需求较多的话，会考虑把支持Linux的需求提前

您好，目前可以在Linux上可以用了吗？我看您把这个issue关闭了。

**Comment by ByLiangCheng** [comment]
> > 你好，因为发布至今Linux系统环境下一直没测试过，所以发布Linux版本可能需要一定的时间做测试及兼容
> > 现在主要重心是放在维护Windows版本的核心功能上，如果使用Linux版本的用户需求较多的话，会考虑把支持Linux的需求提前
> 
> 您好，目前可以在Linux上可以用了吗？我看您把这个issue关闭了。

暂时还不行
抱歉前段时间关闭了一批长时间驻留的issue，这个误操作，重新打开了

**Comment by pmzgit** [comment]
希望早日支持linux，例如deepinv20 或 v23

**Comment by Alex-Zuo-One** [comment]
听群友推荐的，希望早日支持linux

**Comment by JohnFrankz** [comment]
+1

**Comment by xYx-c** [comment]
+1

**Comment by aonoa** [comment]
+1

**Comment by tianws** [comment]
ubuntu +1

**Comment by NPC2000** [comment]
ubuntu +1

**Comment by NPC2000** [comment]
ubuntu +1

**Comment by leafmoes** [comment]
希望早日支持，archlinux用户一枚

**Comment by feiwuya** [comment]
> 希望早日支持linux，例如deepinv20 或 v23

我现在正在使用 deepin 20，我打包了一份，修改了桌面托盘不显示问题，你可以直接下载安装

[下载地址 Google 网盘](https://drive.google.com/drive/folders/1IORWYSu1Zy4AZyDtCFqerZ1_UCHKS9QK?usp=sharing)

**Comment by Greatsaltedfish** [comment]
> > 希望早日支持linux，例如deepinv20 或 v23
> 
> 我现在正在使用 deepin 20，我打包了一份，修改了桌面托盘不显示问题，你可以直接下载安装
> 
> [下载地址 Google 网盘](https://drive.google.com/drive/folders/1IORWYSu1Zy4AZyDtCFqerZ1_UCHKS9QK?usp=sharing)

您好，方便请教一下这个项目是怎么构建的吗？我对nodejs的项目不熟悉。

**Comment by PACHAKUTlQ** [comment]
Hope supports for Linux comes soon. Even though there are bugs and incompatibilities, as an Electron app, most part of this should work fine on Linux.

**Comment by indexss** [comment]
> > 希望早日支持linux，例如deepinv20 或 v23
> 
> 我现在正在使用 deepin 20，我打包了一份，修改了桌面托盘不显示问题，你可以直接下载安装
> 
> [下载地址 Google 网盘](https://drive.google.com/drive/folders/1IORWYSu1Zy4AZyDtCFqerZ1_UCHKS9QK?usp=sharing)

感谢，pot在kde下有很多bug, 体验不佳。这个打包我在kde plasma的arch下测试了，效果很好。
