### ISSUE TITLE
安装最新版依旧是无法启用

### ISSUE THREAD

**Issue by GodA68** [InkTimeRecord/TTime#45]
程序安装后弹出如下提示框，官网下载位最新版本依旧显示。推出后程序会在后台运行，再次点击后闪退
![image](https://user-images.githubusercontent.com/79685060/232354931-d0a67a60-eaea-4568-832c-d835218b409e.png)

**Comment by ByLiangCheng** [comment]
抱歉哈 昨晚上临时修改出问题了 现在已经修复了，无法打开的情况，再重启软件即可

**Comment by GodA68** [comment]
> 

已经可以使用了，感谢
