### ISSUE TITLE
划词翻译不生效，每次都是读取的剪切板内容翻译

### ISSUE THREAD

**Issue by tangli1204** [InkTimeRecord/TTime#50]
版本：0.0.5
系统：win11
划词翻译选中文本后，翻译的文本不是选中的而是从剪切板读取的内容，每次都要先ctrl c然后才能alt e

**Comment by ByLiangCheng** [comment]
你好，此问题已修复，下个版本中发布

**Comment by ByLiangCheng** [comment]
此问题已修复，新版本已发布，如还有问题，请重新提交Issues
