### ISSUE TITLE
如何使用多个候选词？

### ISSUE THREAD

**Issue by 17344config** [InkTimeRecord/TTime#52]
1. 请问如何设置，才能够显示多个翻译候选？

**Comment by 17344config** [comment]
> 你好，没有太明白你指的“显示多个翻译候选”是什么意思
> 
> 如果是想显示多个翻译源的话，请参考官网中的翻译源介绍 ：https://ttime.timerecord.cn/pages/93e0f8/#%E7%AE%80%E4%BB%8B

1. 不说说多个翻译源。
2. 我的意思是：翻译Terminal，他只有一个航空站的翻译，他应该还有终端呀，之类的翻译
![image](https://user-images.githubusercontent.com/115962768/234221606-49c7ea5b-3da8-4012-8ad1-86d0ec2d2901.png)

**Comment by ByLiangCheng** [comment]
你好，由于之前在百度翻译接口文档有看到说，词典功能目前只开放给企业，而大部分普通用户是无法申请的，所以我这里也没有做接入了

如果有其他方式欢迎继续提交issues或根据联系方式和我沟通 谢谢

除此之外，如果想要使用词典功能，可以使用有道的翻译源
