### ISSUE TITLE
企业微信打开图片使用软件进行截图翻译识别内容为空

### ISSUE THREAD

**Issue by rogercc116** [InkTimeRecord/TTime#53]
![image](https://user-images.githubusercontent.com/63380214/234216086-e650b2d3-4d1c-4421-b9c5-30e3ab0a34f1.png)
![image](https://user-images.githubusercontent.com/63380214/234216141-4508509e-d933-49db-8fee-f01f3db10217.png)
翻译Kommissionier这一段 显示识别内容为空

**Comment by ByLiangCheng** [comment]
新版本已发布，现已支持第三方OCR
