### ISSUE TITLE
划词后鼠标侧键翻译

### ISSUE THREAD

**Issue by TaoLoading** [InkTimeRecord/TTime#54]
作者你好，软件是否支持划词后鼠标侧键翻译？如果支持请告诉我怎么设置，如果不支持希望加上这个功能，谢谢

**Comment by ByLiangCheng** [comment]
你好，指的是鼠标右键菜单中希望有个翻译的选项吗？

**Comment by TaoLoading** [comment]
鼠标侧键，划词后按鼠标侧键触发翻译，即鼠标侧键代替Alt+E

**Comment by ByLiangCheng** [comment]
新版本已发布，支持鼠标县浮球取词功能
