### ISSUE TITLE
截图翻译和划词翻译都一直有换行符

### ISSUE THREAD

**Issue by EthanHYX** [InkTimeRecord/TTime#56]
RT，截图翻译和划词翻译都一直有换行符，会导致无法翻译pdf中的段落

**Comment by Ice-small** [comment]
补充：
更新0.06后我划词翻译就无法使用了，0.05正常，系统：Win10专业版

**Comment by ByLiangCheng** [comment]
> RT，截图翻译和划词翻译都一直有换行符，会导致无法翻译pdf中的段落

你好，当前是存在此问题，后续版本中会想办法解决

**Comment by ByLiangCheng** [comment]
> 补充： 更新0.06后我计划词翻译就无法使用了，0.05正常，系统：Win10专业版

你好，提问和当前Issues不是一个问题，我已经新开了一个 Issues #59 ，后续这边回复哈

**Comment by simouse** [comment]
当前版本下用户端解决此问题的一些思路：

1. 使用其他 pdf 阅读软件。举例：zotero（尽管它主要功能是管理文献）在复制 pdf 内容的时候会去掉换行，这样传到 TTime 里的文本就是合适的文本。
2. 将 TTime 中使用 AI 的翻译源（比如小牛和 DeepL）放在翻译列表前面。这些 AI 翻译源基本不受换行影响。

**Comment by ByLiangCheng** [comment]
最新版本已发布，划词功能已修复
