### ISSUE TITLE
识别内容为空

### ISSUE THREAD

**Issue by cybernewboy** [InkTimeRecord/TTime#57]
更新后按快捷键都显示识别内容为空

**Comment by ByLiangCheng** [comment]
你好，识别内容为空指的是截图翻译还是划词翻译的情况下呢？

**Comment by mumudm** [comment]
我这也是划词翻译显示识别内容为空，其他功能没有问题

**Comment by cybernewboy** [comment]
> 你好，识别内容为空指的是截图翻译还是划词翻译的情况下呢？

划词翻译下，感觉是没有复制到剪贴板

**Comment by ByLiangCheng** [comment]
@mumudm @cybernewboy 两位是什么系统？使用的都是0.0.6版本吗？

**Comment by mumudm** [comment]
软件版本 0.0.6,
系统是Windows 11 Version 22H2

**Comment by ByLiangCheng** [comment]
OK，后面我再尝试一下，看能否复现这个问题

**Comment by cybernewboy** [comment]
软件版本 0.0.6,
系统是Windows 11 家庭中文版

**Comment by ByLiangCheng** [comment]
@mumudm @cybernewboy 你好，我对划词进行了一些修改，能否提供下邮箱，我发送一个测试版本的包给你们试试

**Comment by ByLiangCheng** [comment]
新版本已发布
