### ISSUE TITLE
更新0.06后我划词翻译就无法使用了

### ISSUE THREAD

**Issue by ByLiangCheng** [InkTimeRecord/TTime#59]
补充：
更新0.06后我划词翻译就无法使用了，0.05正常，系统：Win10专业版

_Originally posted by @Ice-small in https://github.com/InkTimeRecord/TTime/issues/56#issuecomment-1535610314_

**Comment by ByLiangCheng** [comment]
@Ice-small 你好请问是更新到0.0.6版本之后在任何软件或网页中都无法使用划词吗？

**Comment by Ice-small** [comment]
> @Ice-small 你好请问是更新到0.0.6版本之后在任何软件或网页中都无法使用划词吗？

是的，完全无法使用，切换回0.05版本就可以了

**Comment by ByLiangCheng** [comment]
能否录制视频提供一下，我这边看看操作流程是什么样的

**Comment by Ice-small** [comment]
> 能否录制视频提供一下，我这边看看操作流程是什么样的
录制也不知道发哪，我就先口述一下吧，

系统版本是win10专业版

0.05版本使用一切正常
0.06版本使用结果是这样的，当我划词后会使用F3(设置的划词搜索快捷键)进行划词搜索，然后会弹出软件界面，会弹出提示(内容不能为空)，像是没读取到划词内容或是读取到了没写入查询输入框一样

**Comment by ByLiangCheng** [comment]
好的，我这边先尝试复现一下，看能否触发此问题

**Comment by andywang1011** [comment]
0.0.6是这个问题，划词翻译有一定几率出现获取不到内容的情况，几率还挺高的。

**Comment by ByLiangCheng** [comment]
> 0.0.6是这个问题，计划词翻译有一定几率出现发现取不到内容的情况，几率还是挺高的。

你好，我对划词进行了一些修改，能否提供下邮箱，我发送一个测试版本的包给你试试

**Comment by ByLiangCheng** [comment]
新版本已发布，此问题已解决
