### ISSUE TITLE
关于划词翻译快捷唤出界面警告问题

### ISSUE THREAD

**Issue by CyshallChan** [InkTimeRecord/TTime#60]
如图，当我没有选中任何文字就使用划词翻译快捷键唤出界面就出现告警，能否取消这个告警？这样的话快快捷键就只需要设置划词翻译和OCR翻译两个快捷键就行了（当我需要唤出翻译窗口的时候直接就不选中任何文字使用划词翻译快捷键唤出）
<img width="343" alt="Snipaste_2023-05-05_21-26-34" src="https://user-images.githubusercontent.com/22564041/236470632-bb097e24-2fd9-4e7b-93bf-9eb6f320618a.png">

**Comment by CyshallChan** [comment]
啥功能都不应该，只需要去掉那个提示就可以了阿

**Comment by ByLiangCheng** [comment]
> 啥功能都不用该阿，只需要去掉那个提示就可以了阿

这块没有说的这么简单，几个默认快捷键的翻译逻辑代码之间实现是公用的，改一个地方其他地方都会受到牵连，包括用户

**Comment by CyshallChan** [comment]
> > 啥功能都不用该阿，只需要去掉那个提示就可以了阿
> 
> 这块没有说的这么简单，几个默认快捷键的翻译逻辑代码之间实现是公用的，改一个地方其他地方都会受到牵连，包括用户

好的，了解
