### ISSUE TITLE
翻译语句中如果有"[+]"时，翻译出来+丢失

### ISSUE THREAD

**Issue by CrystalWyz** [InkTimeRecord/TTime#61]
![image](https://user-images.githubusercontent.com/37053692/236846780-bb04a202-392c-4cea-b918-7fdf833e3488.png)

**Comment by ByLiangCheng** [comment]
你好，这个好像是因为翻译源通道方在翻译时检测到这样的文本时会报错，所以我这默认剔除了，后续我再测试一下看看有没有办法解决

**Comment by ByLiangCheng** [comment]
新版本已发布，此问题已解决
