### ISSUE TITLE
选中一段文本后多次按下alt+e后，第二次往后开始都显示为"识别内容为空"

### ISSUE THREAD

**Issue by CrystalWyz** [InkTimeRecord/TTime#62]
稳定复现

**Comment by CrystalWyz** [comment]
> 你好，请问指的的选中一段文本后多次按下alt+e指的是？操作流程可以录个视频什么的看看吗？

详细说就是， 鼠标选中一段文本，按ALT+E 后，文本成功翻译。然后再按一次ALT+E后，显示翻译内容为空

**Comment by ByLiangCheng** [comment]
你好，这个应该是正常现象吧，默认划词获取的是光标选中的焦点内容，而首次划词时自然是可以获取到光标的焦点内容的
而当TTime窗口显示后，之前光标焦点内容已经失去，自然也无法获取
