### ISSUE TITLE
shift+p+p 窗口就自动弹出来了

### ISSUE THREAD

**Issue by swhje** [InkTimeRecord/TTime#63]
没办法关闭这个功能

**Comment by SUDre** [comment]
Ctrl+shift+p 同样出现

**Comment by ByLiangCheng** [comment]
你好，这个快捷键是与系统/其他应用的快捷键冲突了吗？

因为一些特殊原因需要模拟调用，当时考虑的是这个快捷键用的不多所以给占用了

**Comment by SUDre** [comment]
是的 自己的软件有这个快捷键组合

Regards,
Su Zhewei, Dre
+852 9143-8030
2023年5月13日 +0800 PM3:02 ByLiangCheng ***@***.***>，写道：

**Comment by ByLiangCheng** [comment]
好的，这个问题下个版本中会进行修复

**Comment by SUDre** [comment]
谢谢啦

Regards,
Su Zhewei, Dre
+852 9143-8030
2023年5月14日 +0800 AM12:09 ByLiangCheng ***@***.***>，写道：
