### ISSUE TITLE
IDEA上使用划词翻译阅读源码注释时的问题

### ISSUE THREAD

**Issue by YuHaiQing233** [InkTimeRecord/TTime#64]
使用划词翻译功能 在IDEA上翻译Spring源码上的注释时，用起来不太好用，
Mac 上面有个Bob的软件是我一直再用的，但这个软件不支持Windows系统

![image](https://github.com/InkTimeRecord/TTime/assets/30644094/d7e40902-ed9f-4841-aa2a-7862807f8fac)

**Comment by ByLiangCheng** [comment]
你好，目前划词源码对应的注释时，直接划词是存在这种问题

目前的解决方案是，把上面的注释修改成如下这种方式是可以划词的

后续会研究下看看有没有优化方案

![image](https://github.com/InkTimeRecord/TTime/assets/45414993/d29fcb99-f82e-4232-a3f7-9bb02dec7bc1)

![image](https://github.com/InkTimeRecord/TTime/assets/45414993/f2f71af2-7d0f-4dcf-993d-52c9b001a4ca)

**Comment by ByLiangCheng** [comment]
新版本已发布，此问题已解决
