### ISSUE TITLE
V0.0.6 更新后如果翻译窗口打开置顶功能，无法使用ESC键关闭窗口

### ISSUE THREAD

**Issue by Oranlz** [InkTimeRecord/TTime#65]
如标题所示，不知道是不是电脑的问题，但之前使用的时候是可以ESC关闭的。如果不用置顶的话，点一下别的地方窗口就关掉了，比较不符合习惯。

**Comment by ByLiangCheng** [comment]
你好，其实在上个版本中，置顶了之后Esc还可以退出，我这边是记录为BUG的，只是在这个版本中修复了

不过也有其他用户有反馈过这个问题了，已记录下来了，之后考虑在设置中增加配置，可自己选择是否关闭

**Comment by Oranlz** [comment]
好的，毕竟有时候需要将翻译和原文对照着看。不使用置顶的话，翻译窗口在点回原来的地方就会消失，不太方便。希望能够在后面的版本中增加回可自由设置的功能




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "InkTimeRecord/TTime"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月13日(星期六) 下午2:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [InkTimeRecord/TTime] V0.0.6 更新后如果翻译窗口打开置顶功能，无法使用ESC键关闭窗口 (Issue #65)





 
你好，其实在上个版本中，置顶了之后Esc还可以退出，我这边是记录为BUG的，只是在这个版本中修复了
 
不过也有其他用户有反馈过这个问题了，已记录下来了，之后考虑在设置中增加配置，可自己选择是否关闭

**Comment by ByLiangCheng** [comment]
新版本已发布，功能已增加
