### ISSUE TITLE
历史输入记录、“自动检测”翻译方向的功能

### ISSUE THREAD

**Issue by xwxb** [InkTimeRecord/TTime#66]
1. 希望添加“记录历史输入记录功能”。因为在不小心失去窗口焦点的时候就很容易丢失输入的大段内容。

2. 关于“自动检测”翻译方向的功能。当我双向都是自动检测的时候，很容易就是不能识别成 中文 ->  英文，而是英文 -> 英文。我不清楚是怎么判定的，个人的想法是，其实只要文本框检测到极少量中文就可以判定成中文 -> 英文了。

**Comment by ByLiangCheng** [comment]
你好，第一个问题，当大段内容时，通过固定窗口也可以解决吧

第二个问题，"很容易就是不能识别成 中文 -> 英文，而是英文 -> 英文"，这个有举例吗？

**Comment by xwxb** [comment]
> 你好，第一个问题，当大段内容时，通过固定窗口也可以解决吧
> 
> 第二个问题，"很容易就是不能识别成 中文 -> 英文，而是英文 -> 英文"，这个有举例吗？

第一个确实，不加这个功能确实更简洁。是我体验深度不够深 🤣

第二个我后来又发现是翻译引擎的识别问题，抱歉没加例子，确实说的不清楚而且还说错了

比如说这个
![image](https://github.com/InkTimeRecord/TTime/assets/77780051/1c20cea1-2c70-42e0-ba61-2a10b78bd843)
就是好像英文多一点，或者有受符号的干扰，就会中文 -> 中文

**Comment by ByLiangCheng** [comment]
感谢反馈，刚测试发现是有这个问题，我后面看看怎么解决

**Comment by xwxb** [comment]
> 感谢反馈，刚测试发现是有这个问题，我后面看看怎么解决

是的，辛苦了。个人愚见是，或许可以“只要检测到了中文”就判定为“`中文 -> 英文`”翻译方向，毕竟应该不会有 `中文 -> 中文` 的翻译方向，而如果不 i18n 的话可以忽略“英文混少量中文”判定为 `英文->中文` 的翻译方向，否则应该就是调整权重了。

**Comment by ByLiangCheng** [comment]
OKOK，我这边会进行参考一下

**Comment by ByLiangCheng** [comment]
功能已增加

**Comment by pzhren** [comment]
> 

希望添加翻译记录，虽然固定了，但是有时在翻译过程中，查看其他内容不小心点选了翻译图标丢失打断内容且无法返回。希望作者可以考虑下
