### ISSUE TITLE
[BUG] Alt + E 划词翻译无法复制

### ISSUE THREAD

**Issue by xwxb** [InkTimeRecord/TTime#67]
Windows10 21H2
TTime 是最新版本

就是按下快捷翻译快捷键的时候并不会有复制行为，好像偶尔才会触发

**Comment by ByLiangCheng** [comment]
你好，请问使用过之前的版本吗？之前的版本中是否能正常触发划词呢？

**Comment by xwxb** [comment]
> 你好，请问使用过之前的版本吗？之前的版本中是否能正常触发划词呢？

都不行，我就是为了修复这个才更新的，所以记得很清楚

**Comment by ByLiangCheng** [comment]
> > 你好，请问使用过之前的版本吗？之前的版本中是不是能正常触发规划词呢？
> 
> 都不动，我就是为了修复这个才更新的，所以记得很清楚

可以留个邮箱不 我发你一个测试包试试看

**Comment by xwxb** [comment]
> > > 你好，请问使用过之前的版本吗？之前的版本中是不是能正常触发规划词呢？
> > 
> > 
> > 都不动，我就是为了修复这个才更新的，所以记得很清楚
> 
> 可以留个邮箱不 我发你一个测试包试试看

X_Ban@bjfu.edu.cn

**Comment by ByLiangCheng** [comment]
> > > > 你好，请问使用过之前的版本吗？之前的版本中是不是能够正常触发规划词呢？
> > > 
> > > 
> > > 都不动，我就是为了修复这个才更新的，所以记得很清楚
> > 
> > 
> > 可以留个邮箱不是我发给你一个测试包试看
> 
> [X_Ban@bjfu.edu.cn](mailto:X_Ban@bjfu.edu.cn)

已发送

**Comment by xwxb** [comment]
> > > > > 你好，请问使用过之前的版本吗？之前的版本中是不是能够正常触发规划词呢？
> > > > 
> > > > 
> > > > 都不动，我就是为了修复这个才更新的，所以记得很清楚
> > > 
> > > 
> > > 可以留个邮箱不是我发给你一个测试包试看
> > 
> > 
> > [X_Ban@bjfu.edu.cn](mailto:X_Ban@bjfu.edu.cn)
> 
> 已发送

完美解决，辛苦了
