### ISSUE TITLE
[BUG] Ctrl + Shift + P 也会调出划词翻译

### ISSUE THREAD

**Issue by xwxb** [InkTimeRecord/TTime#68]
版本最新 0.0.6

确定和在哪个软件里无关，也不是偶然才有

**Comment by l2iryu** [comment]
同样遇到了，这个热键vscode常用，挺影响体验的。。。

**Comment by ByLiangCheng** [comment]
你好，#63 这个issues中回答了

下个版本中会修复此问题哈

**Comment by xwxb** [comment]
> 你好，#63 这个issues中回答了
> 
> 下个版本中会修复此问题哈

抱歉，辛苦了
