### ISSUE TITLE
建议OCR翻译加入Esc取消

### ISSUE THREAD

**Issue by xwxb** [InkTimeRecord/TTime#69]
不知道是不是只有我没有，如果是的话那就是bug

**Comment by ByLiangCheng** [comment]
这个目前应该是BUG，部分机型触发截图过快时，偶尔会出现ESC无法取消的问题，我这想办法尽量下个版本中修复

**Comment by xwxb** [comment]
> 这个目前应该是BUG，部分机型触发截图过快时，偶尔会出现ESC无法取消的问题，我这想办法尽量下个版本中修复

好的，反复测试应该是都没有，我系统是 Windows10 21H2

**Comment by ByLiangCheng** [comment]
> > 这个目标之前应该是BUG，部分机型触摸发截图过快时，偶会出现ESC无法删除消除的问题，我想办法尽量下个版本中修复
> 
> 好的，复测应该是都没有，我系统是Windows10 21H2

@xwxb 你好，我今天再次做了测试，发现输入窗口在打开时如果触发截图翻译，按下ESC确实无法退出，而当输入窗口没有打开时，直接触发截图翻译，是可以ESC退出的，你这边能否测试一下，看看是不是也是这种情况

**Comment by xwxb** [comment]
> > > 这个目标之前应该是BUG，部分机型触摸发截图过快时，偶会出现ESC无法删除消除的问题，我想办法尽量下个版本中修复
> > 
> > 
> > 好的，复测应该是都没有，我系统是Windows10 21H2
> 
> @xwxb 你好，我今天再次做了测试，发现输入窗口在打开时如果触发截图翻译，按下ESC确实无法退出，而当输入窗口没有打开时，直接触发截图翻译，是可以ESC退出的，你这边能否测试一下，看看是不是也是这种情况

多次测试，确实是这样，就是只有在 TTime 客户端启动在前台的时候时启动 ORC 才无法退出。
其他情况我感觉似乎是在 0.0.7 版本修复的，因为以前感觉任何情况下启动都无法 ESC 退出。

**Comment by ByLiangCheng** [comment]
新版本已发布，问题已修复
