### ISSUE TITLE
能不能加上截图并且把截图识别文字的功能单独分离出来?

### ISSUE THREAD

**Issue by a5855631** [InkTimeRecord/TTime#7]
翻译功能目前用着很好,看作者说之前也是bob的使用者,我跟你一样也是需要windows和mac电脑频繁切换使用,能不能跟bob一样,加上截图功能,并在截图后可以选择翻译文字,或者把截图识别文字做成单独的功能快捷键调用也可以,截图和截图识别文字确实是非常需要的功能,Windows这边之前用的是易用AI,现在想换成大佬你的软件,但是没有截图和截图识别文字又没办法完成替换掉,很尴尬.另外现有的截图翻译,能否加上一个开关选项,自定义截图后是否把识别到的原文字或者翻译后的文字自动拷贝到剪切板.

**Comment by ByLiangCheng** [comment]
好的，感谢你的建议，我这边先记录下来，后续版本会考虑加上去

**Comment by ByLiangCheng** [comment]
新版本已发布，功能已增加
