### ISSUE TITLE
OPENAI API 的 prompt 应该还可以优化一下

### ISSUE THREAD

**Issue by xwxb** [InkTimeRecord/TTime#71]
- TTime版本号 / TTime Version：
0.0.7 beta

- 问题描述 / Description of the issue：

目前感觉还是挺容易受翻译内容影响的，以下是几个例子：

![image](https://github.com/InkTimeRecord/TTime/assets/77780051/dd20f280-e53e-4d11-89bb-2dd53bfc8997)

![image](https://github.com/InkTimeRecord/TTime/assets/77780051/de48e446-11a5-41be-be97-79118b0b2668)

如果需要的话我可以尝试协助改进

**Comment by ByLiangCheng** [comment]
openai最近才开始着手维护起来，进行了一次改造，目前prompt确实还有很多问题，个人精力有限，欢迎一起参与

为了更好的发展，目前也是在犹豫是否对这个项目进行开源

**Comment by xwxb** [comment]
> openai最近才开始着手维护起来，进行了一次改造，目前prompt确实还有很多问题，个人精力有限，欢迎一起参与
> 
> 为了更好的发展，目前也是在犹豫是否对这个项目进行开源

可以问一下技术栈吗？近阶段个人没什么时间，而且前端技术栈不够深。要是开源了可能会尝试，不开源的话感觉没能力参与到核心开发

**Comment by ByLiangCheng** [comment]
> > openai最近才开始着手维护起来，进行了一次改造，目前prompt确实还有很多问题，个人精力有限，欢迎一起参与
> > 为了更好的发展，目前也是在犹豫是否对这个项目进行开源
> 
> 可以问一下技术栈吗？近阶段个人没什么时间，而且前端技术栈不够深。要是开源了可能会尝试，不开源的话感觉没能力参与到核心开发

技术栈是基于electron

可能我误解你说的了，抱歉抱歉

没关系，如果你比较熟悉prompt的话，也可以帮忙一起看看

这个问题我也会先记录下来，同步维护

**Comment by ByLiangCheng** [comment]
@xwxb 新版本中我对openai prompt进行过优化了 有空可以再试试看看
