### ISSUE TITLE
[Feature] 请求支持 OCR.space API，以及想了解一下 TTime 自带源可否离线？

### ISSUE THREAD

**Issue by future93** [InkTimeRecord/TTime#72]
如标题。OCR.space 是与 TTime 相似的老牌聚合翻译软件 QTranslate 唯一可用的、有免费额度的在线图像文本识别引擎，不少 QTranslate 用户（比如我）都因此申请了它的 API 使用权。现在 QTranslate 升天已有一段时日，其最后版本的可用性也在持续降低，不少用户都急于寻找其替代品。因此如果 TTime 能支持使用 OCR.space 的 API 的话，对于像我这样仍然希望能尽可能利用 QTranslate 遗产的用户来说显然会很有吸引力。
OCR.space 的官方网站就是 OCR.space 。
以及，想了解一下，TTime 自带的翻译源是否是离线源？毕竟总是会有不能联网时的需求的。
PS，关于 QTranslate 的所谓“遗产”，其词典模式也是（至少对我个人而言）比较讨喜的一种查询方法，不过它涉及到网页内容抓取什么的一堆麻烦事，因此也只是在这里随口提一句罢了。
又PS，希望能做一个全局快捷键总开关。

**Comment by ByLiangCheng** [comment]
你好，OCR.space之前没有接触过，之后我先了解下这块

TTime目前翻译源不是离线的，是我自己搭建的服务提供的支持，后续会考虑做离线词典支持

**Comment by future93** [comment]
> 你好，OCR.space之前没有接触过，之后我先了解下这块
> 
> TTime目前翻译源不是离线的，是我自己搭建的服务提供的支持，后续会考虑做离线词典支持

感谢解惑。祝开发顺利~
