### ISSUE TITLE
[Feature] 希望可以新增papago翻译

### ISSUE THREAD

**Issue by mrd-mrd** [InkTimeRecord/TTime#73]
**功能描述 / Function Description**
官方可以免费申请papago翻译秘钥的。注册一个naver账号在https://developers.naver.com/ 验证下手机号就可以免费申请到了。每天有1万字符的额度。韩国公司的，韩语翻很厉害

**Comment by ByLiangCheng** [comment]
好的，我先记录下，有时间看看

**Comment by ByLiangCheng** [comment]
新版本已发布，功能已增加
