### ISSUE TITLE
OpenAi翻译的希望可以出一个使用token登录的

### ISSUE THREAD

**Issue by Tzeao** [InkTimeRecord/TTime#74]
OpenAi翻译的希望可以出一个使用token登录的，这样就可以使用免费的chatgpt翻译了

**Comment by ByLiangCheng** [comment]
你好，这块有计划，不过目前了解的不多，后面有时间会研究下看看

**Comment by Tzeao** [comment]
> 
也可以参考这个大佬，他是开源的
https://github.com/pengzhile/pandora
期待您的这个新功能😍

**Comment by ByLiangCheng** [comment]
OKOK

**Comment by Tzeao** [comment]
> OKOK

https://github.com/pengzhile/pandora/issues/837#issuecomment-1585595526
你好，不用token也可以了，只要能够自定义域名

**Comment by ByLiangCheng** [comment]
> > OKOK
> 
> [pengzhile/pandora#837 (comment)](https://github.com/pengzhile/pandora/issues/837#issuecomment-1585595526) 你好，不用token也可以了，只要能够自定义域名

#88 近期会加入
