### ISSUE TITLE
[Feature] 希望在主界面加个ocr的按钮

### ISSUE THREAD

**Issue by liuxianghua1** [InkTimeRecord/TTime#75]
**功能描述 / Function Description**
有时候平板模式没办法用键盘，不好来ocr翻译，希望作者可以在 置顶按钮 一栏 在加个ocr的按钮 这样正好也省的快捷键了

**Comment by ByLiangCheng** [comment]
你好，这个之后会考虑增加鼠标双击时选中文字时出现图标点击进行翻译功能，这个也能解决此问题吧

**Comment by liuxianghua1** [comment]
你好大哥 就是有的时候是pdf需要ocr翻译 无法复制文字

**Comment by ByLiangCheng** [comment]
新版本已发布，鼠标双击时选中文字时出现图标点击进行翻译功能已增加
