### ISSUE TITLE
[Feature] 能把不同翻译窗口做成横向标签式吗

### ISSUE THREAD

**Issue by mendylove** [InkTimeRecord/TTime#76]
**功能描述 / Function Description**
现在翻译一次消耗多个翻译源的额度。做成标签式，需要哪个源的结果再点开，就不会同时消耗了。大佬考虑下

**Comment by ByLiangCheng** [comment]
你好，这个有考虑，不过现在需求堆积了不少，功能在一个个添加中

**Comment by ByLiangCheng** [comment]
已更新，版本已经发布
