### ISSUE TITLE
[Feature] 期待出一个mac风格的菜单栏图标

### ISSUE THREAD

**Issue by justincnn** [InkTimeRecord/TTime#80]
**功能描述 / Function Description**

TTime强大的功能和图标太不搭了，期待可以更新一个图标，谢谢

![](https://cdn.jsdelivr.net/gh/justincnn/pictures/img/202306032030279.png)

**Comment by ByLiangCheng** [comment]
你好，这个确实是个问题，最近的版本中会解决一下

**Comment by justincnn** [comment]
> 你好，这个确实是个问题，最近的版本中会解决一下

颜值党还在等着大神更新图标，😄

**Comment by ByLiangCheng** [comment]
> > 你好，这个确实是个问题，最近的版本中会解决了下
> 
> 颜值党还在等着大神更新图标，😄

下个版本更新 🥰

**Comment by ByLiangCheng** [comment]
新版本已发布，功能已增加
