### ISSUE TITLE
[Feature] 首次点击输入框时全选

### ISSUE THREAD

**Issue by CnsMaple** [InkTimeRecord/TTime#81]
点击输入框，常见有：1.修改内容。2.换新内容。
在换新内容的时候，总是要：点击输入框->全选->删去旧内容->写上新内容。
或者有更好的办法？

**Comment by ByLiangCheng** [comment]
你好，这个你可以按下 Alt+Q 调起输入翻译，他会自动清空之前输入框的内容，并获取输入框的焦点，这样流程会变为：按下快捷键->粘贴即可，粘贴后也会自动翻译

如果是从其他窗口复制过来的内容再进行粘贴的花，也可以直接使用Alt+E划词
