### ISSUE TITLE
[BUG] esc功能异常

### ISSUE THREAD

**Issue by CnsMaple** [InkTimeRecord/TTime#82]
请提供下述完整信息以便快速定位问题 / Please provide the following information to quickly locate the problem

- 系统环境 / System Environment：win11

- TTime版本号 / TTime Version：0.2.0

- 问题描述 / Description of the issue：
![image](https://github.com/InkTimeRecord/TTime/assets/92523839/f81324ac-c269-49e1-890f-3b62cde9567d)
如图，这个功能开启后，即使窗口没有焦点，按下esc，它还是退出了。理论上，没有焦点下，按下esc，应该在其他应用产生对应的功能。而不是退出翻译窗口。

**Comment by ByLiangCheng** [comment]
你好，这个功能是当开启后，在翻译窗口置顶的状态下按下ESC是可退出的，当关闭后，按下ESC才无法退出

不过经过你的提示后，我测试发现当我开启后此功能后，再次手动的开关置顶功能会导致此配置无效

**Comment by ByLiangCheng** [comment]
此问题已修复
