### ISSUE TITLE
能否在更新的时候直接更新

### ISSUE THREAD

**Issue by Tzeao** [InkTimeRecord/TTime#83]
能否在更新的时候直接更新，而不用跳到官网下载

**Comment by ByLiangCheng** [comment]
最开始的初版是这么做的，但是后面发现包太大了，直接内置更新下载很慢、Mac没有证书导致更新失败等一系列问题，最终改到了跳转官网下载

有考虑自己重新实现一套更新的方式，因为实现起来会有点麻烦，所以准备后期有时间了优化下
