### ISSUE TITLE
[Feature] 账号登录自动同步数据

### ISSUE THREAD

**Issue by 2842157468** [InkTimeRecord/TTime#84]
**功能描述 / Function Description**
希望可以新增账号登录功能，其他设备登录后可以自动同步数据

**Comment by ByLiangCheng** [comment]
你好，这个功能之前有考虑，不过翻译源的秘钥同步功能管理可能不会做，会有安全泄露风险

**Comment by 2842157468** [comment]
那这样的话可以考虑一下一键导出和一件导入功能😀

**Comment by ByLiangCheng** [comment]
这个近期版本中会加入

**Comment by xdmlove** [comment]
不知道配置的存储在哪个文件夹啊, 我好几台电脑 一个个设置翻译账户 太麻烦了!

**Comment by ByLiangCheng** [comment]
新版本已新增自定义配置文件路径
