### ISSUE TITLE
[Feature] 更强的文本处理

### ISSUE THREAD

**Issue by 18183883296** [InkTimeRecord/TTime#85]
**功能描述 / Function Description**
TTime OCR识别的准确率让我感到惊讶🤩👍。

希望增强OCR识别的文本处理功能：
1. 将复制到剪贴板的OCR识别结果的[换行符]替换为[空格]
2. 统一识别结果的标点形式（中/西文）

对于第二点，考虑人为设置指定标点的形式或存在中文即使用中文标点，否则使用英文标点（满足大多数应用场景）

**Comment by ByLiangCheng** [comment]
你好，关于两点问题：
1.关于[换行符]替换为[空格]这个，在设置中可以开启，但是不处理OCR文本识别的结果，而是对翻译结果的换行符替换处理
2.关于标点符号的问题，这个目前识别效果还没有那么强，后期优化可能会考虑

**Comment by 18183883296** [comment]
> 你好，关于两点问题： 1.关于[换行符]替换为[空格]这个，在设置中可以开启，但是不处理OCR文本识别的结果，而是对翻译结果的换行符替换处理 2.关于标点符号的问题，这个目前识别效果还没有那么强，后期优化可能会考虑

是的，我希望增加新功能选项，能够对复制到剪贴板中的换行符做替换处理。

**Comment by ByLiangCheng** [comment]
> > 你好，关于两点问题： 1.关于[换行符]替换为[空格]这个，在设置中可以开启，但是不处理OCR文本识别的结果，而是对翻译结果的换行符替换处理 2.关于标点符号的问题，这个目前识别效果还没有那么强，后期优化可能会考虑
> 
> 是的，我希望增加新功能选项，能够对复制到剪贴板中的换行符做替换处理。

请问这么做是使用在什么场景呢？

**Comment by ByLiangCheng** [comment]
> > 请问这么做是使用在什么场景呢？
> 
> 当前的版本提供了将OCR结果写入剪贴板的选项，在该选项被启用的任何场景，用户都应该期望得到规范化的文本格式。比如对一个英文段落进行OCR识别并写入剪贴板，每行末尾的换行符总是多余的。

你的这个回复我有点迷糊，当前这个问题和你上文描述的是一件事情吗？

如果问题是：“开启 [ OCR结果写入剪贴板 ] 选项后，OCR后自动写入剪切板的内容行尾是存在换行符” 
我这边目前测试没有出现这种情况，因为这个是有处理的，你能复现吗？

**Comment by 18183883296** [comment]
> 如果问题是：“开启 [ OCR结果写入剪贴板 ] 选项后，OCR后自动写入剪切板的内容行尾是存在换行符” 我这边目前测试没有出现这种情况，因为这个是有处理的，你能复现吗？
如此设置，
![QQ截图20230608222042](https://github.com/InkTimeRecord/TTime/assets/89304297/8f820f75-95bf-4738-b9fb-32277cf93a5c)
识别英文段落
![QQ截图20230608222151](https://github.com/InkTimeRecord/TTime/assets/89304297/7786ac84-c349-41d7-9966-caed47f4bf42)
OCR识别后导入到剪贴板中的结果
![QQ截图20230608222230](https://github.com/InkTimeRecord/TTime/assets/89304297/e11f5dc6-c458-49df-9f27-79d96b2f50e7)
显然，识别结果分成了5行，我并未看到将行尾换行符替换为空格的有效处理。

**Comment by ByLiangCheng** [comment]
哦明白你的意思了，抱歉，我之前的理解有误

你说的是合理的，这个我会思考一下，或许近期版本中会加入

**Comment by ByLiangCheng** [comment]
新版本已发布，功能已修复
