### ISSUE TITLE
[BUG] 多个屏幕下，鼠标悬浮球取词错位

### ISSUE THREAD

**Issue by CnsMaple** [InkTimeRecord/TTime#86]
请提供下述完整信息以便快速定位问题 / Please provide the following information to quickly locate the problem

- 系统环境 / System Environment：win11

- TTime版本号 / TTime Version：0.3.0

- 问题描述 / Description of the issue：多个屏幕下，鼠标悬浮球取词错位

**Comment by ByLiangCheng** [comment]
你好，屏幕设置的缩放与布局设置比例不是100%吧？

刚测试发现非100%下是有这个问题，下个版本中修复

**Comment by CnsMaple** [comment]
似乎是缩放的问题，我设置成100%就没有这个问题了，我想提一点，点击悬浮球的时候，窗口可以显示在球的附近吗，或者是鼠标附近什么的？

**Comment by CnsMaple** [comment]
似乎是缩放的问题，我设置成100%就没有这个问题了，我想提一点，点击悬浮球的时候，窗口可以显示在球的附近吗，或者是鼠标附近什么的？ @ByLiangCheng

**Comment by ByLiangCheng** [comment]
近期会考虑此功能
