### ISSUE TITLE
[Feature] 自动更新流程优化问题

### ISSUE THREAD

**Issue by wang-bailin** [InkTimeRecord/TTime#89]
**功能描述 / Function Description**
RT

**Comment by ByLiangCheng** [comment]
你好，目前没办法，就算加了自动更新也会弹窗提示的

如果你实在不想更新的话可以在设置里面关闭自动检测新版本设定

**Comment by wang-bailin** [comment]
理解，其实不是嫌弃弹窗，主要是不习惯每次都跳转、下载、手动安装，如果弹窗时能直接点更新，直接出个进度条就完成了，就很好了。

**Comment by ByLiangCheng** [comment]
> 理解，其实不是嫌弃弹窗，主要是不习惯每次都跳转、下载、手动安装，如果弹窗时能直接点更新，直接出个进度条就完成了，就很好了。

了解了，这个之前也有人问过，你可以看看 #83

**Comment by wang-bailin** [comment]
收到。
