### ISSUE TITLE
提个建议：划词--浮现TTime小图标--点击翻译

### ISSUE THREAD

**Issue by goeway** [InkTimeRecord/TTime#9]
提个建议：

划词翻译的方法，能否增加如下功能：
划词---浮现TTime小图标---点击小图标，打开翻译结果窗口

这样子就能一只手就能实现划词翻译了

**Comment by ByLiangCheng** [comment]
这个功能建议已经记录，后续版本会考虑加上

**Comment by CrystalWyz** [comment]
很“有道翻译”~

**Comment by ByLiangCheng** [comment]
新版本发布，此功能已更新
