### ISSUE TITLE
[Feature] 关于翻译源支持音标及悬浮球翻译的一些功能建议

### ISSUE THREAD

**Issue by InRunning** [InkTimeRecord/TTime#90]
**功能描述 / Function Description**
可以添加显示音标的翻译源吗，然后添加一个设置，划词显示翻译图标后鼠标移动到图标直接翻译，不需要再点击一次，这样比较方便

**Comment by ByLiangCheng** [comment]
你好，目前有道翻译源、Bing词典翻译源都是支持音标的，其他的翻译源正在接入中

“划词显示翻译图标后鼠标移动到图标直接翻译” 我之前这样尝试体验过，如果不小心触发了图标，并且刚好滑过了直接触发翻译体验不是很好，后期有时间的话可能会考虑一些更优的方法

**Comment by InRunning** [comment]
只是希望可以增加这个设置，我的使用习惯是这种
