### ISSUE TITLE
[Feature] 建议检测更新操作延后处理

### ISSUE THREAD

**Issue by rogercc116** [InkTimeRecord/TTime#91]
**功能描述 / Function De
能否将检测更新操作延后处理，因为clash代理启动需要时间目前来看检测更新先于clash启动启动
![image](https://github.com/InkTimeRecord/TTime/assets/63380214/00470ba4-5cd4-4adb-aa18-77639ee37afc)
scription**

**Comment by ByLiangCheng** [comment]
你好，这个情况确实可能会存在，近期版本会优化一下

**Comment by ByLiangCheng** [comment]
新版本已发布，功能已增加
