### ISSUE TITLE
捐赠了杯奶茶，希望可以越来越好顺便提个建议[Feature] ♥️♥️🎇🎇

### ISSUE THREAD

**Issue by T0sng** [InkTimeRecord/TTime#93]
**功能描述 / Function Description**
我觉得翻译在双击或者划词之间可以考虑更优解的办法，就是可以设置一个热键比如:“alt” 需要翻译内容的时候按住“alt”不松开，然后鼠标划过需要翻译的内容，等到松开“alt”以后开始进行翻译，这样可以避免考虑设置进程黑名单，打游戏的时候退出软件，偶尔不小心误碰突然弹出来翻译等等诸如类似的情况。希望作者可以考虑一下，看到官网留下的支付宝，捐赠了份心意，不是很多希望开发者不要嫌弃，希望软件可以越来越好 。值得更多人发现♥️♥️😄😄🎆🎇

**Comment by ByLiangCheng** [comment]
首先感谢支持会继续努力 🙏🙏🙏

这个建议我会先收集起来，有时间的时候会看看这块的优化，因为现在功能堆积的有些多，所以也是在一点点增加和改进中

**Comment by ByLiangCheng** [comment]
新版本已发布，托盘菜单开启/停用快捷键功能已支持 ～
