### ISSUE TITLE
[Feature] English UI

### ISSUE THREAD

**Issue by iG8R** [InkTimeRecord/TTime#94]
Hi.
Is it possible to add English UI?

**Comment by ByLiangCheng** [comment]
Hello, there are plans to increase, but now more functional requirements, time is not so abundant, is increasing bit by bit

**Comment by iG8R** [comment]
OK. Thanks.

**Comment by iG8R** [comment]
Hello.
Is there any chance that in the near future English UI will still appear?

**Comment by ByLiangCheng** [comment]
> Hello. Is there any chance that in the near future English UI will still appear?

Sorry, it took so long. There are plans to add English UI in one or two versions in the near future.

**Comment by iG8R** [comment]
Thanks! At least there's some hope now :)
And one more question - is there any way to register on https://ink.timerecord.cn with a foreign phone number?

**Comment by ByLiangCheng** [comment]
> Thanks! At least there's some hope now :) And one more question - is there any way to register on https://ink.timerecord.cn with a foreign phone number?

Sorry, it is not supported yet. We will develop support for overseas mobile phone number and email registration in the future. If you need it, you can currently send the email address you need to register to support@timerecord.cn, and I will open an account for you.

**Comment by iG8R** [comment]
> If you need it, you can currently send the email address you need to register to [support@timerecord.cn](mailto:support@timerecord.cn), and I will open an account for you.

Thank you a lot! I've already sent an e-mail.


> We will develop support for overseas mobile phone number and email registration in the future.

I wish you good luck!

**Comment by ByLiangCheng** [comment]
Functionality has been updated and version has been released

**Comment by iG8R** [comment]
Thanks a lot!
