### ISSUE TITLE
[BUG] 高分屏幕下OCR问题

### ISSUE THREAD

**Issue by Xiayuno111** [InkTimeRecord/TTime#96]
请提供下述完整信息以便快速定位问题 / Please provide the following information to quickly locate the problem
高分屏幕下OCR模糊
- 系统环境 / System Environment：
win11

- TTime版本号 / TTime Version：
0.4.0

- 问题描述 / Description of the issue：
高分屏幕下OCR模糊 如图
![image](https://github.com/InkTimeRecord/TTime/assets/120300365/aee1519f-f3af-4c42-a7dd-dfee60f755a9)

**Comment by ByLiangCheng** [comment]
是4K屏吗？

**Comment by Xiayuno111** [comment]
> 是4K屏吗？

是的,

**Comment by iwei000** [comment]
![image](https://github.com/InkTimeRecord/TTime/assets/16318592/5b3a0f62-9254-46c2-98d0-be0fa6f4f5bc)

同样有这个问题，也是4K

**Comment by iwei000** [comment]
![image](https://github.com/InkTimeRecord/TTime/assets/16318592/5b3a0f62-9254-46c2-98d0-be0fa6f4f5bc)

同样有这个问题，也是4K

**Comment by ByLiangCheng** [comment]
OK 我排查一下

**Comment by YuI2333** [comment]
> OK 我排查一下

2K下也模糊，导致OCR不准

**Comment by kailisx** [comment]
高分辨率都模糊，开系统增强DPI也模糊

**Comment by ByLiangCheng** [comment]
问题已修复，新版本已发布
